README.md
circle.yml
package.json
src/Fonts.tsx
src/Text.tsx
tsconfig.json
yarn.lock

Adds `semantic-release` for automated NPM publishing, as well as a CircleCI config.

[Lib] Add semantic-release and circle config

---

src/elements/Typography.tsx

Wrap components with `styled` so that we can control them more granularly

[PATCH typography] Wrap exports in styled wrapper

---

src/elements/Typography.tsx
src/palette.d.ts

This supports using the `verticalAlign` prop on `Sans`, `Serif`, and `Display` components. 
`verticalAlign` isn't supported by styled-system out of the box, so this is another one of those special cases where I had to create it... not sure about where the types go. We might want to create a package kinda dedicated to these special things... or make PRs for them to styled system.

Support vertical-align on text components

---

src/Theme.tsx

Currently the designs have the cutter at 20px. This updates the col padding to reflect that.

Update grid gutter to match designs

---

src/Theme.tsx

Moves the media queries here and out of reaction. There's a bit of duplication between these definitions and the grid definitions. These values should be usable directly in styled-components.

Add mediaQueries to theme

---

src/Theme.tsx
src/elements/Typography.tsx
src/platform/fonts/fontFamily.ios.ts
src/platform/fonts/fontFamily.ts
src/platform/fonts/index.ts

This adds support for platform specific font declarations. The font families implement the same interface across platforms. 
Also adds a helper to allow expressing more complex font-family configurations (like when we have to define weight, style). 
Adds fallbacks for web. Might want to double check  those and update any that are missing.

Add platform specific fonts

---

package.json
src/Theme.tsx

This fixes our typechecking so that `yarn type-check` also emits declarations and thus catches associated interface needs.

[PATCH toolchain] Fix typechecking

---

src/Theme.tsx

(Noticed it effecting nested columns, realized not needed.)

[PATCH grid] Remove unneeded padding

---

src/platform/fonts/fontFamily.ts

We were missing fallback fonts for unica. This adds them. 
It also adds type styles and font weights in the appropriate places so that the fallback text preserves the correct look.

Add fallback fonts for unica

---

src/Theme.tsx

This updates the keys of our space theme settings to be numbers instead of strings. 
This change will correct the types for anything referencing space keys. 
For example, this will allow the `space` helper to be used like `space(0.3)` instead of `space("0.3")`

Update space keys to be numerical

---

src/platform/fonts/fontFamily.ios.ts

Some of the font names were messed up for ios. This should fix them.

Correct font name issue on ios

---

src/Theme.tsx
src/helpers.ts
src/index.tsx

The types for colors and spaces are useful in other places. This just defines and exports them explicitly so we don't have to keep redefining them.

[FEATURE types] Exposes type defs for colors and spacing values

---

src/Theme.tsx
src/elements/Typography.tsx

Directly exports the sizes for the typography components so that they can be reused in reaction.

Expose type sizes for easier external typing

---

src/index.tsx

Another update to expose some of the types so that they don't have to be manually imported from a sub-module.

Export typesizes from the index

---

src/Theme.tsx
src/elements/Typography.tsx
src/index.tsx

After using this in reaction it didn't really feel right to use `size: SansSizes`. I think `SansSize` feels better as a type being as its not a list of types.

Updates types to not be plural

---

src/Theme.tsx

adds [purple5](https://www.notion.so/artsy/purple-47f26e30e0604d79accdb791c2ba2aaa) to `colors` + corrects `purple30` comment.

adds purple5 #minor

---

src/Theme.tsx
src/helpers.ts

This adds an easy way to build media query strings with palette.
```javascript
styled.div`
${media('xl')} {
display: none;
}
`
```

Add media query helper function

---

src/index.tsx

This exports the media helper that was created previously.

Export media helper

---

src/Theme.tsx

Tested on:
* Safari
* Chrome
* FireFox
* MobileSafari
According to docs it _should_ work on:
* [Chrome for Android](https://caniuse.com/#feat=css-media-interaction)
* [Opera](https://dev.opera.com/articles/media-features/)
* [IE11](https://msdn.microsoft.com/en-us/library/bg124120(v=vs.85).aspx)
* [Edge](https://caniuse.com/#feat=css-media-interaction)

[MINOR Theme] Add hover media query to detect hoverable devices

---

src/elements/Typography.tsx
tsconfig.json

Adds a property that only exists in the React Native `Text` primitive. Had a good debate with @zephraph about whether this the the best abstraction, but given that it's one property when porting a complex set of screens it's probably alright for now. 
It's likely we'll need something more complex later for bigger design system elements.

Adds the ability to set the number of lines for a text element in React Native

---

src/elements/Box.tsx
src/elements/Flex.tsx
src/elements/Join.tsx
src/elements/Separator.tsx
src/elements/Spacer.tsx
src/platform/primitives.ios.ts
src/platform/primitives.ts

Adds base layout primitives, which were first tested out in Emission to see what would work: 
- `Box`
- `Flex`
- `Join`
- `Separator`
- `Spacer`
In `Box` we have some Web-specific values that will need to be updated but need to discuss approach.

WIP => [Primitives] Add layout primitives

---

src/elements/Box.tsx
src/index.tsx

This is a continuation of #65 which I might've kinda accidentally merged. I'm just going to keep the work going in this PR. 
Original description below
---
Adds base layout primitives, which were first tested out in Emission to see what would work: 
- `Box`
- `Flex`
- `Join`
- `Separator`
- `Spacer`
In `Box` we have some Web-specific values that will need to be updated but need to discuss approach.

[WIP] Update layout primitives

---

src/Theme.tsx
src/elements/Box.tsx
src/elements/Flex.tsx
src/elements/Join.tsx
src/elements/Separator.tsx
src/elements/Spacer.tsx
src/elements/Typography.tsx
src/platform/fonts/fontFamily.ios.ts
src/platform/fonts/fontFamily.ts
src/platform/fonts/index.ts
src/platform/primitives.ios.ts
src/platform/primitives.ts
tslint.json

This PR needs additional work, @zephraph - any chance you could throw 15m at adding some of the additional fails? It's things like `Box`, `Flex` etc, which I don't really understand enough to feel like I should be writing the core docs.
I didn't add interfaces in here, I don't think that matters too much. In the most ideal state, we turn on properties so and people know what all the options in props are - but I'm not sure if that's overkill.

Adds a tslint config requesting JSDoc for exporting components, and does some of the easier comments

---

package.json
yarn.lock

Attempting to lock TS version to that which is in Emission until it can be updated to 3.0.

[PATCH lib] Match typescript version to Emission 2.5.3

---

doczrc.js

Updates routes to support a `/#/` so that deeplinking works. Can flip this off once we figure out how to support dynamic urls.

[Docs] Update router to use hash for deeplinking

---

docs/Select.mdx
src/elements/Select.tsx

Adds a disabled prop and state to `LargeSelect`. I'm not aware of an official spec for this, but I followed the design seen [here](https://app.zeplin.io/project/5ab94282c124db8d58365b47/screen/5b7c5afcd2b23b7c8a0c3a2e) and followed the disabled state of `Radio` for how to handle the hovered disabled state - `default` cursor.

feat: add disabled prop to select

---

docs/Select.mdx
src/elements/Select.tsx

This PR adds border styling to our `Select` html elements.
Spec: https://app.zeplin.io/project/5acd19ff49a1429169c3128b/screen/5ace8399553bdae0668efe69
Tracked in https://artsyproduct.atlassian.net/browse/PURCHASE-504
cc @damassi 
The gif below doesn't capture it well but the `border-transition` property is working identically to the other components (whose borders are controlled by reaction).
(from `yarn link`ed in reaction )storybook:

add styling to border

---

src/elements/Select.tsx

Simple fix to move the arrow into the target area and vertically aligning it with the label on the `Select` component. As of now it's a bit misleading as it's outside of the target area.

[PATCH select] make arrow clickable

---

src/elements/Avatar/Avatar.tsx
src/elements/BorderBox/BorderBox.tsx
src/elements/BorderBox/BorderBoxBase.tsx
src/elements/Box/Box.tsx
src/elements/Button/Button.tsx
src/elements/Checkbox/Checkbox.tsx
src/elements/Colors/Colors.tsx
src/elements/Flex/Flex.tsx
src/elements/Message/Message.tsx
src/elements/Radio/Radio.tsx
src/elements/RadioGroup/RadioGroup.tsx
src/elements/Select/Select.tsx
src/elements/Separator/Separator.tsx
src/elements/Slider/Slider.tsx
src/elements/Spacer/Spacer.tsx
src/elements/StackableBorderBox/StackableBorderBox.tsx
src/elements/Tooltip/Tooltip.tsx
src/elements/Typography/Typography.tsx
src/elements/__tests__/Avatar.test.tsx
src/elements/__tests__/Button.test.tsx
src/elements/__tests__/Join.test.tsx
src/elements/__tests__/RadioGroup.test.tsx
src/elements/__tests__/Typography.test.tsx
src/helpers/__tests__/color.test.ts
src/helpers/__tests__/media.test.ts
src/helpers/__tests__/space.test.ts
src/helpers/color.ts
src/helpers/media.ts
src/helpers/space.ts
tsconfig.json

Remove absolute path imports. 
See https://github.com/Microsoft/TypeScript/issues/15479#issuecomment-300240856 for more info.

[FIX absPaths] Remove abs paths due to type emission

---

.yarnrc

Brought up by @javamonn in [slack](https://artsy.slack.com/archives/C03J4L2KK/p1539016467000100). 
Yarn 1.11+ will have the auto checksum disabled behind a flag because it was technically a major difference released under a minor version update. See the [yarn issue](https://github.com/yarnpkg/yarn/pull/6465) for more. 
cc @alloy, @damassi

Preempt issues w/ yarn 1.11+ from removing integrity checks

---

src/elements/Tooltip/Tooltip.tsx

Some minor QA feedback from @nicoleyeo …

[FIX tooltip] Darken the tooltip drop shadow

---

docs/Banner.mdx
docs/Icons.mdx
src/elements/Banner/Banner.tsx
src/elements/Banner/index.tsx
src/elements/Checkbox/Checkbox.tsx
src/elements/__tests__/Banner.test.tsx
src/elements/index.tsx
src/index.tsx
src/svgs/Check/Check.tsx
src/svgs/Check/index.tsx
src/svgs/CloseIcon/CloseIcon.tsx
src/svgs/CloseIcon/index.tsx
src/svgs/index.tsx

This PR is for #110 and represents some messing around with how we might do SVGs. Open to thoughts and ideas!! ❤️ 
Here's some shots of the component:
While working on this I explored an idea I had about getting SVG images into Palette. I made `src/svgs` and then created `CloseIcon` in there for the purposes of completing the Banner component. Then, I took a stab at pulling out the other SVG in the Checkbox element.
From there, I added a page for Icons that looks like this:
So this is one way we could do it. Would love feedback.

Add banner

---

docs/Join.mdx

Hiya!
Love the work you all have done with this. Been poking around the source for inspiration while building out @edenhealth's style guide / design system, and stumbled upon this missing import:

[FIX join] Add missing `Separator` import.

---

package.json
yarn.lock

Add missing `static-extend` dep. Seen this in a few node repos lately, not sure whats up.

[PATCH dep] Add missing static-extend dep?

---

.github/ISSUE_TEMPLATE/component-spec.md

Per discussion in previous design system syncs — we want to provide ourselves with checklists to improve the quality of the components we are delivering, and to ease the cognitive burden of remembering all the things.
To that end, @jeffreytr and I worked up one design- and one engineering-focused checklist to add to the issue template. 
These are not meant to be exhaustive, nor to serve as blockers for any particular PR. Rather they are intended to visibly signpost common goals and to help us be on the same page. If this or that item on the checklist doesn't feel right we should definitely feel free to iterate on these.

Add design and engineering checklists to issue template

---

package.json
src/elements/BorderBox/BorderBox.tsx
src/elements/BorderBox/BorderBoxBase.tsx
src/elements/Box/Box.tsx
src/elements/Button/Button.tsx
src/elements/Checkbox/Checkbox.tsx
src/elements/Colors/Colors.tsx
src/elements/Flex/Flex.tsx
src/elements/Image/Image.tsx
src/elements/Radio/Radio.tsx
src/elements/Select/Select.tsx
src/elements/Separator/Separator.tsx
src/elements/Spinner/Spinner.tsx
src/elements/StackableBorderBox/StackableBorderBox.tsx
src/elements/Tooltip/Tooltip.tsx
src/elements/Typography/Typography.tsx

Adds a few new cli commands to make working in Emission a bit easier in the absence being able to `yarn link` changes between modules: 
```sh
yarn compile:emission
yarn watch:emission
```
The flow when working is to start emission and then run, in a second pane, `yarn watch:emission` which will then start the `emitDeclaration` + compile process. Changes are reflected instantly: 
(**Note:** This presumes that an `/emission` folder exists alongside `/palette` on the developer's HD)

[Toolchain] Add emission-related package.json scripts

---

src/elements/Radio/Radio.tsx

Problem: the radio label content can't expand to fill parent space
Solution: add `flex-grow: 1;` to the label
I had a look at other usages of `Radio` in reaction and this does't affect any of them. Couldn't find any usages in other projects, but would be good for someone else to double-check.

[patch radio] make radio label grow

---

src/elements/Collapse/Collapse.ios.tsx

As part of ongoing Local Discovery work, we needed an animated `Collapse` implementation and wanted to extend the existing implementation in Palette. We ran into a couple issues while building this out:
- `react-spring` has a `peerDependency` [on `react` at `>=16.4.0`](https://github.com/drcmda/react-spring/blob/v5.9.2/package.json#L111). It looks like it depends on [`React.forwardRef`](https://reactjs.org/docs/forwarding-refs.html), a feature added in React 16.3. Emission is on `16.3.0-alpha.1` and appears to not have this feature, causing `react-spring` to throw an error. I'm opting to pin `react-spring` via `resolutions` in emission at 5.5 (the latest working version) rather than downgrade the version used in palette as we are in the process of upgrading React Native and could upgrade …

[FEATURE ios] Add Collapse implementation

---

package.json
src/elements/Banner/Banner.test.tsx
yarn.lock

Adds [`jest-styled-components`](https://github.com/styled-components/jest-styled-components#tohavestylerule) for testing against style rules. 
Example: 
```js
it("has default red background", () => {
const message = "There was an error."
const wrapper = mount(<Banner message={message} />)
expect(wrapper).toHaveStyleRule("background-color", "red100")
})
```

[Tooling] Add jest-styled-components

---

docs/Tooltip.mdx

Provide the required `size` attribute to `<Sans>` components in the `<Tooltip>` component docs.

Fix Tooltip component docs

---

docs/Tooltip.mdx
yarn.lock

Just wanted to see what we currently have as a tooltip and wanted it to load:)
But the real question I have is - wondering how to do this more permanent closable popup like the one that is defined here: https://app.zeplin.io/project/5b113f413ede4bb10dbfdc42/screen/5b354b3f925ef06d24e323f0
Want to have the wrapper style and positioning logic from tooltip essentially but add close button and support for more elaborate content.
I think for now I would just copy needed things but we should probably have a more generic style for positioning and bordering that can be included wherever.

#minor fix to docs

---

docs/Link.mdx
src/elements/Link/Link.tsx

While the border is helpful when focusing on a link and using the tab key to move forward, it looks too disruptive for most of our default
links. Let's just remove it for now and re-visit when we think we really need it.
Also adding href to <Link> otherwise browsers do not apply default styles to link tags.

Remove the purple border from <Link>

---

.circleci/config.yml

Vastly simplifies the circleci config by reusing jobs in the `yarn` orb. Did the same thing in reaction.

Simplify circleci config by relying on orbs

---

renovate.json

Ignore the `docs2` gatsby folder for now. 
@zephraph - **very** impressed with how configurable Renovate is!

[Renovate] Ignore docs2 folder

---

src/elements/Pagination/Pagination.tsx
src/elements/Pagination/__tests__/Pagination.test.tsx

Ahhh I realized when trying to get the arrow fix out that the Reaction pagination PR hadn't been merged yet. I started looking closely and realized we can move the tests over here with little effort (just replace responsive parent `<Pagination>` component with explicit reference to Large / Small pagination.

Move Pagination tests

---

src/helpers/injectGlobalStyles.tsx

When creating a `<GlobalStyles>` helper, can now pass additional rules: 
```js
const { GlobalStyles } = injectGlobalStyles(`
a {
text-decoration: none;
}
`)
const MyComponent = props => <GlobalStyles>{props.children}</GlobalStyles>
```

Add ability to pass styles to injectGlobal

---

docs/TextArea.mdx
src/elements/TextArea/TextArea.tsx

This existed in the Reaction version, putting it back for the Palette refactor.

Add placeholder to TextArea component

---

www/content/pages/CHANGELOG.mdx
www/gatsby-config.js
www/package.json
www/src/Boot.tsx
www/src/layouts/DefaultLayout.tsx
www/yarn.lock

Removes react-head and adds react-helmet (since the newer version seems to be ideal API-wise)
Palette should deploy after this.

Add react-helmet

---

www/content/docs/index.mdx
www/gatsby-node.js

We want people to see the about page by default.

Redirect palette traffic to the about page

---

www/static/admin/config.js

I've only got it enabled for prod because it only works with the github backend.

Use editorial workflow when deployed

---

README.md

This adds a Netlify status badge, as described [here](https://www.netlify.com/blog/2019/01/29/sharing-the-love-with-netlify-deployment-badges/).

Add Netlify status badge

---

www/content/docs/components/index.mdx
www/content/docs/elements/index.mdx
www/content/docs/tokens/index.mdx
www/content/docs/utilities/index.mdx
www/src/components/Sidebar/NavTree.tsx

Expand first level nav items on load

---

package.json

(peril got mad at me for not having a description sorry). When trying to start palette locally, noticed that `yarn docs` no longer worked after we moved to Gatsby. Turns out there should be a `yarn install` that takes place in the `www` directory; this adds that to the `yarn docs` script

updates docs command with yarn install

---

.babelrc
package.json
src/elements/BorderBox/BorderBox.tsx
src/elements/Box/Box.tsx
src/elements/Flex/Flex.tsx
src/elements/Grid/Grid.tsx
src/elements/Image/Image.tsx
src/elements/Link/Link.tsx
src/elements/Spacer/Spacer.tsx
src/elements/StackableBorderBox/StackableBorderBox.tsx
src/elements/Typography/Typography.tsx
src/helpers/__tests__/media.test.ts
src/helpers/injectGlobalStyles.tsx
www/gatsby-node.js
www/package.json
www/yarn.lock
yarn.lock

Fixes `yarn link` when working in docs by enforcing styled-components resolution to `www/node_modules/styled-components`. 
Also add babel-plugin-styled-components so we can see styled components' displayNames when looking at the dom.

Fix yarn linking with docs

---

src/elements/Radio/Radio.tsx
www/content/docs/elements/inputs/Radio.mdx
www/content/docs/elements/inputs/RadioGroup.mdx

This is a backwards compatible change to improve the API of the `Radio` element
Before this PR, anything you pass to the `children` of a `Radio` will be dumped inside a `<label>`. This is bad semantically if you start putting other form elements in there, because the first of those inputs becomes the *labelled input*.  Obviously the radio button should be the labelled input, not any text boxes or other controls you put inside it.
This also causes weird interactions in mobile safari where tapping anything inside the label focuses on the first input inside the label, meaning you can't focus on the second input if there is one (which there is in one of our flows).
I added another prop which can be used to explicitly set the `label` content. If you pass this prop *and* children, then the …

Add `label` prop to Radio

---

src/helpers/injectGlobalStyles.tsx
www/content/docs/home/getting-started.mdx
www/src/layouts/DefaultLayout.tsx

@damassi noticed that Force was making two calls to get all-webfonts.css as a result of the file being referenced both there and in Palette. To keep Palette flexible and prevent duplicate calls, we removed the automatic import from Palette's global styles and instead made it a call in our Gatsby site.

Stop palette from automatically including all-webfonts.css

---

package.json
www/package.json
www/yarn.lock
yarn.lock

Updates to latest.
Note that `@types/styled-components` hasn't been updated yet since it leads to compatibility issues with our version of react. Will need to do that at the same time.

Upgrade styled-components@4.1.3

---

src/elements/Flex/Flex.tsx

Noticed that the `<Flex>` component wasn't responsive. So now it defaults to flex, but then the user can override with responsive props, which is good for layouts: 
```jsx
<Flex display={['none', 'flex']}>...</Flex>
```

[Flex] Make `display` prop responsive

---

src/elements/Link/Link.tsx
www/content/docs/elements/buttons/Link.mdx

After some thought, I took a stab at what I think the API should be for a Link. The problems I'm trying to solve here are how one controls the underline and color properties together and separately. These concepts were intermingled in a way that @pepopowitz and I found difficult to work with - hopefully this is better!! ❤️ 
The first thing I did was extract an enum for the three types of underline behaviors I saw:
* underline the link all the time (default)
* never underline the link (none)
* underline the link on hover (hover)
And I added a prop called `underlineBehavior` to replace the `noUnderline` prop. If you were using that prop, it maps to the `hover` value of `underlineBehavior`.
Next I looked at how I could improve dealing with color. We want our links to be black by default and …

Improve Link API

---

src/elements/Link/Link.tsx

Noticed type failures over [in reaction](https://circleci.com/gh/artsy/reaction/28523?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). 
Also @jonallured, noticed that Prettier wasn't applied to the code which makes me think your repo environment is configured incorrectly. It's totally cool to have prettier disabled in in yr editor but make sure that githooks work and that all commits are processed by them. There are [quite a few](https://github.com/artsy/palette/blob/master/package.json#L105-L117) checks and auto-fixers that take place before code can be committed and / or pushed, most importantly type-checking. This also applies to Reaction, Force and Positron, where we have a similar husky githook-based setup.

[Link] Make underlineBehavior optional

---

src/elements/Link/Link.tsx
src/helpers/injectGlobalStyles.tsx
www/content/docs/elements/buttons/Link.mdx

Noticed another issue when updating API in reaction - by using an `enum` it forces consumers to pass enums to define the behavior, e.g., `underlineBehavior={UnderlineBehavior.NONE}`, which is a bit verbose. 
```sh
ERROR in /Users/cn/Sites/artsy/reaction/src/Components/NavBar/NavItem.tsx
29:44 Type '"none"' is not assignable to type 'UnderlineBehavior'.
27 |       onMouseLeave={() => toggleHover(false)}
28 |     >
> 29 |       <Link href={href} color={hoverColor} underlineBehavior="none">
```
While strings and enums can be compared within code, passing a string as an prop !== enum.string, unless it's coerced. Also fixes a possible regression where underline behavior wasn't being applied by default in our global styles. It's not apparent in Force because we already have a global set of …

Make underlineBehavior simpler for consumers

---

src/elements/Menu/Menu.tsx

Noticed an issue where responsive props weren't being passed through to the menu. (Needed to pass in the `display` styled-system mixin.)

[Menu] Fix responsive props

---

src/elements/Menu/Menu.tsx
www/content/docs/components/Menu.mdx

Updates the `<MenuItem>` so that custom, not `<a>` tag events are supported:
```js
<MenuItem href='/'>Normal Link</MenuItem>
<MenuItem onClick={event => {
event.preventDefault()
...   
}>
Normal Link
</MenuItem>
```

[Menu] Add onClick handler

---

package.json
src/elements/BarChart/MousePositionContext.tsx
src/elements/Typography/determineFontSizes.ts
yarn.lock

This PR aims to get prettier added to our CI setup so that formatting mistakes can be corrected when they are being introduced rather than after the fact. I've updated prettier to the latest which includes a new `check` flag (h/t @orta for finding that). This flag will list the files that have formatting mistakes and then a helpful message that maybe prettier was not run. Docs: https://prettier.io/docs/en/cli.html#check.
This is WIP until I'm able to land https://github.com/artsy/orbs/pull/25 and then I'll come back here and update the `.circleci/config.yml` file with the newer orb version and that new job.

Add prettier check

---

src/elements/Tooltip/Tooltip.tsx
www/content/docs/elements/inputs/Tooltip.mdx

Mainly to be able to have lists and paragraphs in the tooltip.

[Tooltip] Add option to have component as tooltip content

---

packages/palette/src/elements/Toggle/Toggle.tsx

Fixes a little regression due to icon size adjustments: 
Before: 
After:

Fix <Toggle> icon size

---

packages/palette-docs/content/docs/tokens/Typography.mdx
packages/palette/src/elements/Typography/Typography.tsx

This PR adds a prop named `element` to the Typography components, allowing the user to specify what type of element gets rendered. The `element` prop flows through to styled-components as [an `as` prop](https://www.styled-components.com/docs/api#as-polymorphic-prop). 
I attempted to do this, but I ran into a confusing problem. Whenever I specified `as` on a JSX element, the rendered element would lose all other styles that were specified. In fact, the function [`createStyledText`](https://github.com/pepopowitz/palette/blob/62d94bb314a58be2bd93eaece1a87ac3438638d1/packages/palette/src/elements/Typography/Typography.tsx#L171) wouldn't even get called. I dug as far as I could, but I don't really know why it hates the prop being named `as`.
If you've got the courage to investigate why I can't …

Add 'element' property for specifying element type on Typography

---

packages/palette-docs/content/docs/elements/inputs/TextArea.mdx
packages/palette/src/elements/TextArea/TextArea.tsx
packages/palette/src/elements/TextArea/__tests__/TextArea.test.tsx

This PR allows you to specify that a TextArea component is required by passing a `required` prop. Doing so adds a purple `*` after the title:

adds required prop to textarea

---

packages/palette/src/helpers/injectGlobalStyles.tsx

Force contains a reset that wipes out agent/user-agent styles for headings, but reaction/palette do not. Headings can look different in the palette docs & reaction storybooks than they do when they are deployed via Force.
For example, here's what an h2 looked like in the artwork sidebar in Reaction's storybooks:
And here's what it looked like when I linked it into Force:
Adding this h1-h6 reset should make it easier for engineers to build things in storybooks, and have them look identical in Force.

Add CSS reset for headings (h1-h6) to global styles

---

.circleci/config.yml
package.json
yarn.lock

Auto isn't strictly needed as a dependency of the project and the `auto-release` orb job _should_ properly deploy. I'm restoring this to use the old approach to be consistent with our other deployments and to remove the extra dep. 
This would normally be a `Trivial`, but I'm setting it to `Patch` in order to ensure the release process still works.

Go back to auto-release step in orb

---

packages/palette/src/elements/Image/LazyImage.tsx

Fix to ensure avatars take up the full placeholder.

Ensure lazy-loaded images fill placeholder container

---

packages/palette-docs/content/docs/elements/layout/Collapse.mdx
packages/palette/src/elements/Collapse/Collapse.test.tsx
packages/palette/src/elements/Collapse/Collapse.tsx

https://artsyproduct.atlassian.net/browse/PURCHASE-942
On the purchase team we have noticed a couple of issues with the Collapse component animating itself to incorrect heights, or not animating at all when nested. Unfortunately we were not able to resolve them with the current implementation by following the advice outlined [in the react-spring docs](https://www.react-spring.io/docs/props/gotchas#animating-auto)
I therefore propose we use a custom Collapse component with transparent internals. This amounts to ~100 lines of well-commented code.
This approach has a couple of other benefits:
- Lifting the burden on users of Collapse to know about the `height: auto` gotcha and how to mitigate it.
- Reducing web bundle size by 10k gzipped. (Collapse is the only web component so far that uses …

Fix web Collapse component

---

packages/palette-docs/content/docs/elements/inputs/RadioGroup.mdx
packages/palette/src/elements/Radio/Radio.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.test.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.tsx
yarn.lock

Fixes https://github.com/artsy/palette/issues/349
Adds a new `deselectable` prop to `<RadioGroup>` which, if `true`, allows an item within a group to be toggled off and the selected item to be set to `null`.

[RadioGroup] Add deselectable option

---

packages/palette/src/elements/Radio/Radio.tsx

There was a docs build failure that happened because `onSelect` isn't always passed into radio but debounce requires a function to be passed to it. Gating the check fixes the build.

Don't try to debounce if onSelect isn't defined

---

packages/palette/src/helpers/withoutStyleProps.tsx

@mzikherman found a bug caused by the width and height props being removed from an image. This readds those props.

Don't strip width and height props from images

---

packages/palette/src/elements/BarChart/Bar.tsx
packages/palette/src/elements/BarChart/BarChart.test.tsx

See context here: https://artsy.slack.com/archives/C9YNS4X32/p1554200961150900
If a bin has 0 works but is highlighted, display min 10px bar.
__Before:__
__After:__

If the artwork's highlighted bin is empty, default to showing a minimum-height bar

---

packages/palette/src/elements/Flex/Flex.tsx

I had the need of using `background` with `<Flex>` but it doesn't seem to accept it. This will help clean up [the code in Prediction](https://github.com/artsy/prediction/blob/5ddf80542f35b45c4f2a281c434f3e2597799ec6/src/apps/operator/operator3/StartingAsk.tsx#L130-L133): 
```tsx
// TODO: The <Flex /> component should accept the `bg` prop
const Container = styled(Flex)`
background-color: ${theme.colors.white100};
`
```

Add background to <Flex>

---

packages/palette-docs/content/docs/tokens/Color.mdx
packages/palette-docs/gatsby-config.js
packages/palette-docs/src/components/ColorComponent.jsx
packages/palette-docs/src/components/GlobalComponents.jsx

Discussed with @owendodd and Design would like to have the option to not display every color in Palette in the same section, instead picking out a color or group of colors to display.
This is due to a change in the way we're dealing with colors - in [Notion](https://www.notion.so/artsy/Color-a0c24896daf8433d9409aee2146ac267), you can see Primary, Secondary, and Deprecated colors, and these lists will likely grow and change over time.
The docs update in this PR allows greater flexibility by creating a mini-component that takes a color (e.g. `black100`) and outputting a color bar, hex code, and title in the same manner as the old `Colors` page.
After this is merged, @owendodd can create `<ColorComponents />` using the docs admin to match our current colors.
Two things that could be improved …

creates a docs-only <ColorComponent> to allow display of separate colors

---

packages/palette/src/elements/Tooltip/Tooltip.tsx
packages/palette/src/svgs/QuestionCircleIcon.tsx

Removed unused title from help icon
All uses of HelpIcon/QuestionCircleIcon have their own custom tooltip
https://github.com/artsy/reaction/blob/7eb428eb4c16dac01b39efce581f1bf991d90925/src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx#L186-L189
https://github.com/artsy/reaction/blob/7eb428eb4c16dac01b39efce581f1bf991d90925/src/Components/Artist/MarketInsights/MarketInsights.tsx#L134-L138
----
replaced TipSize enum with plain strings. After discussion with Alloy we concluded the enum wasn't adding much and strings were simpler.

Tooltip related changes

---

packages/palette/src/elements/Menu/Menu.tsx

Ensures that the shadow is black so that it doesn't mix strangely with image overlays. 
#trivial

[Menu] Fix drop shadow color

---

packages/palette/src/elements/BarChart/Bar.tsx

Made `cursor: pointer` conditional so that it only applies to bars with onClick functions passed in. This is related to this story: https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=41&modal=detail&selectedIssue=PURCHASE-1035

only apply cursor pointer to bar if it has onclick

---

.circleci/config.yml

When a chromatic test runs on master let's just auto accept any diffs. 
This is recommended by the chromatic docs: http://docs.chromaticqa.com/setup_ci#maintain-a-clean-master-branch

Auto approve chromatic results on master

---

renovate.json

Put palette on the `lib` renovate config. It'll create a masterIssue with non `@artsy` dependencies.

Update to use the @artsy:lib renovate workflow

---

packages/palette/package.json
packages/palette/src/elements/Join/Join.story.tsx
packages/palette/src/elements/Join/Join.test.tsx
packages/palette/src/elements/Join/Join.tsx

The original idea was to skip rendering blank components if those are passed as children to Join. But that is very hard to do without pre-rendering the components first. I've abandoned that idea but added a storybook and a couple of tests in a process for Join component. So those could stay :)
The Storybook entry:

Add storybook for Join component and a couple of more tests.

---

packages/palette-docs/content/docs/home/getting-started.mdx
packages/palette-docs/content/docs/tokens/Spacing.mdx

Looks like some URLs in the documentation need an update after the recent folder structure reorg.

Fix some urls in the documentation

---

packages/palette-docs/content/docs/elements/buttons/Button.mdx
packages/palette/src/elements/Button/Button.test.tsx
packages/palette/src/elements/Button/Button.tsx

See:
- https://artsy.slack.com/archives/C9XJKPY9W/p1557249933014500
- https://github.com/artsy/rosalind/pull/180/commits/0b008d9069ad52aa3eebc51409e0b717331ce50f
This makes the Button component consistent with accessibility best practices and with our other form components by ensuring that passing a `disabled` prop to Button results in the rendered `<button>` DOM element having the `disabled` attribute as well (and not just a css class)

Pass disabled prop down to button DOM element

---

packages/palette/src/elements/Menu/Menu.tsx

Adds an `onClick` event to the Menu interface 
#trivial

[Menu] Add onClick event type to interface

---

packages/palette/src/elements/Radio/Radio.tsx

In https://github.com/artsy/reaction/pull/2439, I found a `Radio` that was setting `selected` based on a prop, but it "wasn't working," because it was wrapped in a `RadioGroup`. In that scenario, `RadioGroup`.`defaultValue` is the correct way to mark the individual `Radio` items as selected.
If you'd like different verbiage, please suggest it!

Add some help for users who might be confused why their `Radio` isn't selected.

---

packages/palette-docs/content/docs/elements/inputs/Select.mdx
packages/palette/src/elements/Select/Select.story.tsx
packages/palette/src/elements/Select/Select.test.tsx
packages/palette/src/elements/Select/Select.tsx

For now I've created this MiniSelect as an additional Select component. The idea is that once it's merged we can go ahead and update all the uses of SmallSelect with MiniSelect and then just kill SmallSelect option here.
The looks:

Add a MiniSelect as a select component

---

packages/palette-docs/static/admin/config.js

@nicoleyeo was having issues creating new pages. She was getting this error: 
I found some [documentation](https://github.com/netlify/netlify-cms/blob/master/website/content/docs/collection-types.md#folder-collections) on the netlify-cms docs that mentioned having a field with `{ name: "title" }` was required unless we specify an `identifier_field`. 
I just added the `identifier_field` to hopefully fix the issue.

Add identifier_field to fix page creation errors

---

packages/palette-docs/content/docs/elements/inputs/Select.mdx
packages/palette-docs/content/docs/elements/inputs/SelectSmall.mdx
packages/palette/src/elements/Select/Select.story.tsx
packages/palette/src/elements/Select/Select.test.tsx
packages/palette/src/elements/Select/Select.tsx

Current view of `SelectSmall`:
Did not do anything to `LargeSelect` for now. I think this is a separate refactor/upgrade.
cc @owendodd, @jeffreytr

rename MiniSelect to SelectSmall and create separate entry for it in docs

---

packages/palette/src/elements/Link/Link.tsx

Adds `display` to available props. 
#trivial

[Link] Add styled-system display mixin

---

packages/palette-docs/content/docs/elements/inputs/Select.mdx
packages/palette/src/elements/Select/Select.tsx

I did a global search in our repos on Github and seems like the only place SmallSelect was used is the reaction and the removal was merged here: https://github.com/artsy/reaction/pull/2475. So killing SmallSelect here.
Also added explicit font definition from Theme for SmallSelect. And made sure that label in this select does not include padding/margin. In Volt the global value for label was sneaking in here:(

remove unused SmallSelect and remove margin/padding on label for SelectSmall

---

packages/palette-docs/content/docs/elements/images/Image.mdx
packages/palette/src/elements/Image/Image.tsx
packages/palette/src/elements/Image/LazyImage.tsx

Collaboration with @jonallured 
Associated with https://artsyproduct.atlassian.net/browse/DISCO-1059
**Update:** I've cleaned up feedback on this PR, and I think it's in mergeable state.
---
We used to block users from right-clicking on any artwork images, to discourage them from downloading them. This functionality disappeared from most of the site as pieces were moved from Force to Reaction.
The original logic to prevent right-click is [based on the CSS class names applied to images or their parent elements](https://github.com/artsy/force/blob/df49a2ac0bfdf99f0ca98158f7788df1e9e584be/src/desktop/components/prevent_right_click/index.jade#L8). 
```
if (
classes.match('artwork') ||
classes.match('seadragon')
) e.preventDefault();
```
As things moved to Reaction, that meant that semantic …

Add the ability to prevent right-click on <Image> elements

---

packages/palette/src/Theme.tsx
packages/palette/src/platform/primitives.ios.ts
packages/palette/src/platform/primitives.ts

We were getting strange errors in Jest, which were tracked down to `/elements` exporting components that didn't have associated `.ios.tsx` stubs:
```
● Test suite failed to run
TypeError: Cannot read property 'rules' of undefined
at createStyledComponent (node_modules/styled-components/dist/styled-components.cjs.js:2193:25)
at templateFunction (node_modules/styled-components/dist/styled-components.cjs.js:1342:12)
at Object.<anonymous> (node_modules/@artsy/palette/src/elements/DataVis/ChartHoverTooltip.tsx:27:35)
at Object.<anonymous> (node_modules/@artsy/palette/src/elements/LineChart/LineChart.tsx:4:1)
```
This adds two for Bar / Line chart, as well as a proper `ThemeProvider` export depending on platform type. 
Once Emission is fully upgraded we should make it a priority to get proper …

Add missing component .ios.tsx stubs

---

packages/palette/README.md

Spent a long time yesterday debugging an issue that ended up resolving to missing `.ios` file stubs. Wanted to add some documentation around this requirement and a why.

[Docs] Add docs around required palette structure

---

packages/palette/src/elements/Typography/Typography.tsx

This issue arose during Emission's Palette upgrade. We were getting weird failures in our tests and it turns out we were wrapping our universal typography component in a web-only `styled` wrapper. 
#trivial

[Typography] Fix styled-components wrapper input path

---

packages/palette/src/Theme.tsx
packages/palette/src/helpers/isReactNative.tsx

Creates a few more `.ios.tsx` stubs for components, and adds a new utility `isReacNative` for checking if we're on a RN platform. Used to conditionally load the our Grid provider.

[ReactNative] Create more stub components

---

packages/palette-docs/content/docs/elements/layout/Flex.mdx
packages/palette/src/elements/Flex/Flex.tsx

This added [`order`](https://developer.mozilla.org/en-US/docs/Web/CSS/order) to `<Flex>` and so that  we can order flexbox items by:
```jsx
<Flex>
<Flex order="2">Item 2</Flex>
<Flex order="1">Item 1</Flex>
</Flex>
```
I also updated the doc to include an example.

Support Flexbox order

---

packages/palette/package.json
packages/palette/src/svgs/EyeOpenedIcon.ios.tsx
packages/palette/src/svgs/HeartFillIcon.ios.tsx
packages/palette/src/svgs/HeartIcon.ios.tsx
packages/palette/src/svgs/Icon.ios.tsx
packages/palette/src/svgs/ShareIcon.ios.tsx
yarn.lock

This PR adds icons that can be consumed by emission via the `react-native-svg` library, which is what we're already using within emission.
I can follow-up by updating all of the remaining icons to have a proper iOS counterpart, but wanted to keep this targeted for now.
Confirmed that it works via an emission link:

Add icons necessary for the iOS artwork view

---

packages/palette/src/elements/Image/Image.shared.tsx
packages/palette/src/elements/Image/Image.tsx
packages/palette/src/elements/Image/LazyImage.tsx

While working on #473, I misunderstood the separation of `Image.tsx`, `Image.ios.tsx`, and `Image.shared.tsx`, and initially added a new web-specific prop to the props that are shared between web _and_ iOS. @zephraph identified my mistake before we merged, but it raised a question of clarity on the roles of these different files. `Image.shared.tsx`, which is intended to be used by both web and iOS, contained several props that are web-specific, and this contributed to me adding another web-specific prop in the wrong place.
This PR moves the web-specific props from `Image.shared.tsx` to `Image.tsx`, via interfaces named `WebImageProps` and `WebResponsiveImageProps`. 
- Did I move the correct props? These are all the ones that I thought were web-specific; let me know if I got any wrong.
- I …

Reorganize image props for web, iOS, and shared Image/ResponsiveImage components

---

README.md
packages/palette/README.md

This adds some documentation around `yarn watch:emission`, for developing components for Emission in the absence of `yarn link`. 
Additionally moves the "Don't forget about ios!" section to the top-level `README`, to improve visibility and co-locate with other development docs.

[Docs] Add docs about `yarn watch:emission`

---

packages/palette/package.json
yarn.lock

As discussed in Slack (https://artsy.slack.com/archives/C02BAQ5K7/p1559667553010600), this PR adds `react-native-svg` to `peerDependencies` of Palette.

Add react-native-svg to peerDependencies

---

packages/palette/src/elements/LineChart/LineChartSVG.tsx

When all values are zero, `maxValue` ends up being zero causing division by zero.
We currently don't support negative values for line chart so this would fix the problem.

Fix error when all linechart values are zero

---

packages/palette/src/elements/StaticCountdownTimer/StaticCountdownTimer.tsx
packages/palette/src/elements/StaticCountdownTimer/__tests__/StaticCountdownTimer.test.tsx

- Previously I had used `% 12` on the hour which was incorrect (would return `0` if noon) as we want to `- 12` from the hour if it's greater than 12. 
- Adds test file for StaticCountdownTimer

Small fix in StaticCountdownTimer hour logic

---

packages/palette/src/elements/StaticCountdownTimer/StaticCountdownTimer.tsx
packages/palette/src/elements/StaticCountdownTimer/__tests__/StaticCountdownTimer.test.tsx
packages/palette/src/elements/TimeRemaining/TimeRemaining.tsx
packages/palette/src/elements/TimeRemaining/__tests__/TimeRemaining.test.tsx

- Checks if hour is zero and returns 12
- Doesn't show 0 state times for countdown clock (e.g. `1d 0h 30m 20s` is now `1d 30m 20s`)
- Adds tests for `TimeRemaining`

Updates to Luxon logic

---

packages/palette/package.json
packages/palette/src/elements/ProgressBarTimer/ProgressBarTimer2.tsx
packages/palette/src/elements/StaticCountdownTimer/StaticCountdownTimer2.tsx
packages/palette/src/elements/StaticCountdownTimer/__tests__/StaticCountdownTimer.test.tsx
packages/palette/src/elements/TimeRemaining/TimeRemaining.tsx
packages/palette/src/elements/TimeRemaining/TimeRemaining2.tsx
yarn.lock

We encountered some snapshot failures in Reaction, so to ensure deploys are still good gonna move new Luxon-based components to v2 files while restoring old.

[Date Components] Move luxon components to v2

---

README.md

Very similar to the section we currently have [in the Reaction README][link].
[link]: https://github.com/artsy/reaction/blob/416aeeac1ac5e4b20fb73b646d02d2f02ffab061/README.md#linking-and-unlinking-with-force

Add README section for linking/unlinking with Reaction

---

packages/palette/src/elements/Tooltip/Tooltip.tsx

When there are multiple tooltips vertically aligned the tooltip content of the one on the bottom can block the hover area of the one above:
adding `pointer-evnets: none` to content. It is also possible to fix this with changing `z-index` along with `opacity` but `pointer-events` is simpler and in fact it is not even possible to get the mouse over the content area when it is visible.

Add pointer-event: none to tooltip content

---

packages/palette/src/elements/Avatar/Avatar.ios.tsx
packages/palette/src/elements/EntityHeader/EntityHeader.ios.tsx

Reusable palette component created to be used for partner card and other follow button components.
__User story__
As a user, I can tap the “follow” button to follow, or “unfollow” button to unfollow the entity.
__Spec__
https://zpl.io/2Egzy5y

PURCHASE-1060/PURCHASE-1059: iOs Entity Header palette component

---

packages/palette/src/elements/Button/Button.ios.tsx
packages/palette/src/elements/Button/Button.shared.tsx
packages/palette/src/elements/Button/Button.tsx
packages/palette/src/elements/Button/index.tsx
packages/palette/src/elements/Spinner/Spinner.ios.tsx
packages/palette/src/elements/Spinner/Spinner.shared.tsx
packages/palette/src/elements/Spinner/Spinner.tsx
packages/palette/src/elements/Spinner/index.tsx

This PR ports the Button and Spinner component from emission into palette. This also sets some guidelines on how to share common code and interfaces between React Native and React Web version of a component.
Note this works best for components that behave essentially the same on both platforms and can thus share a common interface.
Design spec:

Button & Spinner Component for React Native

---

packages/palette/src/elements/LineChart/LineChart.tsx

Adding back `LineChart` props type export that was removed by mistake [here](https://github.com/artsy/palette/pull/495/files#diff-d7d8d5bdf3d113a828a162de67c18d21L18)

Adds LineChart props type export

---

packages/palette/src/elements/DonutChart/DonutChart.tsx

Addresses [GALL-1864](https://artsyproduct.atlassian.net/browse/GALL-1864)
After [react-spring update](https://github.com/artsy/palette/pull/511) animations broke. Each react render causing animation to trigger again:
This fixes that. Seems to be `Spring` internal state bug. Will try to find the minimal code for reproducing it to report it but this fixes that.

Fix donut chart animation bug

---

packages/palette/src/elements/Avatar/Avatar.ios.tsx

- Fixes typo for `borderRadius`
#trivial

Fixes typo

---

packages/palette/src/elements/Button/Button.ios.tsx
packages/palette/src/elements/Button/Button.shared.tsx

Added an optional "block" prop to the ios button component.

Add prop to make button full width

---

packages/palette/src/elements/Tabs/Tabs.tsx

- Adds `width: 100%` to `TabsPadding` for Flickity Carousel wrapper

Adds 100%  width to TabsPadding

---

packages/palette/src/elements/Tabs/Tabs.tsx

- Fixes `justify` on tabs for CMS by using `width: auto` on padding wrapper when `justifyContent` is passed as a prop.
- Once we move `TabsCarousel` to Palette we should reevaluate this use case.

Fixes justify on Tabs

---

packages/palette/src/elements/EntityHeader/EntityHeader.ios.tsx

__Problem:__
Partner card follow button goes off screen if the partner name is too long (i.e. The Metropolitan Museum of Art). 
We should make sure we are truncating both the name and the metadata on the second line. 
__Solution:__
Added ellipsizeMode and numberOfLines to name and metadata text elements
__Before:__
__After:__

[PURCHASE-1226] Partner card follow button goes off screen if the partner name is too long

---

packages/palette/src/elements/Button/Button.ios.tsx
packages/palette/src/elements/Button/Button.shared.tsx
packages/palette/src/elements/Button/Button.tsx
packages/palette/src/elements/EntityHeader/EntityHeader.tsx
packages/palette/src/elements/Typography/Typography.tsx

- Adds a prop to `Button` to pass the longest string to keep the button width fixed at the longest text width. I.e. a button with "Following" and "Follow" states will always retain the width of "Following." This allows for enlarged text sizes and is a fix for otherwise necessitating hard coded button widths.
- Replaces `purple100` for `black100` background color from iOS button transitions on request from design team.

Adds longestText prop to Button component

---

packages/palette-docs/content/docs/home/process.mdx

Updates to reflect discussion in design system meeting. [Meeting notes](https://www.notion.so/artsy/Design-Sys-Meeting-Notes-27948cc8ac2543fa91edc1f4e9d9fe37).
To reiterate here, we updated the swimlanes in the [project board](https://github.com/artsy/palette/projects/1) to reflect our process.
Board columns
1. **To do**: tickets for components being proposed by designers and engineers alike which we review during the design system meeting
2. **In Design**: new component design and spec is being worked on by the design team
3. **Design Done**: design for new component is completed and uploaded to Zeplin
4. **In Progress**: an engineer has created a PR for the component implement and linked the issue to said PR
5. **Visual QA**: new component is ready to be visually QA'd before merging the …

Update to process docs

---

packages/palette/src/elements/BarChart/BarChart.story.tsx
packages/palette/src/elements/BarChart/BarChart.tsx

- Is it by design that the highlighted bar has at least has `10px` height? It is defined [here](https://github.com/artsy/palette/blob/master/packages/palette/src/elements/BarChart/Bar.tsx#L164-L166):
- Removed [this](https://github.com/artsy/palette/compare/master...sepans:bar-chart-zero?expand=1#diff-710f36809acea9f66cf6ae101cf56b66L14) `flex: 1`. Doesn't seem to be doing anything except making charts grow from top instead of bottom when there is no `highlightLabel`

Bar chart zero state

---

packages/palette/src/elements/DataVis/ChartTooltip.tsx
packages/palette/src/elements/DonutChart/DonutChart.tsx
packages/palette/src/elements/LineChart/LineChart.tsx

Minor fixes:
* Make the gap around invisible line chart hover label area on both sides instead of just right side
* Remove padding around donut chart labels

Minor chart fixes

---

packages/palette/src/elements/Button/Button.shared.tsx
packages/palette/src/elements/Button/Button.tsx

- Design team has requested the `noOutline` button have black text
- Before 
- After

noOutline button color

---

packages/palette-docs/package.json
packages/palette/package.json
yarn.lock

Related: 
- https://github.com/artsy/reaction/pull/2625
- https://github.com/artsy/force/pull/4330
Upgrades to latest, which fixes a false-positive warning thrown by earlier version of Styled Components: 
> It looks like you've wrapped styled() around your React component (Component), but the className prop is not being passed down to a child. No styles will be rendered unless className is composed within your React component.

Upgrade styled-components@4.3.2

---

packages/palette-docs/content/docs/elements/buttons/Button.mdx
packages/palette/src/elements/Button/Button.ios.tsx
packages/palette/src/elements/Button/Button.shared.tsx
packages/palette/src/elements/Button/Button.tsx

- `Inline` now removes `height` and `padding` 
- Fixes React Spring bug where `transparent` background causes crash, replacing `transparent` with `rgba(0, 0, 0, 0)` is the fix.
Example of inline button:

Fixes Spring bug and updates Inline to remove padding and height

---

.github/ISSUE_TEMPLATE/component-spec.md

This commit updates the Component Step template to prompt for both Zeplin links: web and app. Those interested in the spec are not always on a system with the Zeplin app installed. This prompts issue creators to provide both links so that the spec can be accessed by a wider range of viewers and devices.

Update Component Spec template to include web Zeplin link

---

packages/palette-docs/content/docs/elements/dialogs/Modal.mdx
packages/palette/src/elements/Modal/Modal.tsx
packages/palette/src/utils/usePrevious.ts

- We were seeing issues where new props were not correctly being rendered. This PR updates the Modal to always pass new body content as props unless the `refreshModalContentKey ` updates.
- This PR also removes an issue where the Modal fade in animation was firing twice due to the `refreshModalContent` `useEffect` call firing on render. This removes that function and only calls the fade when `refreshModalContentKey` updates.

Updates modal to allow for updates prop changes

---

packages/palette/src/elements/EntityHeader/EntityHeader.ios.tsx

- Subtext in `EntityHeader` should be size `2`

Fixes entityheader subtext size

---

packages/palette/package.json
packages/palette/src/elements/BarChart/BarChart.story.tsx
packages/palette/src/elements/DonutChart/DonutChart.story.tsx
packages/palette/src/elements/DonutChart/DonutChart.test.tsx
packages/palette/src/elements/DonutChart/DonutChart.tsx
packages/palette/src/elements/LineChart/LineChart.story.tsx
packages/palette/src/elements/LineChart/LineChart.test.tsx
packages/palette/src/elements/LineChart/LineChartSVG.tsx
yarn.lock

It turned out that the SVG chart animations (currently donut and line charts) are sensitive to the version of `react-spring` it is using. This hopefully catches that.
- Why not chromatic? The chart may render correctly without animation and chromatic wouldn't catch that
- Why `mock-raf` dependency? It is a small dev dependency but definitely can make our own, though it will be _very_ similar.

Add tests for SVG chart animations

---

packages/palette-docs/content/docs/components/TimeRemaining.mdx
packages/palette/src/elements/TimeRemaining/TimeRemaining.tsx

- Adds custom font sizes to `TimeRemaining` API for new iOS artwork page. The default font sizes do not match the iOS spec, and after speaking with design the best solution is to pass optional custom font sizes.

Adds fontsize props to TimeRemaining

---

packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.test.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.tsx

Fixes issue where subsequent updates to `defaultValue` don't update the UI. Also adds a storybooks entry. 
#trivial

[RadioGroup] Fix defaultValue selection #trivial 

---

packages/palette/package.json
packages/palette/src/svgs/CheckCircleIcon.ios.tsx
packages/palette/src/svgs/CloseCircleIcon.ios.tsx
yarn.lock

- Creates `ios` versions of `CloseCircleIcon` and `CheckCircleIcon`

Adds ios Close and Check Circle Icons

---

packages/palette/.storybook/config.js
packages/palette/src/elements/Modal/Modal.story.tsx

This PR ports the Palette documentation examples over to Storybook for visual regression testing.

Add Modal component examples to Storybook

---

packages/palette/src/elements/Modal/Modal.tsx
packages/palette/src/elements/Modal/__tests__/Modal.test.tsx

- https://artsyproduct.atlassian.net/browse/PURCHASE-1473
- Users can now close the Modal by clicking anywhere outside of the Modal. This however is disabled if the `hideCloseXButton` prop is passed. In some cases we may want a CTA to be the only way to exit out of a modal, this prop can be used in these cases.

PURCHASE-1473 - Adds hideCloseXButton prop and allow for closing from wrapper

---

packages/palette/src/elements/Modal/Modal.tsx

Following up from discussion here https://artsy.slack.com/archives/C9XJKPY9W/p1568209247034600?thread_ts=1568197341.029300&cid=C9XJKPY9W
we're
1. Adding extra spacing to give the title and logo more room to breathe.
2. Using 30px padding everywhere.
This should be a lot closer but we're still waiting on the final specs from @samchieng

Improve modal padding

---

packages/palette-docs/content/docs/elements/data-visualization/BarChart.mdx
packages/palette-docs/content/docs/elements/data-visualization/DonutChart.mdx
packages/palette-docs/content/docs/elements/data-visualization/LineChart.mdx
packages/palette-docs/content/docs/elements/images/Image.mdx
packages/palette-docs/content/docs/elements/inputs/Checkbox.mdx
packages/palette-docs/content/docs/elements/inputs/RadioGroup.mdx
packages/palette-docs/content/docs/elements/inputs/Select.mdx
packages/palette-docs/content/docs/elements/inputs/SelectSmall.mdx
packages/palette-docs/content/docs/elements/inputs/Slider.mdx
packages/palette-docs/content/docs/elements/layout/CSSGrid.mdx
packages/palette-docs/content/docs/elements/layout/Flex.mdx
packages/palette-docs/content/docs/elements/layout/Grid.mdx
packages/palette-docs/content/docs/elements/layout/ReadMore.mdx
packages/palette-docs/content/docs/home/getting-started.mdx
packages/palette-docs/content/docs/home/process.mdx
packages/palette-docs/content/docs/tokens/Color.mdx
packages/palette-docs/content/docs/tokens/Spacing.mdx
packages/palette-docs/gatsby-config.js
packages/palette-docs/package.json
packages/palette-docs/src/components/GlobalComponents.jsx
packages/palette-docs/src/layouts/DefaultLayout.tsx
yarn.lock

This update makes a series of changes requested by an algolia rep to enable docsearch. 
It includes
- making headings consistent
- ensuring headings use the right elements
- adding a sitemap
- add custom classes that algolia can hook into
Once we have this live they can start indexing us. Afterwards, the next big step will be to add the ui.

Algolia updates

---

packages/palette-docs/content/docs/elements/inputs/Slider.mdx
packages/palette/src/elements/Slider/Slider.story.tsx
packages/palette/src/elements/Slider/Slider.tsx

Fixes drag offset on handles in prod, impacting only chrome:
Also adds new storybook entry. 
#trivial

[Slider] Fix handles

---

packages/palette/src/elements/Select/Select.tsx

@sepans and I needed to add some functionality to `<SelectSmall>` - this PR allows it to receive the normal `m`, `mr`, `p`, `pr`...etc. props that other Palette components accept, and it also allows the consumer to pass a `width` prop.
This should not affect existing functionality as nothing we added changes the default behavior.

SelectSmall updates

---

packages/palette/src/elements/Dialog/Dialog.tsx

Realizing that I have a flaw here with the dialog. Because it's a stopping point in the flow that usually used for 'confirm'/'cancel' interactions - with confirm being primary action and cancel secondary - we definitely don't want to call primary action with dialog close and in most cases we would not want to do any additional actions on close.
I should have a spec for that but not sure how to incorporate `State` for show in spec.

bug fix for Dialog

---

packages/palette-docs/content/docs/elements/inputs/Input.mdx
packages/palette-docs/content/docs/elements/inputs/Select.mdx
packages/palette/src/elements/Input/Input.test.tsx
packages/palette/src/elements/Input/Input.tsx
packages/palette/src/elements/Select/Select.story.tsx
packages/palette/src/elements/Select/Select.test.tsx
packages/palette/src/elements/Select/Select.tsx

While working on something unrelated over on Volt, I had a chance to compare the `Select` component here with what we made before Palette even existed! I found that there was some work to do, so this PR is me taking a crack at it. The result of this PR would be me able to migrate code from Volt's select to Palette's.
So with this LargeSelect learns all sorts of cool new tricks:
* it supports title, description and error messages like Input
* it correctly computes it's border color the same way as Input
* it can be marked as required
* a name attribute can be supplied to the underlying select element
* the keys for the options try a little harder to be unique on the page
I've also updated the docs to more closely match Input so that all the various states can be played around with.
Here's …

Improve selects

---

packages/palette/src/elements/Select/Select.tsx

Users of this component are going to want to use this interface, so we might as well export it.

Export the Option interface

---

packages/palette/src/elements/Checkbox/Checkbox.tsx

@sweir27 and @ds300 are working on cypress tests and needed a way to target the checkbox in a test. Cypress recommends putting something like `data-test="123"` on an element to enable targeting it for a test, but the checkbox wasn't passing down attributes to the element. 
This adds a spread to pass down unused props to the wrapper element. The same pattern is already used in the radio button.

Allow attributes to be passed to checkbox for testing

---

packages/palette/src/elements/Tags/Tags.tsx

The introduction of the `Tags` component broke emission because it was using the web version of `styled` so I switched it to use our cross-platform `styledWrapper` helper.

Make Tags cross platform

---

packages/palette/src/elements/Tags/Tags.tsx

Fixes [PURCHASE-1615](https://artsyproduct.atlassian.net/browse/PURCHASE-1615)
Mostly inspired from [Collapse component](https://github.com/artsy/palette/blob/master/packages/palette/src/elements/Collapse/Collapse.tsx) H/T @ds300
I first struggled to find a way to animate the height of a flexbox that has `flex-wrap` to wrap its element using only css but looked at the collapse component and realized that approach is perfectly applicable here but open to other simpler ideas.
Also I don't think this causes any problem with **SSR** since the height is `auto` by default and only changes when there is a user interaction but I might be missing something.
<details>
<summary>screenshot</summary>
</details>
TODO:

Adds Tags container animation

---

packages/palette/scripts/generate-styles.ts

Fixes an issue where the stylesheet generation process was causing deployments to fail because there was an unchecked type issue that `ts-node` was choking on.

Fix type issues in stylesheet generator

---

package.json
packages/palette/src/elements/Typography/Typography.tsx

A minor update to fix some type failures on the docs site. Also I noticed the `type-check` command didn't do everything it needed if the types for palette changed that the docs site relied on.

Add className type to typography components

---

packages/palette/src/elements/Modal/Modal.tsx

Not sure why we wouldn't want `overflow: auto` instead of `overflow: scroll` always, but makes that opt-in [for now].

@mzikherman => [Modal] Add option to disable forcing scrollbars for smaller content

---

packages/palette/package.json
yarn.lock

bumping react-lazy-load-image-component dependency to latest version update (from the current beta it's on)

Upgrade `react-lazy-load-image-component` off of beta

---

packages/palette/package.json
yarn.lock

See https://github.com/Aljullu/react-lazy-load-image-component/issues/50
TL;DR
react-lazy-load-image-component was sometimes double downloading images (especially on chrome) because an optimization that changed the src and retriggered the download.
I thought another changed fixed it, but it was hard to reproduce due to the need to link the library from reaction through force.

Fix lazy load double download issue by updating lib

---

.circleci/config.yml
package.json

This is a follow-up to https://github.com/artsy/palette/pull/629
cc @damassi 
This sets up CI to deploy the docs (assuming that the `auto-release` set succeeds). 
I'm assuming we need to add some env vars to this as well?

Deploy docs to s3 on master build

---

packages/palette-docs/package.json
packages/palette/package.json
packages/palette/src/elements/Banner/Banner.test.tsx
packages/palette/src/elements/BarChart/BarChart.test.tsx
packages/palette/src/elements/Pagination/__tests__/Pagination.test.tsx
yarn.lock

Reverts artsy/palette#630
This undoes the `styled-components` upgrade, which will be staged better.
Should this be a major version bump (and could be then merged in any client apps with a button click)?

@damassi => Revert "@zephraph => [Package] Update styled-components to v5"

---

packages/palette/src/elements/Spinner/Spinner.shared.tsx
packages/palette/src/elements/Spinner/Spinner.story.tsx
packages/palette/src/elements/Spinner/Spinner.tsx

There's a lot of content around Artsy.net right now that is rendered by a QueryRender, which by default uses a spinner. However, often we make a request to MP but then decide _not_ to render the content, leaving the UI jumpy as the spinner shows and hides. 
Also added a quick 400ms fade in to make the transition less jarring. 
This adds a new `delay` prop which will delay the rendering until `x` milliseconds. 
<details>
<summary>📦 Published PR as canary version: <code>7.0.1-canary.640.9679.0</code></summary>
<br />
```sh
npm install @artsy/palette@7.0.1-canary.640.9679.0
yarn add @artsy/palette@7.0.1-canary.640.9679.0
```
</details>

[Spinner] Adds delay prop for visibility

---

packages/palette/src/elements/Select/Select.tsx

the Sort: dropdown arrow is displaying oddly/in incorrect placement on Chrome (iPhone X)
https://files.slack.com/files-pri/T02531TU5-FTC9HD19P/image.png
__Before:__
__After:__
[PURCHASE-1779]: https://artsyproduct.atlassian.net/browse/PURCHASE-1779

Small dropdown arrow is misaligned

---

.circleci/config.yml

cc @eessex, @damassi 
I created a new IAM role w/ write-only permissions to palette's S3 bucket. This should fix our problem w/ master failing to upload site artifacts.  
<details>
<summary>📦 Published PR as canary version: <code>7.1.2-canary.643.9742.0</code></summary>
<br />
```sh
npm install @artsy/palette@7.1.2-canary.643.9742.0
yarn add @artsy/palette@7.1.2-canary.643.9742.0
```
</details>

Add new context w/ proper permissions to upload to S3

---

packages/palette-docs/gatsby-config.js

Adding `acl: null` to not require a special ACL permissions grant in IAM. 
I also updated the S3 permissions slightly. 
See #643 for more context.

Disable acl to bypass requiring the addition of extra permissions

---

packages/palette-docs/gatsby-config.js

This is technically a revert of #644. When the publish was successful files in the bucket were private. I manually set them to public, but I'm not certain they wouldn't default to private on the next publish. 
I've updated the permissions for this set to be able to control the ACL rules for its bucket, just to ensure the proper permissions are provided on deployments.  
At least now we know it's deploying correctly though!
cc @eessex 
<details>
<summary>📦 Published PR as canary version: <code>7.1.2-canary.645.9773.0</code></summary>
<br />
```sh
npm install @artsy/palette@7.1.2-canary.645.9773.0
yarn add @artsy/palette@7.1.2-canary.645.9773.0
```
</details>

Re-add acl permissions to avoid publishing private assets

---

packages/palette/src/elements/Spinner/Spinner.tsx

Added last week to smooth out QueryRenderer appearance in reaction but turns out it's not needed with new delay prop. 
<details>
<summary>📦 Published PR as canary version: <code>7.1.2-canary.647.9808.0</code></summary>
<br />
```sh
npm install @artsy/palette@7.1.2-canary.647.9808.0
yarn add @artsy/palette@7.1.2-canary.647.9808.0
```
</details>

[Spinner] Remove fade

---

packages/palette-docs/plugins/gatsby-plugin-local-algolia-docsearch/gatsby-ssr.js

In #633, I overrode some styles to make the search results look more on-brand. Unfortunately, they only worked locally, as the production build placed the docsearch CSS *after* the overrides. 😢 
This PR adds an `onPreRenderHTML` handler to our custom plugin, to bubble the `docsearch-css` styles to the beginning of the `head` element. Thanks to [the Gatsby docs](https://www.gatsbyjs.org/docs/ssr-apis/#onPreRenderHTML) for a clear example on how to do this!
The search results before these changes (note the algolia-blue underline):
The search results after these changes (note the artsy-purple underline):

Move docsearch CSS to beginning of head so that our custom styles override it

---

packages/palette-docs/content/docs/elements/inputs/TextArea.mdx
packages/palette/src/elements/TextArea/TextArea.story.tsx
packages/palette/src/elements/TextArea/TextArea.tsx
packages/palette/src/elements/TextArea/__tests__/TextArea.test.tsx

This PR adds a `name` prop to the TextArea input. 
If a client wasn't using TypeScript, they would have no problem passing a `name` into a `<TextArea>`. The `name` would be attached to the `textarea` element in the DOM, just as they'd expect. However, if the client was using TypeScript, they would get a compilation error. This PR doesn't change how the name gets emitted in the DOM - it just allows for TypeScript clients to pass it in.
Adding the `name` property enables for easier testing. `capybara` tests have an idiom where you fill in fields in a form with `fill_in 'field_name', with: value` - but they expect a `name` attribute on the field. Enzyme tests also become easier, as elements can be targeted via a selector like `.find('textarea[name="my-textarea"])`.
It also enables us to use …

Add name prop to TextArea

---

packages/palette/src/elements/Toggle/Toggle.story.tsx
packages/palette/src/elements/Toggle/Toggle.tsx

This adds the ability to inject secondary action on the toggle. The secondary action is a render function that will render _something_ beside the chevron icon. 
This will initially be used for [PURCHASE-1841](https://artsyproduct.atlassian.net/browse/PURCHASE-1841). 
The `clear` link here would be the secondary action. 
<details>
<summary>📦 Published PR as canary version: <code>7.4.0-canary.654.9952.0</code></summary>
<br />
```sh
npm install @artsy/palette@7.4.0-canary.654.9952.0
yarn add @artsy/palette@7.4.0-canary.654.9952.0
```
</details>

Add the ability to have a secondary action on the toggle

---

packages/palette/src/elements/CSSGrid/CSSGrid.story.tsx

Because we were using a random image from picsum.com for the CSS Grid story, every build resulted in visual diffs that we had to approve.
This PR specifies the objectively best image available on picsum instead.
A closer view:

Use a stable image for CSSGrid story.

---

packages/palette/src/elements/Button/Button.tsx

[PURCHASE-1781]
The Small button size: I know we built all btns with extra padding on right/left, but it feels unresolved/buggy or something in these smaller screen sizes. Possible to consider eliminating this extra 20px of east-west padding? 
https://files.slack.com/files-pri/T02531TU5-FTNEPUDFA/image.png
we adjusted the left/right padding for small buttons in palette for iOS with the new artwork page, so we should be able to change it on web too
__Before:__
__After:__
[PURCHASE-1781]: https://artsyproduct.atlassian.net/browse/PURCHASE-1781

Adjust left/right padding on small buttons for mWeb (to match iOS styling)

---

packages/palette/src/svgs/ArtsyLogoBlackIcon.tsx

Currently we're unable to change the size of the full, black artsy logo. Given that it really needs to keep it's ratio, I've added a scale property that we can use to scale it up down depending on context. 
<details>
<summary>📦 Published PR as canary version: <code>7.5.0-canary.658.10022.0</code></summary>
<br />
```sh
npm install @artsy/palette@7.5.0-canary.658.10022.0
yarn add @artsy/palette@7.5.0-canary.658.10022.0
```
</details>

Allow the Artsy logo to be scaled

---

packages/palette/src/elements/Flex/Flex.tsx

The version of styled-systems we're on is missing the `flexShrink` property. This adds it. 
<details>
<summary>📦 Published PR as canary version: <code>7.5.1-canary.659.10038.0</code></summary>
<br />
```sh
npm install @artsy/palette@7.5.1-canary.659.10038.0
yarn add @artsy/palette@7.5.1-canary.659.10038.0
```
</details>

Add missing `flexShrink` to Flex component

---

packages/palette-docs/content/docs/elements/images/Avatar.mdx
packages/palette/package.json
packages/palette/src/elements/Avatar/Avatar.test.tsx
packages/palette/src/elements/Avatar/Avatar.tsx
packages/palette/src/elements/Flex/Flex.tsx
packages/palette/src/elements/Image/LazyImage.tsx
yarn.lock

This adds the ability to specify a fallback when the image doesn't load for an avatar. I updated the palette docs with a realistic example of how we might use it. 
Note that this should still be ported to iOS. 
This adds two props to avatar:
1. `renderFallback` -- Basically a render method to render a component if the image fails to load
2. `onError` -- The is the same callback that's present on images and is what powers the fallback logic. You can also hook into this to do arbitrary things (like remove the `src` from the props so that it falls back to initials if you have those defined).  
A tiny related article: https://medium.com/@Mdmoin07/image-fallback-for-broken-images-react-react-native-261f35b02f45
<details>
<summary>📦 Published PR as canary version: …

Add fallback image support to avatar

---

packages/palette/src/elements/Flex/Flex.tsx

Small change to allow adding top prop to flex. 
<details>
<summary>📦 Published PR as canary version: <code>7.7.0-canary.662.10098.0</code></summary>
<br />
```sh
npm install @artsy/palette@7.7.0-canary.662.10098.0
yarn add @artsy/palette@7.7.0-canary.662.10098.0
```
</details>

Add top to flex

---

packages/palette/src/elements/Input/Input.tsx

This updates the `Input` component to use `React.forwardRef` so that we can actually get the ref of the input component. 
This would be useful for scenarios where we want to clear the input without having to create a wrapping component. 
<details>
<summary>📦 Published PR as canary version: <code>7.8.0-canary.663.10121.0</code></summary>
<br />
```sh
npm install @artsy/palette@7.8.0-canary.663.10121.0
yarn add @artsy/palette@7.8.0-canary.663.10121.0
```
</details>

Allow `Input` to accept refs

---

packages/palette/src/elements/Menu/Menu.tsx

Addresses: [FX-1889](https://artsyproduct.atlassian.net/browse/FX-1889)
This expands the Menu and MenuItem components to support the new DropDownMenu component in reaction. It adds a few new props in order to adjust the menu styling.
<details>
<summary>📦 Published PR as canary version: <code>7.8.1-canary.664.10164.0</code></summary>
<br />
```sh
npm install @artsy/palette@7.8.1-canary.664.10164.0
yarn add @artsy/palette@7.8.1-canary.664.10164.0
```
</details>

[FX-1889] expand menu component to work with new nav DropDownMenu in reaction

---

packages/palette/src/elements/TextArea/TextArea.story.tsx
packages/palette/src/elements/TextArea/TextArea.tsx

Changes text area title/description to use `Sans`. Updates the spacing to ensure there's not 10px of spacing between the `title` and the `description`. 
<details>
<summary>📦 Published PR as canary version: <code>8.1.1-canary.668.10308.0</code></summary>
<br />
```sh
npm install @artsy/palette@8.1.1-canary.668.10308.0
yarn add @artsy/palette@8.1.1-canary.668.10308.0
```
</details>

Removed spacing, changed font for text area

---

packages/palette/src/elements/Input/Input.story.tsx
packages/palette/src/elements/Input/Input.test.tsx
packages/palette/src/elements/Input/Input.tsx

Changed font family on text inputs from Serif to Sans. Created a storybook file for inputs.
<details>
<summary>📦 Published PR as canary version: <code>8.1.2-canary.670.10350.0</code></summary>
<br />
```sh
npm install @artsy/palette@8.1.2-canary.670.10350.0
yarn add @artsy/palette@8.1.2-canary.670.10350.0
```
</details>

Style tweaks for text inputs

---

packages/palette/src/elements/Menu/Menu.tsx

This addresses some minor style issues with the drop down menu:
- Ensure menu extends to the fullwidth of the screen.
- Remove top and bottom padding for fullwidth drop down menu.
**Before:**
**After:**
<details>
<summary>📦 Published PR as canary version: <code>8.1.3-canary.671.10374.0</code></summary>
<br />
```sh
npm install @artsy/palette@8.1.3-canary.671.10374.0
yarn add @artsy/palette@8.1.3-canary.671.10374.0
```
</details>

Update menu component style props

---

packages/palette/src/elements/Menu/Menu.tsx

Addresses: [FX-1907](https://artsyproduct.atlassian.net/browse/FX-1907)
Adjusts the back-ground color to be more legible when we use lighter colors.
<details>
<summary>📦 Published PR as canary version: <code>8.2.1-canary.673.10444.0</code></summary>
<br />
```sh
npm install @artsy/palette@8.2.1-canary.673.10444.0
yarn add @artsy/palette@8.2.1-canary.673.10444.0
```
</details>

[FX-1907] make background color darker for legibility with light text colors

---

README.md
packages/palette/package.json

React Native doesn't support symlinks, so a typical `yarn link` approach won't work. For this reason, we have scripts in Palette to target the React Native codebase's `node_modules` folder. However, we [recently combined Emission into Eigen](https://github.com/artsy/eigen/pull/3022) so we need to update Palette to match the new expected directory name. I updated the script names and docs, too.
I haven't tried this locally but it should work 🙈 
<details>
<summary>📦 Published PR as canary version: <code>8.2.2-canary.678.10538.0</code></summary>
<br />
```sh
npm install @artsy/palette@8.2.2-canary.678.10538.0
yarn add @artsy/palette@8.2.2-canary.678.10538.0
```
</details>

Updates Palette to use new Eigen repo structure

---

packages/palette/src/elements/Flex/Flex.tsx

I was mistaken about `flexBasis` which is here and works fine.
Missing were `alignSelf`, `flex`, `justifyItems`, `justifySelf` — if you're interested in these, which brings this inline with styled-system's current flexbox: https://github.com/styled-system/styled-system/blob/master/packages/flexbox/src/index.js

Mixes in missing flex-related functions

---

packages/palette/src/elements/Modal/Modal.tsx

Slack thread: https://artsy.slack.com/archives/C9XJKPY9W/p1576267394001200
This will be a breaking change and will required some compatibility updates in @artsy/reaction.

Remove Modal `forcedScroll` prop / Default `overflow` to `auto`

---

packages/palette/src/elements/Modal/Modal.tsx

Don't call `onClose` callback if we're within the initial render.

[Modal] Do not fire external `onClose` callback on first render

---

packages/palette-docs/content/docs/tokens/Typography.mdx
packages/palette/src/elements/Typography/Typography.test.tsx
packages/palette/src/elements/Typography/Typography.tsx

Not 100% sure that I understand the ask correctly. But that does add `unstable_trackIn` to Sans and Serif and puts a sample in the doc file. It's collapsed by default.
Looks like that:

[COM-16] - add unstable_trackIn as a prop to Sans and Serif

---

packages/palette-docs/content/docs/elements/dialogs/Banner.mdx
packages/palette/src/elements/Banner/Banner.tsx

This PR has a few changes:
* Make `props.message` for the `<Banner>` component optional. It can take `props.children` so we may not always have to specify `props.message`, so I think it makes sense to make it optional.
* Fix the close button position when the context of a `<Banner>` expands the height of the component (see the before/after below).
* Add a new Dismissable Banner section to the doc to clarify the necessity of this update.

Update the Banner component to work well with a content that takes more space

---

packages/palette/src/elements/Typography/Typography.tsx

@oxaudo this change you made failed in eigen (artsy/eigen#3318) because the `style` prop is allowed to be an array in react-native but this code assumed that it was always an object. In this PR I just turned the `unstable_trackIn` feature off in react-native, since I guess it's a web-only thing?

No unstable_trackIn in eigen

---

packages/palette/src/elements/BorderBox/index.tsx

`BorderBoxProps` is exported within `BorderBoxBase` which wasn't included in the `index.tsx` exports.
Addresses [this comment](https://github.com/artsy/reaction/pull/3398#discussion_r408897421) in a previous PR and allows us to update the artsy/reaction imports which reach all the way through `dist/elements/BorderBox/BorderBoxBase`.

Export BorderBoxProps in top-level package

---

packages/palette-docs/content/docs/elements/inputs/RadioGroup.mdx
packages/palette/.storybook/addons.js
packages/palette/package.json
packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.test.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.tsx
yarn.lock

For context, this is something we need for the PR https://github.com/artsy/reaction/pull/3558 which converts the price from a range to a radio.
This is what range looks like:
This is what radio looks like now:
This PR also adds https://github.com/storybookjs/storybook/tree/master/addons/knobs to make our DX just a tiny bit nicer. With knobs we can edit props directly in the storybook like:

Add disabledtext to radiogroup

---

packages/palette/src/elements/EntityHeader/EntityHeader.ios.tsx
packages/palette/src/elements/EntityHeader/EntityHeader.tsx

Before (iOS):
After (iOS):
Before (web):
After (web):
https://artsyproduct.atlassian.net/browse/FX-1901

Use Sans Instead of Serif in EntityHeader component

---

packages/palette/src/elements/Button/Button.story.tsx
packages/palette/src/elements/Button/Button.test.tsx
packages/palette/src/elements/Button/Button.tsx

Closes https://github.com/artsy/palette/issues/696
Weird that this uses class names instead of just props for handling these states?

Fixes mixed-in classnames coming from styled-components

---

packages/palette/jest.config.ts
packages/palette/package.json
packages/palette/src/elements/BarChart/BarChart.story.tsx
packages/palette/src/elements/Modal/ModalBase.story.tsx
packages/palette/src/elements/Modal/ModalBase.tsx
packages/palette/src/elements/Modal/__tests__/ModalBase.test.tsx
packages/palette/src/elements/Modal/index.tsx
yarn.lock

So here I'm re-implementing the lower-level modal but without forcing it onto the existing one. The intent is to use this for the mobile action sheets in Force (!), and implement any newer modally behavior on top of this. I intend to migrate the existing modal to use this as well, but I'm going to punt on that migration for the time being.
Took a slightly lighter touch here as well with only using a library for the scroll-locking, and implemented the focus management stuff myself.
Keyboard navigation demo (we really need focus rings on Buttons!):
---
I'm gonna yalc this over to Force before converting to a real PR.
<details>
<summary>📦 Published PR as canary version: <code>9.8.2-canary.693.11035.0</code></summary>
<br />
```sh
npm install …
```

[FX-1936] Implements ModalBase (take II)

---

packages/palette/src/elements/Avatar/Avatar.shared.tsx

While working on the Collect Resume header, @jpotts244 and I noticed that the avatar component uses Sans instead Serif (which the component has currently). This PR updates the Avatar component to Sans which we want globally.
More context in this [slack thread](https://artsy.slack.com/archives/C9YNS4X32/p1591042672438200?thread_ts=1591042646.437900&cid=C9YNS4X32).
**Before:**
**After:**

Update avatar component to use Sans

---

packages/palette-docs/content/docs/elements/layout/BorderBox.mdx
packages/palette/src/elements/BorderBox/BorderBoxBase.tsx

This might be controversial since allows to expand the variation on boxes, but we do already have a way to do it by extending with Styled components and we do allow to customize spacing. So seems logical to allow to customize `borderColor` as well.
This is for the https://github.com/artsy/volt/pull/4357

allow customizing border color for BorderBox

---

packages/palette-docs/content/docs/elements/layout/BorderBox.mdx
packages/palette/src/elements/BorderBox/BorderBoxBase.tsx

I think somewhere through refactor the space prop for BorderBox was lost. And seems logical to me that it should be supported for BorderBox.
In fact arguably we should support all the properties there that Box supports + border props. But I only needed spacing for now. So adding it here to fix this view:

BorderBox should support custom padding

---

packages/palette/src/elements/Toggle/Toggle.tsx

White spacing on artwork filters is too large (https://artsyproduct.atlassian.net/browse/FX-1993).
Remove hardcoded top margin from `Toggle` component. This impacts artwork filters on desktop and mobile web, including filters on the auction results page. (The Auctions FAQ page also uses `Toggle` but these pages will soon be retired in favor of Zendesk pages.) After this change, artwork filters will have consistent whitespacing across desktop and mobile web. Eigen does not use Palette's `Toggle` component.
**Note**: The screenshots here for the artwork filters reflect an additional (to be added) Force PR that also tweaked some margins on the filters themselves.
---
<details>
<summary>📦 Published PR as canary version: <code>11.0.3-canary.712.11453.0</code></summary>
<br />
:sparkles: Test …

Remove margin on Toggle component

---

packages/palette/.storybook/addons.js
packages/palette/package.json
packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx
yarn.lock

@ds300 noticed that after the Storybook upgrade, [typings from `@emotion/core` were being required in the built type declarations](https://app.renovatebot.com/package-diff?name=@artsy%2fpalette&from=11.0.2&to=11.1.0)
Apparently this is [due to addon-knobs](https://github.com/storybookjs/storybook/issues/8321). See also: https://github.com/emotion-js/emotion/issues/1800
addon-knobs it turns out is dead and being replaced with [addon-controls](https://github.com/storybookjs/storybook/tree/next/addons/controls#how-will-this-replace-addon-knobs) which OK, fine.
For now I'm just removing knobs because we only use it in a single place so it's value here isn't huge. I'd like to upgrade to Storybook 6 beta, and I started to go down that road but we run into some issues with our babelrc that I …

Disables knobs to remove dependency on emotion typings

---

packages/palette-docs/content/docs/components/EntityHeader.mdx
packages/palette/src/elements/EntityHeader/EntityHeader.ios.tsx
packages/palette/src/elements/EntityHeader/EntityHeader.tsx

https://artsyproduct.atlassian.net/browse/FX-2070
The Entity Header Palette component should support receiving a `smallVariant` prop that changes the layout and design of the component. When this prop is passed the component only renders the Entity name and Followed/Unfollowed State.
With the `smallVariant` prop on iOS:
Without the `smallVariant` prop on iOS:
With the `smallVariant` prop on web:
Without the `smallVariant` prop on web:
In the Palette Playground:

Supports a small entity header design via "smallVariant" prop

---

packages/palette/src/helpers/injectGlobalStyles.tsx

This is a pretty presumptuous rule to have in here and we shouldn't be doing this anyway.
I ran into this because in trying to clean up how we integrate `:focus-visible` — this is sometimes winning in specificity depending on where I insert the CSS.

Removes blanket focus disable

---

packages/palette/package.json
packages/palette/src/elements/Grid/Grid.tsx
yarn.lock

So I'd like to use a vanilla `position: sticky` on an element that happens to be contained within a grid container and you can't actually stick anything if the parent container is `overflow: hidden`.
I can see that this property was introduced here: https://github.com/artsy/reaction/pull/1031 with the foreshadowing "It'll never be scrollable because of that (for better or worse)" 😈  but I'm not entirely sure why this was necessary?
Setting the `overflow` to `auto` on the artist page seems fine? If we *do* need it to be hidden then we can either wrap or mix in a system function for it.
@zephraph I know this was a while ago so I know the memory of this change is hazy but let me know if I'm missing something obvious here.
----
Also I upgraded styled-bootstrap-grid — that said, I have zero …

Upgrades styled-bootstrap-grid; removes overflow: hidden

---

packages/palette-docs/content/docs/elements/layout/Cards.mdx
packages/palette/src/elements/Cards/MediumCard.tsx

Adds a medium size card to palette. See spec for medium card here: https://www.figma.com/file/GrCeNUJbKpfZtgwHga64cC/Artsy-Viewing-Room-Entry-Points-Components?node-id=78%3A1368

GALL-2970 Add web version of medium card

---

packages/palette-docs/content/docs/tokens/Typography.mdx
packages/palette/src/elements/Text/Text.story.tsx
packages/palette/src/elements/Text/Text.tsx
packages/palette/src/elements/Text/tokens.ts

Also adds the `overflowEllipsis` option, and updates the typography docs. I would have added a bit more to those but [I can't get the docs to actually compile correctly](https://github.com/artsy/palette/issues/733).

Removes serif from Text

---

packages/palette/src/elements/Box/Box.tsx
packages/palette/src/elements/Box/__tests__/Box.test.tsx

OK, so I'd like to break apart https://github.com/artsy/palette/pull/730 into some more manageable pieces.
This gives us a typesafe utility that we can use when you have compound components where you've got an outer Box container that is being used to manage layout but would like to spread native rest props on the inner component (think img, input, etc).

Implements utility for breaking apart layout props

---

packages/palette/src/Theme.tsx
packages/palette/src/elements/Grid/Grid.story.tsx
packages/palette/src/elements/Grid/Grid.tsx

@williardx has an interesting use case where he wants to override the Grid's `maxWidth` and set it to 100% when at or below the small breakpoint.
Initially I had thought you should be able to use the responsive props for this but it turns out that's not useful because in terms of the directionality of the media query, to do this you'd want a max-width, and responsive props create styles using min-width.
Nonetheless, I thought I'd PR support for object style syntax here. Which at least makes this a lot more clear and less mysterious.

Breakpoints aliasing

---

packages/palette-docs/content/docs/tokens/Typography.mdx

This restructures the typography docs a bit, and cleans up the layout (removes unnecessary playground toggles, titles, etc.)

Update Typography docs

---

packages/palette/src/elements/Input/Input.tsx

Thing that was bothering me when I was debugging just now:
Before:
After:

Removes shadow on iOS

---

packages/palette/src/elements/HTML/HTML.story.tsx
packages/palette/src/elements/HTML/HTML.tsx
packages/palette/src/elements/Text/Text.story.tsx
packages/palette/src/elements/Text/tokens.ts

So:
> Garamond will continue to be used in Editorial, and in all B2B web pages and outreach.
So I've reverted its removal here.
Also updating the HTML component to extend Text instead of Sans/Serif. This will constitute a breaking change, though the only call sites currently are on the Feature pages. I'll handle the integration of this as soon as it's released.
One other nice thing about this is now we get proper bold and italic fonts within rendered HTML 🥳

Reverts serif removal, migrates HTML to new typography

---

packages/palette/src/elements/HTML/HTML.story.tsx
packages/palette/src/elements/HTML/HTML.tsx

Minor thing, normalizing the remaining block-level elements that might come out of Markdown.
Not trying to be super comprehensive with how these are styled (for instance we're targeting `blockquote` specifically on Features) — but rather just give everything a normalized reasonable default.

Adds remaining block-level elements that can come from rendered Markdown

---

packages/palette-docs/content/docs/components/EntityHeader.mdx
packages/palette/src/elements/Avatar/Avatar.shared.tsx
packages/palette/src/elements/EntityHeader/EntityHeader.tsx

The `smallVariant` needs some updates, per https://artsyproduct.atlassian.net/browse/FX-2149.
This PR updates the avatar size to be 30px and uses the new type variants.

Updates avatar size and typography for entity header small variant

---

packages/palette/src/elements/LabeledRange/LabeledRange.tsx
packages/palette/src/elements/Pagination/Pagination.tsx
packages/palette/src/elements/PriceRange/PriceRange.tsx
packages/palette/src/elements/StaticCountdownTimer/StaticCountdownTimer.tsx
packages/palette/src/elements/Stepper/Stepper.tsx
packages/palette/src/elements/TimeRemaining/TimeRemaining.tsx
packages/palette/src/elements/Toggle/Toggle.tsx

There are several dependency cycles in Palette that under certain
circumstances such as loading a component using its canonical path
which will create partially loaded modules that lead to undefined objects at
runtime.
The solution is to import the files directly rather than relying on the global
index.

Chore - Cleanup Dependency Cycles

---

packages/palette/src/elements/Image/Image.shared.tsx
packages/palette/src/elements/Image/Image.story.tsx
packages/palette/src/elements/Image/LazyImage.tsx

So I had initially intended to refactor this entire component but that got away with me. My intention with simply adding the prop here is that currently because we swap `src` props for `FillwidthItem` on page load, we actually double load images on all 1x devices 😈

Adds support for `srcSet`

---

packages/palette/src/elements/Carousel/Carousel.tsx
packages/palette/src/elements/Carousel/__tests__/Carousel.test.tsx
packages/palette/src/elements/Carousel/__tests__/paginate.test.ts
packages/palette/src/elements/Carousel/index.ts
packages/palette/src/elements/Carousel/paginate.ts

Moves the renaming of the paginateCarousel function into the file where
it is create rather then renaming it in the `index.ts`.

Move paginateCarousel Rename to Original File

---

packages/palette/src/elements/Carousel/Carousel.story.tsx
packages/palette/src/elements/Carousel/Carousel.tsx
packages/palette/src/elements/Carousel/CarouselNavigation.tsx
packages/palette/src/elements/Carousel/__tests__/Carousel.test.tsx
packages/palette/src/elements/Swiper/Swiper.story.tsx
packages/palette/src/elements/Swiper/Swiper.tsx
packages/palette/src/elements/Swiper/__tests__/Swiper.test.tsx

[Hide diff whitespace changes](https://github.com/artsy/palette/pull/767/files?diff=unified&w=1)
Ultimately the goal here was to add support for 100% width cells & disabling carousel animated transitions without resorting to adding a number of additional and inconsistent props. These are essentially stylistic changes and so rather than exposing options which toggle them, allowing fully customizable sub-components both discourages out-of-design-system inconsistencies but makes complex behaviors that are well thought out possible none-the-less.
<details>
<summary>📦 Published PR as canary version: <code>13.0.1-canary.767.12960.0</code></summary>
<br />
```sh
npm install @artsy/palette@13.0.1-canary.767.12960.0
yarn add …
```

[Carousel/Swiper] Allows structural components to be injected

---

packages/palette/src/Theme.tsx
packages/palette/src/elements/Button/Button.tsx
packages/palette/src/elements/Cards/MediumCard.tsx

Catch up with the discussion here: https://artsy.slack.com/archives/C9XJKPY9W/p1600109997018200. 
TL;DR some new designs were starting to use 15px more which aren't represented by our spacing system. Generally we _don't_ want to have 1 offs, especially for margins and paddings. Design has been using 15px more for the app and xs experiences, so we've decided to add it to account for that. 50px has similarly been used multiple times and was suggested to be added by @nicoleyeo.

Add 1.5 and 5 to our spacing units

---

packages/palette/src/elements/Swiper/Swiper.story.tsx
packages/palette/src/elements/Swiper/Swiper.tsx

Some `Swiper` updates included `margin: 0` in the container which was overriding any passed in `mx` — here we set a default and set up a story to use as a visual spec.

Fixes horizontal margin overrides

---

packages/palette/src/elements/Text/Text.tsx

This sets the default `Text` variant as `text`, which is the obvious thing to do here. Thanks for raising @anandaroop.

Sets default Text variant to `"text"`

---

packages/palette/src/elements/Clickable/Clickable.tsx
packages/palette/src/elements/HTML/HTML.story.tsx
packages/palette/src/elements/HTML/HTML.tsx
packages/palette/src/elements/ReadMore/ReadMore.story.tsx
packages/palette/src/elements/ReadMore/ReadMore.tsx
packages/palette/src/elements/ReadMore/__tests__/ReadMore.test.tsx

Re: [FX-2245](https://artsyproduct.atlassian.net/browse/FX-2245)
* Some minor updates to `Clickable` to make it easier to use
* Updates `HTML` to export it's default styling
* Utilizes `HTML` styling on `ReadMore`
<details>
<summary>📦 Published PR as canary version: <code>13.6.1-canary.782.13312.0</code></summary>
<br />
```sh
npm install @artsy/palette@13.6.1-canary.782.13312.0
yarn add @artsy/palette@13.6.1-canary.782.13312.0
```
</details>

[FX-2245] ReadMore styling

---

packages/palette/src/svgs/XCircleIcon.tsx

Necessary for Order History page
__Before:__
__After:__

Removed white background from XCircleIcon

---

packages/palette-docs/content/docs/components/EntityHeader.mdx
packages/palette/src/elements/EntityHeader/EntityHeader.story.tsx
packages/palette/src/elements/EntityHeader/EntityHeader.tsx

Re: [FX-2251](https://artsyproduct.atlassian.net/browse/FX-2251)
The use of caption was causing some line-height differences as well due to the way this component nests a (faux-)button (necessitating the use of stopPropagation).
-----
Added stories for use as visual specs and simplified the examples a bit.

Ensures consistent typography in EntityHeaders

---

packages/palette/src/elements/EntityHeader/EntityHeader.story.tsx
packages/palette/src/elements/Swiper/Swiper.tsx

`onChange` in `Swiper` was being called on scroll. This PR keeps track with an internal state and only calls `onChange` when the active index actually changes.

Only calls onChange when the active index actually changes

---

packages/palette/src/elements/ReadMore/ReadMore.tsx
packages/palette/src/elements/ReadMore/__tests__/ReadMore.test.tsx

Shouldn't see any difference in the visual specs. Will publish a canary to confirm this fixes the stale render issue.
<details>
<summary>📦 Published PR as canary version: <code>13.7.4-canary.790.13409.0</code></summary>
<br />
```sh
npm install @artsy/palette@13.7.4-canary.790.13409.0
yarn add @artsy/palette@13.7.4-canary.790.13409.0
```
</details>

Converts ReadMore class component to functional component

---

packages/palette/src/elements/Pagination/Pagination.story.tsx
packages/palette/src/elements/Pagination/Pagination.tsx

The bug here surfaced when we added `5` to the spacing scale: `top` accepts themed values and since `space(0.5)` yields `5` this no longer falls back to `5px` but rather maps to the themed value of `50`.
I've added some stories to serve as visual specs since we'll have to edit this component a bit in the future.

[FX-2317] Fixes pagination arrow alignment

---

packages/palette/src/elements/Tabs/Tabs.tsx

This change is prompted by the new fair page redesign and we decided to change this globally to wherever the tab component is used elsewhere.
Jira: https://artsyproduct.atlassian.net/browse/FX-2320

style(FX-2320): Remove XS horizontal padding within tabs container

---

packages/palette/src/elements/GridColumns/GridColumns.tsx

Trying to get rid of this `css` prop error.
<details>
<summary>📦 Published PR as canary version: <code>13.9.1-canary.795.13515.0</code></summary>
<br />
```sh
npm install @artsy/palette@13.9.1-canary.795.13515.0
yarn add @artsy/palette@13.9.1-canary.795.13515.0
```
</details>

GridColumns typing

---

packages/palette/package.json
packages/palette/src/elements/Carousel/Carousel.story.tsx
packages/palette/src/elements/Carousel/Carousel.tsx
packages/palette/src/elements/Swiper/Swiper.story.tsx
packages/palette/src/elements/Swiper/Swiper.tsx
packages/palette/src/elements/Swiper/__tests__/activeIndex.test.ts
packages/palette/src/elements/Swiper/activeIndex.ts
packages/palette/src/elements/Swiper/percentage.ts
yarn.lock

Closes: [PCI-3](https://artsyproduct.atlassian.net/browse/PCI-3)
Will follow up with a spec here, just drafting for now.
The use-case here is being able to reset the artwork image browser to the beginning/default image if you click "View in Room".
This is a bit more straight-forward in `<Carousel />` vs `<Swiper />` since you're updating the index as you scroll already.
I think this API makes sense (re: ***initial***Index) as it works as you'd expect by default and then if you want to gain full control over the state via props, you need to lift it up a level by passing a setter into `onChange`.
-----
-----

[PCI-3] Supports props based navigation in Swiper/Carousel

---

packages/palette/src/elements/Input/Input.test.tsx
packages/palette/src/elements/Input/Input.tsx

In Volt, we sometimes use an `<Input>` element from Palette without wanting to use the built-in text error rendering (we instead display custom formatted error message to match older components). This means we sometimes just pass a boolean error value to `<Input>`, which then renders the nice red border error state - but it also renders an empty `<Sans>` component.
I know this non-standard error handling is sorta an anti-pattern, _but_ I feel that it's helpful to support boolean errors since we can already do this in practice and it causes an unexpected render. 
Here's a gif that shows the issue with rendering an empty component (stretches out other adjacent components): https://share.getcloudapp.com/8LurzAWq
This PR adds official support for a boolean error being passed to the `<Input>`, …

feat: support boolean errors for Input

---

packages/palette/src/elements/Menu/Menu.tsx

Related to https://github.com/artsy/force/pull/6639, adds `target` to `MenuItem` links, to open `href` in a new tab (in this use-case, Google Calendar).
<details>
<summary>📦 Published PR as canary version: <code>13.17.1-canary.812.13759.0</code></summary>
<br />
```sh
npm install @artsy/palette@13.17.1-canary.812.13759.0
yarn add @artsy/palette@13.17.1-canary.812.13759.0
```
</details>

trivial: add target to MenuItem

---

packages/palette/src/elements/Text/tokens.ts

For most stuff we can fall back to the automatic responsive sizes, but in some instances its nice to be able to use responsive array syntax when the differences are greater. (Versus `<Media>` component)

fix: [Text] update variant type to support array syntax

---

packages/palette/src/elements/Text/Text.tsx

Ugh, one more. Delirious night coding. 
Swaps `Thing | Thing[]` for `ResponsiveValue<Thing>`

fix: Use ResponsiveValue helper

---

lerna.json
package.json
packages/palette-tokens/README.md
packages/palette-tokens/package.json
packages/palette-tokens/src/index.ts
packages/palette-tokens/src/text.ts
packages/palette-tokens/tsconfig.json

It was decided in https://github.com/artsy/README/issues/318 to pull all react native specific components out of palette and into eigen. There was a note in the RFC that sharing tokens would be good, but that ended up not getting implemented. There was recent confusion about some specific spacing sizes missing in eigen that had been recently added to palette. That re-raised the need to share tokens. 
Check out the [slack thread](https://artsy.slack.com/archives/C02BAQ5K7/p1605638079020600) for more details. 
Essentially, this pulls out our design tokens and theme config into a separate package. It'll be followed up w/ a PR to migrate palette to begin consuming this. The last step will be to upgrade eigen to also consume it. 
I've switched lerna over to indpendent versioning mode so that …

Extract palette tokens into a separate package

---

packages/palette-docs/content/docs/elements/dialogs/Message.mdx
packages/palette/src/elements/Message/Message.tsx

This PR adds new variants to the `<Message />` component to be used in Volt and elsewhere.
Figma spec: https://www.figma.com/file/LKKhtse11fjmdFI6AaVqGM/Palette?node-id=1844%3A3294
Jira ticket: https://artsyproduct.atlassian.net/browse/PX-3501

feat: update message component

---

packages/palette-docs/content/docs/home/getting-started.mdx
packages/palette-docs/src/layouts/DefaultLayout.tsx
packages/palette/.storybook/preview-head.html

Re: [FX-2540](https://artsyproduct.atlassian.net/browse/FX-2540)
These were changed to `production-webfonts` during the transition. The bare `webfonts` subdomain now points to the same Cloudfront distro as `production-webfonts` and so this can be restored.

chore(webfonts): update webfonts domain references

---

packages/palette/src/elements/BaseTabs/BaseTab.story.tsx
packages/palette/src/elements/BaseTabs/BaseTab.tsx
packages/palette/src/elements/BaseTabs/BaseTabs.tsx
packages/palette/src/elements/BaseTabs/index.ts
packages/palette/src/elements/Stepper/Stepper.story.tsx
packages/palette/src/elements/Tabs/Tabs.story.tsx
packages/palette/src/elements/Tabs/Tabs.tsx
packages/palette/src/elements/index.tsx

This PR implements a new `BaseTabs` component which adheres to the most recent Figma specs — it's essentially just a display component for a tab list and set of tabs (not the tab panels). Which allows us to `as={RouterLink}` them as needed for the `RouterTabs` in Force, which are more common lately. To that end it also overflows and gives a little fade-out affordance for use in the search page so that we can get rid of the `TabCarousel` and that instance of Flickity.
I'd like to utilize these `BaseTabs` to build out the client-side `Tabs` for consistency and a11y. Which should be straightforward enough. But before I do that I'd like to simplify the API a bit to drop functionality we're not using.
* `autoScroll` appears to be broken? I can try to glean the intention here and support this …

feat: implements base tabs

---

packages/palette/src/elements/Tabs/Tabs.tsx

I had meant to switch these to generics but will do that when I actually cut the breaking release. Moving these back to anys for now.

fix(tabs): converts back to anys

---

packages/palette/src/elements/BaseTabs/BaseTab.story.tsx
packages/palette/src/elements/BaseTabs/BaseTabs.tsx
packages/palette/src/helpers/__tests__/flattenChildren.test.tsx
packages/palette/src/helpers/flattenChildren.ts

Previously if we were using a fragment within the tabs we'd get:
This PR introduces a simple helper to flatten out the fragments:

fix(basetabs): support nested fragments

---

packages/palette/src/elements/Swiper/Swiper.story.tsx
packages/palette/src/elements/Swiper/Swiper.tsx

This change allows us to, for instance, use an `mt` value which will override the `my` default.
Re: https://github.com/styled-system/styled-system/issues/599

fix(swiper): inlines default margins to simplify setting alternatives

---

packages/palette/src/elements/Skeleton/Skeleton.story.tsx
packages/palette/src/elements/Skeleton/Skeleton.tsx

Previously, multi-line texts would have the underlaid text peek out, because the overlay was scaled using a percentage.
Now it just tucks in the overlay a small amount, scaled to the current font size. The text is also transparent incase an edge peeks out around an aggressive border radius.

fix(skeleton): implements appropriate scaling for multiline texts

---

packages/palette/src/elements/Pagination/LargePagination.tsx

cc @jonallured 
I was trying to do some dependency updates and I noticed the UI tests were failing due to `getHref` being called when it wasn't defined. Looking over at the story it's not being passed in and was erroring out here. 
I used the same guard pattern here that existed in other places in this file. That said, something feels a little off. Should this `getHref` prop be required? If not, adding a default value to the deconstructed prop below would allow us to avoid propagating all those checks. 
https://github.com/artsy/palette/blob/64cd9a89860b3f983ab5dd04fd8190087dabd1e6/packages/palette/src/elements/Pagination/LargePagination.tsx#L44-L50
.e.g.
```diff
const {
+   getHref = () => "",
hasNextPage,
onClick,
onNext,
pageCursors: { around, first, last, previous },
} = props
``` …

Fix failing storybook tests by guarding getHref call

---

packages/palette/src/elements/Pagination/LargePagination.tsx
packages/palette/src/elements/Pagination/SmallPagination.tsx
packages/palette/src/elements/Pagination/__tests__/LargePagination.test.tsx
packages/palette/src/elements/Pagination/__tests__/SmallPagination.test.tsx

After doing some QA on staging I noticed a bug I made when I wrote an untested bit of logic about determining the next page number. I got it right when the previous page existed but on the first page, this bit of logic would return `1` and cause the Next button's HREF to be incorrect. SIGH.
How many times must I re-learn that I need tests!!
So, this PR introduces a set of tests that verify both the Next and Prev button HREF values. It ensures that the first and last pages have the correct empty hrefs and that each step along the way has the right page param being set.
https://artsyproduct.atlassian.net/browse/GRO-146
/cc @artsy/grow-devs

fix: Populate pagination next/prev hrefs correctly

---

packages/palette/src/elements/Pagination/LargePagination.tsx
packages/palette/src/elements/Pagination/Pagination.story.tsx
packages/palette/src/elements/Pagination/SmallPagination.tsx
packages/palette/src/elements/Pagination/__tests__/LargePagination.test.tsx
packages/palette/src/elements/Pagination/__tests__/SmallPagination.test.tsx

I'm having a lot of trouble actually using this component — this is the minimal change that allows me to use it. The main problem is how it encodes knowledge of cursors, but fixing that would result in a lot of breaking changes that would have to be dealt with in force. Thus: just appending the page number into the onNext callback args.
Publishing a canary incase there are any type issues; though there shouldn't be.
<details>
<br />
```sh
npm install @artsy/palette@13.27.3-canary.840.14569.0
yarn add @artsy/palette@13.27.3-canary.840.14569.0
```
</details>

feat(pagination): includes page number on next callback

---

packages/palette-docs/content/docs/elements/layout/Toggle.mdx
packages/palette/src/elements/Toggle/Toggle.tsx
packages/palette/src/elements/Toggle/__tests__/Toggle.test.tsx

Added optional `chevronSize` prop (`number`) to `Toggle` component that defaults to `12`.  
I had also considered a less flexible prop in the form a string that allows for "big" or "small" to limit the options for size, but I think providing the flexibility is probably better?

feat: Add chevronSize prop to Toggle component

---

packages/palette-tokens/src/index.ts

Makes things easier. We use this to pass colors in the objC part of the app too, and we could convert them to 6 digits but feels nicer to have them 6 digits directly.

Use full 6 digits for hex colors

---

packages/palette-docs/content/docs/elements/layout/Toggle.mdx
packages/palette-docs/package.json
packages/palette/package.json
packages/palette/src/elements/Toggle/Toggle.story.tsx
packages/palette/src/elements/Toggle/Toggle.tsx
packages/palette/src/elements/Toggle/__tests__/Toggle.test.tsx

Added option to pass a component instead of a string to the Toggle component.
What is the best way to test this out in the UI w/o bringing it into another app? Seems like the Playground is a bit limiting to make sure this looks how I want it to.
Storybook:
Update to docs:

feat: Add ability to pass in a component into Toggle label prop

---

packages/palette/src/elements/Checkbox/Check.tsx
packages/palette/src/elements/Checkbox/Checkbox.story.tsx
packages/palette/src/elements/Checkbox/Checkbox.tsx
packages/palette/src/elements/Clickable/Clickable.tsx

This PR fixes two issues with the checkbox:
1. It makes it accessible: can now be focused, selected with keyboard, and has proper aria tags
2. The label container was collapsing meaning you couldn't have checkbox labels that occupy the full-width of their container, this is the only noticeable change (flex: 1 on the label wrapper).
The component also now supports the full set of props as it's parent (clickable) — so it's a proper `Box` now.

fix(checkbox): makes checkbox accessible; supports box props

---

packages/palette/src/elements/Checkbox/Check.tsx
packages/palette/src/elements/Checkbox/Checkbox.story.tsx
packages/palette/src/elements/Checkbox/Checkbox.tsx
packages/palette/src/elements/Checkbox/__tests__/Checkbox.test.tsx
packages/palette/src/elements/Clickable/Clickable.tsx

Thanks for catching this. This PR reverts my revert. Then 5a4946ea8b6a34061c0fd32bad215dd5b2880425 changes it from a button back to a div, but handles the a11y changes manually.

fix(checkbox): makes a11y updates without using button

---

packages/palette/src/elements/Checkbox/Checkbox.story.tsx
packages/palette/src/elements/Checkbox/Checkbox.tsx
packages/palette/src/elements/Checkbox/__tests__/Checkbox.test.tsx
packages/palette/src/elements/Clickable/Clickable.story.tsx
packages/palette/src/elements/Clickable/Clickable.tsx
packages/palette/src/elements/Swiper/Swiper.story.tsx

@pepopowitz good idea re: Clickable; for some reason I thought the default button type was `button` but it's actually `submit`
We've never used a Clickable as a submit button before in Force so this shouldn't have any effect/I don't feel like we need to cut a breaking change... but let me know if you think otherwise.
I can't capture this in a test because Enzyme doesn't support event propagation; so just a story for now.
Also: I forgot to prevent the default of spacebar which is to scroll the page. Publishing a canary to verify in force.
<details>
<br />
```sh
npm install @artsy/palette@13.33.2-canary.858.15065.0
yarn add @artsy/palette@13.33.2-canary.858.15065.0
``` …

Change default Clickable type; minor checkbox fix

---

packages/palette/package.json
packages/palette/src/elements/Avatar/Avatar.story.tsx
packages/palette/src/elements/Button/Button.story.tsx
packages/palette/src/elements/Button/Button.tsx
packages/palette/src/elements/Checkbox/Checkbox.story.tsx
yarn.lock

This is a take it or leave it kind of thing — I find it useful in storybook to look at a story with all the (reasonably) possible states driven out simultaneously. [I packaged this component in a tiny lib](https://github.com/dzucconi/storybook-states), nothing fancy. Examples:
I'd refactor more stories where relevant if we are into this. 🤷

chore(storybook): rewrites some stories with storybook-states

---

packages/palette/src/elements/Toggle/Toggle.story.tsx
packages/palette/src/elements/Toggle/Toggle.tsx

Trying to make filters fully keyboard accessible.
Not much to this:
* refactored the component from class => functional
* made the header a `Clickable`
* added aria-expanded tag
One thing I didn't handle with this PR is doing the appropriate labelledby/region markup. We need to be able to generate unique IDs that are consistent across SSR/client-side render. Loathe to add a dependency; but looking at what [react-uid](https://github.com/thearnica/react-uid) is doing.
Another little wrinkle here is that I want to upgrade this to the `Text` component but will have to cut a breaking change for that since the types will break. Will probably do that separately picking up where https://github.com/artsy/palette/pull/780 left off.
----
Also my evergreen reminder that adding the accessibility …

fix(toggle): supports keyboard accessibility

---

packages/palette/src/elements/Join/Join.tsx

Co-authored-by: David Sheldrick <djsheldrick@gmail.com>
It looks `_react.default.Children.toArray` is returning an array containing an empty string which is causing the UI to break. We simply added a check to make sure that the child actually exists.

fix: check for empty strings in join

---

packages/palette/src/elements/EntityHeader/EntityHeader.story.tsx
packages/palette/src/elements/EntityHeader/EntityHeader.tsx
packages/palette/src/elements/Radio/Radio.story.tsx
packages/palette/src/elements/Radio/Radio.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.test.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.tsx

The behavior here was more surprising than I thought.
[WAI-ARIA example](https://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/examples/radio/radio-1/radio-1.html)
Just opening a draft here; few more things to button up, specs, and ensure there's no visual regressions. There was some weird margin behavior that was effecting the container that I removed but might have to put back.
<details>
<br />
```sh
npm install @artsy/palette@13.35.1-canary.863.15275.0
yarn add @artsy/palette@13.35.1-canary.863.15275.0
```
</details>

fix(a11y): makes radio / radio groups accessible

---

packages/palette/src/elements/Banner/Banner.story.tsx
packages/palette/src/elements/Banner/Banner.test.tsx
packages/palette/src/elements/Banner/Banner.tsx
packages/palette/src/elements/Message/Message.story.tsx
packages/palette/src/elements/Message/Message.tsx
packages/palette/src/themes/v2.tsx
packages/palette/src/themes/v3.tsx

So: I made some breaking changes here in order to improve/restrict the API.
* Removed `textSize` in Message because you can just use custom children if you really need to
* Removed `textColor` and `backgroundColor` because we don't want or need that.
There are a few changes to Volt and Force. I'm going to probably be doing this a few more times: cutting a breaking release and then updating Volt/Force. If you think I should include some other apps in this cycle then point them out; but those seem like the main to be concerned with.
<details>
<br />
```sh
npm install @artsy/palette@13.36.2-canary.869.15447.0
yarn add @artsy/palette@13.36.2-canary.869.15447.0
``` …

[v3] Banner/Message

---

packages/palette/src/elements/Button/v2/Button.tsx
packages/palette/src/elements/Grid/Grid.tsx
packages/palette/src/elements/ProgressBar/ProgressBar.story.tsx
packages/palette/src/elements/ProgressDots/ProgressDots.story.tsx
packages/palette/src/elements/Select/Select.story.tsx
packages/palette/src/elements/Select/Select.test.tsx
packages/palette/src/elements/Select/Select.tsx
packages/palette/src/elements/Select/tokens/types.ts
packages/palette/src/elements/Select/tokens/v2.ts
packages/palette/src/elements/Select/tokens/v3.ts
packages/palette/src/elements/Text/Text.tsx

On the V2 instances I got rid of the serif text in favor of a reasonable sans variant. Should be OK, works the same obviously. Also consolidated them into a single implementation then deprecated LargeSelect / SelectSmall.
width="50%" /><img src="https://user-images.githubusercontent.com/112297/110995794-ec48a580-8348-11eb-8a6a-a91d463cd802.png" width="50%" />

[v3] Select

---

packages/palette/src/elements/Select/Select.tsx
packages/palette/src/elements/Select/__tests__/Select.test.tsx

Trying this for a fix for https://app.circleci.com/pipelines/github/artsy/force/12768/workflows/07ed89b4-0685-4619-ab98-96b65751eb78/jobs/90755

fix(select): fix type signature for deprecated exports

---

packages/palette/src/elements/Input/Input.tsx

Would anyone oppose me changing the global font-family to courier or something obvious inside of storybooks so that we can be sure to catch things like this in the future?
The default font-family in most of Force is still, regrettably, Garamond.

fix(inputs): sets font-family to sans

---

packages/palette/src/elements/Separator/Separator.story.tsx
packages/palette/src/elements/Separator/Separator.tsx

Looks like Chrome updated the default style sheet for HRs which is causing some Separators which present as hr to look greenish.

fix(divider): resets default styling when presenting as hr

---

packages/palette-docs/content/docs/elements/layout/Toggle.mdx
packages/palette/src/elements/Toggle/Toggle.tsx
packages/palette/src/elements/Toggle/__tests__/Toggle.test.tsx

You can actually already use `<Toggle onClick={...}>`, but you'll get a type error. This PR adds it to `Toggle`'s interface. Current anticipated use case is adding a tracking event to a toggle in Volt so we can see when users interact with it.
Seem reasonable to folks?

feat: add optional onClick prop to Toggle

---

.circleci/config.yml
.gitignore
package.json

This deploys our storybooks to an `artsy-palette-storybook` S3 location.

ci: Deploy storybooks via Circle orb

---

packages/palette/src/themes/Themes.story.tsx

The category "helpers/controls" seems a bit confusing, so just renamed to catch all "Components". Thoughts?

storybook: Rename helpers/controls > components

---

packages/palette/src/elements/LabeledInput/LabeledInput.story.tsx
packages/palette/src/elements/LabeledInput/LabeledInput.tsx

Currently have the situation where I'd like to use this label prop to insert a clear button for a filter input. I think it makes sense for textual labels to have pointer-events none and then leave it alone for custom components.

fix(labeledinput): allows for clickable labels

---

packages/palette/src/elements/LabeledInput/LabeledInput.tsx

OK last one 😉 
Fixes the tabindex by just moving the label into a natural order.

fix(labeledinput): corrects tabindex

---

packages/palette/src/elements/Select/Select.story.tsx
packages/palette/src/elements/Select/Select.tsx

Re: https://artsy.slack.com/archives/C9XJKPY9W/p1616618231018200
This PR fixes a minor issue I noticed when investigating; that longer values will cut into the caret issue.
Regarding the problem mentioned in chat: I'm going to just manually pass `display="inline-flex"` to the few instances where this is a problem in Force. I don't want to change it for default `inline` variants because the current display property makes more sense when using columns for layout.

fix(select): adjusts padding to accommodate caret

---

packages/palette/src/themes/v2.tsx
packages/palette/src/themes/v3.tsx

I noticed this while trying to use the `xs` media query inside of a styled-component using `themeGet`. The `media` util in Palette builds them but isn't theme-aware.
<del>Riddle me this: how is [this code working currently?](https://github.com/artsy/force/blob/5c79ce80607403c2e6e4de629500383d6ddcef59/src/v2/Components/NavBar/NavBar.tsx#L56-L57)</del> Answered my own question: it's not working currently 👅  and this should fix it.

fix(theme): corrects media queries

---

packages/palette/src/elements/ReadMore/ReadMore.story.tsx
packages/palette/src/elements/ReadMore/ReadMore.tsx

Re: https://github.com/artsy/force/pull/7289
Bug report here: https://github.com/facebook/react/issues/16416
I suspect this only surfaced when we upgraded React the other day but I'm not sure of that. Removing the memoization should fix.
We'll want to revert https://github.com/artsy/force/pull/7289 when this is released inside of Force.
<details>
<br />
```sh
npm install @artsy/palette@14.15.1-canary.901.16300.0
yarn add @artsy/palette@14.15.1-canary.901.16300.0
```
</details>

fix: protects against error on ssr

---

packages/palette/src/elements/ReadMore/ReadMore.tsx
packages/palette/src/elements/ReadMore/__tests__/ReadMore.test.tsx

Makes it a little safer as we noticed it was blowing up in force when operating on null data.

bugfix: Ensure read more only operates on strings

---

packages/palette/src/elements/Link/Link.tsx
packages/palette/src/elements/Pagination/LargePagination.tsx
packages/palette/src/elements/Pagination/Pagination.story.tsx
packages/palette/src/elements/Pagination/Pagination.tsx
packages/palette/src/elements/Pagination/SmallPagination.tsx
packages/palette/src/elements/Pagination/__tests__/Pagination.test.tsx
packages/palette/src/elements/Pagination/__tests__/SmallPagination.test.tsx
packages/palette/src/elements/Pagination/index.tsx

V2 remains basically the same. I cleaned up some alignment issues and deprecated `SmallPagination` — moved `LargePagination` to just `Pagination` and deprecated the alias. Shouldn't be any breaking changes unless some specs reach into the buttons (possible...) — Will check that out with the canary before merging.
<details>
<br />
```sh
npm install @artsy/palette@14.17.2-canary.906.16421.0
yarn add @artsy/palette@14.17.2-canary.906.16421.0
```
</details>

[v3] Pagination

---

packages/palette/src/elements/Shelf/Shelf.tsx

This updates the `Shelf` so that we can position items within it. Current use-case prompting this change is the MyBids component, which doesn't work bottom up.

feat: Add alignItems prop to shelf

---

packages/palette/src/elements/Shelf/Shelf.story.tsx
packages/palette/src/elements/Shelf/Shelf.tsx

Adds a new `showProgress` prop to Shelf, so that one can show / hide the progress bar. This makes shelf a more generic `Carousel` component. Also updates stories.

feat: Add showProgress prop to Shelf

---

packages/palette/src/elements/Shelf/Shelf.tsx

The spacing was a bit too tight between the shelf items and the progress bar, per the comps. Increased it to a 6:

fix: Increase scroll bar space

---

packages/palette/src/elements/Shelf/Shelf.tsx

Noticed that arrows would appear when interacting on phone

fix: [Shelf] Dont show arrows if on touch device

---

packages/palette/src/elements/ProgressBar/ProgressBar.tsx
packages/palette/src/elements/Shelf/Shelf.tsx

Quick little fix to just tie the progress directly to scroll. I think I was stuck in thinking about this from the cell-based older components.

fix(shelf): smoother progress

---

packages/palette/src/elements/Tabs/Tabs.tsx

In trying to get https://github.com/artsy/force/pull/7514 over the finish line, I'm running up against some frustrating type failures. 
```
src/v2/Apps/Artwork/Components/ArtworkDetails/index.tsx:72:11 - error TS2322: Type 'undefined' is not assignable to type 'TabLike & ReactNode'.
72           {/* @ts-expect-error STRICT_NULL_CHECK */}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Evidently JSX comments can be interpreted as undefined. Also, statements that don't correctly evaluate could return null-ish which is its own issue. 
Loosening the types here will hopefully help resolve that.

Loosen tab types to allow null, undefined

---

packages/palette/src/elements/Tooltip/Tooltip.story.tsx
packages/palette/src/elements/Tooltip/Tooltip.tsx

Pretty much the same just some minor clean up; and convert to v3. Added support for keyboard focus as well.
<details>
<br />
```sh
npm install @artsy/palette@14.30.2-canary.939.17313.0
yarn add @artsy/palette@14.30.2-canary.939.17313.0
```
</details>

feat(tooltip): supports v3; supports keyboard focus

---

packages/palette/src/elements/Cards/SmallCard.tsx

https://artsyproduct.atlassian.net/browse/FX-2988
On Safari images were rendered with incorrect aspect ratio:
After fixing it looks like this:

fix: Small card images width

---

packages/palette/src/elements/Radio/Radio.story.tsx
packages/palette/src/elements/Radio/Radio.tsx

This is to accommodate a situation we have on the artwork sidebar where we need to float over a price on the right hand side of the container.

fix(radio): allows for custom labels to occupy immediate container

---

packages/palette/src/elements/Button/Button.story.tsx
packages/palette/src/elements/Button/v2/Button.tsx
packages/palette/src/elements/Button/v3/Button.tsx

This lets us use `<Button as={RouterLink} to="/whatever">` etc. As always the typing here is a problem but since this is more of an escape hatch for a few one-offs I feel fine about that.

feat(button): supports `as` prop

---

packages/palette/src/elements/Tooltip/Tooltip.story.tsx
packages/palette/src/elements/Tooltip/Tooltip.test.tsx
packages/palette/src/elements/Tooltip/Tooltip.tsx

Another small bug fix. Always forget that it's possible to overwrite the existing props when using `cloneElement`

fix(tooltip): avoids blowing away child props

---

packages/palette/src/elements/Image/Image.tsx
packages/palette/src/elements/Image/LazyImage.tsx
packages/palette/src/elements/Skeleton/Skeleton.tsx

I mentioned this over Slack — but this animation never got disabled on lazy images. As a result when there are a lot of them, performance drops dramatically. The homepage rebuild I'm working on goes from basically unusable to normal 60fps when I simply disable the animation in the class.
EDIT: Trying this now with an opacity animation and disabling it once done.
<details>
<br />
```sh
npm install @artsy/palette@14.35.3-canary.950.17754.0
yarn add @artsy/palette@14.35.3-canary.950.17754.0
```
</details>

fix(image,skeleton): optimizes skeleton animations

---

packages/palette/package.json
packages/palette/src/elements/DonutChart/DonutChart.test.tsx
packages/palette/src/elements/DonutChart/DonutChart.tsx
packages/palette/src/elements/LineChart/LineChart.test.tsx
packages/palette/src/elements/LineChart/LineChart.tsx
packages/palette/src/elements/LineChart/LineChartSVG.tsx
packages/palette/src/elements/Modal/Modal.tsx
yarn.lock

This removes react spring from the app per [this thread](https://artsy.slack.com/archives/CA8SANW3W/p1624453974296000).
In short, react spring was causing a memory leak in our application. We've removed animation from the charts and replaced animation in modal with css, which additionally removes a boat load of complexity.

fix: Remove react-spring

---

packages/palette/src/elements/Join/Join.story.tsx
packages/palette/src/elements/Join/Join.tsx

Closes [WP-60](https://artsyproduct.atlassian.net/browse/WP-60)
You may want to conditionally render multiple things inside a join, which may require the use of a fragment. This change supports those cases.

fix(join): supports nested children

---

packages/palette/src/elements/Text/Text.story.tsx
packages/palette/src/elements/Text/Text.tsx

This is more of a nice-to-have / progressive enhancement. [It's reasonably well supported with all the evergreens.](https://caniuse.com/css-line-clamp)

feat(text): adds line-clamp

---

packages/palette/src/elements/Tabs/Tabs.tsx

Closes: [WP-59](https://artsyproduct.atlassian.net/browse/WP-59)
This _should_ fix the issue. Attempted to upgrade styled-components to 5 but it didn't make a difference in Storybook. Could just be some kind of import order thing in Force itself rather than here.
<details>
<br />
```sh
npm install @artsy/palette@14.41.2-canary.965.18222.0
yarn add @artsy/palette@14.41.2-canary.965.18222.0
```
</details>

fix(tabs): attempts to fix unstyled tabs in force

---

packages/palette/src/elements/Tabs/Tabs.tsx

https://github.com/artsy/palette/pull/965 introduced a minor visual bug where the first tab wouldn't fill out the container. Chromatic caught this but after merge since it currently isn't blocking PRs (TODO).

fix(tabs): fixes styling

---

packages/palette/src/elements/Carousel/Carousel.tsx
packages/palette/src/elements/Carousel/__tests__/Carousel.test.tsx
packages/palette/src/elements/Swiper/Swiper.tsx
packages/palette/src/elements/Swiper/__tests__/Swiper.test.tsx

This PR adds `onPageCountChange` event to be able to make dynamic data loading for the `Swiper` and `Carousel`.
I want to add batch loading for the artworks on the Artists page(PPP) and as far as I see now it's impossible to implement that without page count information. Please let me know if you have another option.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4310

fix(PX-4310): get page count information from Swiper and Carousel

---

packages/palette/src/elements/Image/Image.story.tsx
packages/palette/src/elements/Image/Image.tsx

While although this doesn't do much in addressing [my list of grievances](https://artsyproduct.atlassian.net/browse/DSWGW-79) — I do need to put an `id` on an image so this fixes the types.
<details>
<br />
```sh
npm install @artsy/palette@14.43.1-canary.978.18680.0
yarn add @artsy/palette@14.43.1-canary.978.18680.0
```
</details>

fix(image): supports native img props

---

packages/palette/src/utils/index.ts

Just exporting two more hooks that are useful. Need `useIsomorphicLayoutEffect`, as it happens.

feat(hooks): exports hooks

---

packages/palette/src/Theme.tsx

An export was missed when completing the palette-tokens work, but it didnt' show up in force because renovate auto-update pr failed on type-check (and didn't notice). This fixes that.

fix: Fix missing TextVariant export 

---

packages/palette/src/elements/Pagination/SmallPagination.tsx
packages/palette/src/elements/Pagination/__tests__/SmallPagination.test.tsx

This PR doesn't allow clicking on the next or prev button if there is no next or prev page. 
JIRA - https://artsyproduct.atlassian.net/browse/PX-4059
Before
https://user-images.githubusercontent.com/79979820/126981637-beff0abd-a7a8-48f5-b077-d7589020a10b.mov

fix(PX-4059): prevent link click if there is no next or prev page

---

packages/palette/src/Theme.tsx

This exports our palette theme constants so that we can access static values outside of the hook

feat: Export v2/v3 theme constants

---

packages/palette-tokens/src/helpers.ts
packages/palette/src/helpers/color.ts
packages/palette/src/helpers/space.ts

Deprecates `color` and `space`

chore(space,color): deprecates space & color functions

---

packages/palette/src/elements/Input/Input.story.tsx
packages/palette/src/elements/Input/Input.tsx
packages/palette/src/elements/Input/tokens/v2.ts
packages/palette/src/elements/Input/tokens/v3.ts

The use-case for this is to align the v3 inputs with the height of the Artsy logo in the global nav.
Currently (50px):

feat(input): supports inputs with custom heights

---

.circleci/config.yml

Lets lean on existing deploy pipelines to deploy the docs static files. 
Also cleans up some naming to better distinguish between docs and storybooks.

ci: Use s3-orb to deploy docs

---

packages/palette-docs/README.md

Adds docs on how Algolia DocSearch is used to provide search within our docs.
Context: [this slack conversation](https://artsy.slack.com/archives/C2TQ4PT8R/p1628100125016300)

chore: docs for algolia docsearch

---

packages/palette/src/elements/Text/Text.tsx

I just paired with @rajsam003 to figure this one out... working off https://github.com/artsy/palette/pull/1006
The way `BaseTab` is set up is that it expects to be a button, potentially. So rather than altering those styles, it'd be good to just be able to use `as={Clickable}` and have it work as you'd expect.
We can [use this recommendation from styled-components](https://styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity) to increase the specificity of the `Text` styles and that way we can use `Clickable` again without too much worry.

fix(text): increases text styles specificity

---

packages/palette/src/elements/Text/Text.tsx

Good catch @lilyfromseattle — once this is published you can cast as this. Alternatively I could just make this a string value but we'd lose the auto-complete 🤔

fix(text): exports text-transform type

---

packages/palette/src/elements/Avatar/Avatar.story.tsx
packages/palette/src/elements/Avatar/Avatar.test.tsx
packages/palette/src/elements/Avatar/Avatar.tsx
packages/palette/src/elements/EntityHeader/EntityHeader.story.tsx
packages/palette/src/elements/EntityHeader/EntityHeader.tsx
packages/palette/src/elements/EntityHeader/__tests__/EntityHeader.test.tsx
packages/palette/src/elements/EntityHeader/v3/EntityHeader.tsx

Closes: [GRO-480](https://artsyproduct.atlassian.net/browse/GRO-480)
We'd like to support both `srcSet` and `lazyLoad` on images in `EntityHeaders`, this change deprecates the `imageUrl` prop and adds support for passing arbitrary image props, which get threaded into the image in `Avatar`.

fix(avatar,entityheader): supports detailed image props

---

packages/palette/src/elements/Pill/Pill.story.tsx
packages/palette/src/elements/Pill/Pill.tsx

Artist tags occasionally are quite long and break.

fix(pill): fixes multi-line pills

---

packages/palette/src/elements/Avatar/Avatar.tsx
packages/palette/src/elements/Cards/MediumCard.tsx
packages/palette/src/elements/Cards/SmallCard.tsx
packages/palette/src/elements/EntityHeader/EntityHeader.tsx
packages/palette/src/elements/Image/Image.story.tsx
packages/palette/src/elements/Image/Image.tsx
packages/palette/src/elements/Image/LazyImage.tsx

This is some prep work for fixing [our issue with image width + height](https://artsyproduct.atlassian.net/browse/GRO-479). Removes the deprecated `ResponsiveImage` (work to support this has already been merged in Force: https://github.com/artsy/force/pull/8178). And cleans up some of the typings, which were an artifact from the previous React Native support.
This will be another breaking release. (Our 3rd today!)
<details>
<br />
```sh
npm install @artsy/palette@15.0.1-canary.1019.20055.0
yarn add @artsy/palette@15.0.1-canary.1019.20055.0
```
</details>

chore(image): removes responsive image; cleans up types

---

packages/palette/src/elements/BaseTabs/BaseTabs.tsx
packages/palette/src/elements/Tabs/Tabs.story.tsx

Fix for failures occurring in https://github.com/artsy/force/pull/8318 — assuming this is somehow related to strict typing being turned on?

fix(tabs): loosens up tab types so as to support conditional children

---

packages/palette/src/elements/Modal/ModalBase.tsx

Addresses [PURCHASE-2883]
We discussed this issue briefly in [slack](https://artsy.slack.com/archives/C9XJKPY9W/p1629131314102000). @dzucconi pointed out the fact that bootstrap tried a similar approach to accidental modal closures and ended up reverting the change. After digging through the conversation around that reversion it appears that bootstrap modals were closing when the content inside the modal was scrollable, and the user tried to use the browser level scroll bar to navigate the modal. Fortunately, this makes bootstrap's issue a moot point for us. 
Palette uses an in-dialog scroll bar which is not subject to the same event tree that caused problems for bootstrap. I've tested the display in chrome, firefox and safari and this remains true in all browsers. Similarly, the change …

change modal close to onMouseDown

---

packages/palette/src/elements/ReadMore/ReadMore.tsx
packages/palette/src/elements/ReadMore/__tests__/ReadMore.test.tsx

[FX-3315]
This PR adds ability to collapse text back down after expanding it
**Demo**
[FX-3315]: https://artsyproduct.atlassian.net/browse/FX-3315

feat(ReadMore): Added Read less functionality

---

packages/palette/src/elements/Button/v2/Button.tsx
packages/palette/src/elements/Button/v3/Button.tsx

Minor thing I noticed in the iOS15 update. Buttons with `type="submit"` are automatically bolded.

fix(button): ensures submit buttons are same font-weight

---

packages/palette-docs/content/docs/hooks/useFocusLock.mdx
packages/palette/src/utils/useFocusLock.story.tsx
packages/palette/src/utils/useFocusLock.ts
packages/palette/src/utils/useMutationObserver.ts

* Ignores mutation observer hook when mutation observer isn't defined (specifically our version of Jest in Force)
* Improves docs
* Better handling of story surrounding clicks in focus lock

fix(hooks): improves focus lock and mutation observer hooks

---

packages/palette/src/elements/Link/Link.tsx

It doesn't technically *need* to be deprecated, but folks use it enough to need a pointer to `RouterLink`.

Deprecate <Link>

---

packages/palette/src/elements/HorizontalOverflow/HorizontalOverflow.story.tsx
packages/palette/src/elements/HorizontalOverflow/HorizontalOverflow.tsx

Small fix for this component so that we can use it in places where we want a specific height without relying on padding.

fix(horizontaloverflow): ensures internal heights match external

---

packages/palette/src/elements/BaseTabs/BaseTab.tsx
packages/palette/src/elements/Stepper/Stepper.tsx
packages/palette/src/elements/Tabs/Tabs.story.tsx
packages/palette/src/elements/Tabs/Tabs.tsx

Closes: [DSWGW-96](https://artsyproduct.atlassian.net/browse/DSWGW-96)
`scrollIntoView` makes this nice and simple. This should just be on by default and there's no need to trigger it via prop.

feat(tabs): supports autoscrolling on tab selection

---

packages/palette/src/elements/Button/Button.tsx
packages/palette/src/elements/Text/Text.tsx

During my onboarding, I made some questions that could be easily answered with enhanced documentation of the `variants` of a few components.
This PR improves the Button and Text `variant` property document.

docs(types): Improve DX on Button/Text variants

---

packages/palette/src/elements/Input/Input.tsx
packages/palette/src/elements/LabeledInput/LabeledInput.story.tsx
packages/palette/src/elements/LabeledInput/LabeledInput.tsx

Since the title and description are contained within the input, we need to insert the children inside a wrapper around the input itself so that the label height is correct.

fix(labeledinput): fixes height when title/description are present

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx

This makes more sense since the component is expecting any options passed into be pre-filtered. If you wanted to disable them for some query length you'd simply do so `{query.length !== 0 ? options : []}`

fix(autocomplete): display options if they are present regardless of query

---

packages/palette/src/elements/BaseTabs/BaseTabs.tsx
packages/palette/src/elements/HorizontalOverflow/HorizontalOverflow.tsx
packages/palette/src/elements/Stepper/Stepper.tsx
packages/palette/src/elements/Tabs/Tabs.story.tsx
packages/palette/src/elements/Tabs/Tabs.tsx

So — the problem was that `scrollIntoView` was working — meaning it _was_ scrolling the active tab into view horizontally _as well as_ vertically.  This isn't really a problem when triggered via a click since to click something it's always going to be in the viewport. But this became a problem when we started using the prop to drive the active index since the initial mount is going to force the `scrollIntoView` as well.
Initially my thought was that we could use `useUpdateEffect` to skip the initial mount, but that has a few problems: one is that Force pages re-render _a lot_. Another is that if you set the initial index to something something that was off-screen it wouldn't be scrolled to initially.
Two things needed to happen:
* We need to manually scroll by getting a handle on the …

fix(tabs): avoids scrolling on mount

---

packages/palette/package.json
packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.test.tsx
packages/palette/src/utils/index.ts
packages/palette/src/utils/useContainsFocus.ts
yarn.lock

This should take care of [DSWGW-99](https://artsyproduct.atlassian.net/browse/DSWGW-99)
A small note is that instead of altering the native `onBlur`, I've added an `onClose` prop that will run after the options are closed (when focus leaves the component group).
Install the canary once it publishes and let me know if I've missed anything.
<details>
<br />
```bash
npm install @artsy/palette-charts@17.7.2-canary.1075.21847.0
npm install @artsy/palette@18.7.2-canary.1075.21847.0
yarn add @artsy/palette-charts@17.7.2-canary.1075.21847.0
yarn add @artsy/palette@18.7.2-canary.1075.21847.0
```
</details>

fix(DSWGW-99): Autocomplete Q/A

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
packages/palette/src/utils/useContainsFocus.ts

Moves onClose to the focus leave hook. Also (!) fixes a memory leak in that hook.

fix(autocomplete): improves onclose; fixes memory leak

---

packages/palette/src/elements/Clickable/Clickable.story.tsx
packages/palette/src/elements/Clickable/Clickable.tsx

Apparently all buttons have a default 2px vertical margin in Safari. Here we reset that.

fix(clickable): resets margin for safari

---

packages/palette/src/elements/Modal/Modal.story.tsx
packages/palette/src/elements/Modal/Modal.tsx
packages/palette/src/utils/useOnScroll.ts

[NX-2486]
This PR updates the Modal to the latest changes from Design. Also implements a new idea, the shadow over sticky elements only when the content it's scrolled, getting back to scrollTop 0, doesn't show the shadow.
I kept the old narrow behavior and didn't create any breaking changes, only styling things happened here.
I wanted to create unit tests for this new hook but with Enzyme and the use case was tricky to be done, I wonder if we're going to extend RTL to Palette too, my vote is YES, definitely facilitates some neat stuff to test like hooks over Enzyme.
<details>
<summary>Desktop</summary>
https://user-images.githubusercontent.com/15792853/142894439-6844b8e7-c5cf-45d5-873d-5ccc51444b61.mov
</details>
<details>
<summary>Mobile</summary> …

feat(NX02486): adjusts the modal to the new design

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx

Will only try to close and execute callback if options are visible.

fix(autocomplete): only closes when options are visible

---

packages/palette/src/elements/Modal/Modal.tsx

[NX-3032]
This PR adds 20px of space around the modal in xs breakpoint.
[NX-3032]: https://artsyproduct.atlassian.net/browse/NX-3032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NX-3032): add space of 20px in xs breakpoint

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx

This PR stops default behavior and event propagation for the `onEnter` handler in `AutocompleteInput`
**VIDEO:clapper: :**
BEFORE: (`onEnter` triggers form submit if the user has filled valid form)
https://user-images.githubusercontent.com/55637696/147667204-b0e0273e-75da-43a5-9bd3-4eda889759fd.mov
https://user-images.githubusercontent.com/55637696/147667215-e62c4ce7-35dc-4411-aee2-203e87348dda.mov
https://user-images.githubusercontent.com/55637696/147667380-4e9e3b45-83de-4d30-bd1f-0919ce8e6f0f.mov
AFTER:

fix(SWA): Fix onEnter in AutocompleteInput

---

packages/palette/.eslintrc.js

Closes https://artsyproduct.atlassian.net/jira/software/projects/WP/boards/97?selectedIssue=WP-51
Hooks linting was missing.

toolchain(linting): Add rule-of-hooks

---

packages/palette-charts/package.json

See https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/ 
We don't import this lib directly, but it is an ephemeral dep, which still runs the risk of an automatic update.

security(colors.js): Lock version to 1.4 due to corruption

---

packages/palette/src/elements/FilterSelect/Components/FilterSelectContext.tsx
packages/palette/src/elements/FilterSelect/FilterSelect.story.tsx
packages/palette/src/elements/FilterSelect/FilterSelect.test.tsx
packages/palette/src/elements/FilterSelect/FilterSelect.tsx
packages/palette/src/elements/FilterSelect/index.tsx

Adds a new multiselect prop so that we can support single select lists. Also updates a type to support dynamic relay list types from force. See "typescript readonly confusion" in google 😓

feat(filterselect): Add multiselect option

---

packages/palette/src/utils/useFocusLock.story.tsx
packages/palette/src/utils/useFocusLock.ts

Nodes with `tabIndex="-1"` shouldn't be focusable.

fix(usefocuslock): skips -1 tabindex elements

---

packages/palette/src/elements/Modal/ModalBase.tsx

Noticed that pages in force were erroring out if they include the ModalDialog, but aren't guarded against on the server.

fix(ModalBase): Make SSR friendly

---

packages/palette-docs/content/docs/index.mdx
packages/palette-docs/src/components/Sidebar/NavTree.tsx
packages/palette-docs/src/components/TableOfContents.tsx

Realized that my main issue was that the two logos on the home page (and the far right column header) were all top aligned, but are difference sizes. I made everything vertically centered (just about), and now it looks right. Also removed the vertical lines in the left sidebar: 
looks A+ now

chore(docs): Super minor fixes

---

packages/palette-charts/src/elements/DonutChart/DonutChart.tsx

Addresses [PX-4907]
In #956, we removed react-spring, and as part of this work we removed logic that was setting the opacity of DonutChart labels from 0 to 1. The effect of this was that the labels remained at `opacity:0`, and never appeared. 
This PR removes opacity from the DonutChart. Since the previous PR removed the "flourish" from this component, I don't personally think it is worth preserving the fading-in effect on the labels. Instead, they are now permanently visible. 
It's been a while since I contributed here in palette so please let me know if I interpreted incorrectly and need to manually generate a changelog entry 😅 
cc @artsy/px-devs 
[PX-4907]: https://artsyproduct.atlassian.net/browse/PX-4907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …

fix: remove permanent transparency from DonutChart labels

---

packages/palette/src/elements/Popover/Popover.tsx
packages/palette/src/utils/useClickOutside.ts

This is a weird one — https://github.com/artsy/palette/commit/bb715ff204d1604fb6b0d4179ff1df6e0cefcad2 introduced some state into the `usePosition` hook, which should be fine. But the re-render that state initiates causes it to compete with the click handler that `useClickOutside` registers. So you click to make the popover visible, but that click propagates to the useClickOutside handler which then hides the popover. The solution is to wait for the stack to clear after visibility changes before adding the handler.
As far as catching issues like this with tests: I think we need to add a Cypress test suite. We definitely need more fidelity for these very UI-centric specs and they would be much easier to write.

fix(useclickoutside): wait for stack to clear before adding event

---

packages/palette/src/elements/Pill/Pill.tsx

- Removes `lineHeight={1}` from Pill text to prevent cutting off letters like `g`, `q`, `p`
- Adds clarification about `active` prop style to be more visible
> NOTE: The text background color in the screenshots is not included
|Before|After|
|--|--|
|![Screenshot 2022-03-04 at 11 56 22](https://user-images.githubusercontent.com/21178754/156752554-bf6d25d6-198e-4fdc-9ebf-c7b9980fa17f.png)|![Screenshot 2022-03-04 at 11 56 08](https://user-images.githubusercontent.com/21178754/156752550-d82e68d0-3ebc-4ea9-84e9-2eb84410135d.png)|
|![Screenshot 2022-03-04 at 12 00 51](https://user-images.githubusercontent.com/21178754/156752561-4438ddb5-8429-4758-958b-910c085f144a.png)|![Screenshot 2022-03-04 at 11 59 05](https://user-images.githubusercontent.com/21178754/156752559-b87d0a68-aaf6-4d8c-87d7-46a59 …

fix: removed line height from pill text

---

packages/palette/src/elements/ModalDialog/ModalDialog.tsx

We have a difference of 40px of width in the modal that's is caused by extra padding from left and right, 20px each side; the width should be 440px but the padding are eating 40px. This PR fixes the width of the modal to make it consistent with Figma.
Before
After

fix: modalDialog width

---

packages/palette/src/elements/FilterSelect/FilterSelect.tsx

This actually provides a fix for the double page view logging on `/works-for-you`. Generally speaking, when you manually implement `onChange` you want to use `useUpdateEffect` so that it's not called on mount. In this case https://github.com/artsy/force/blob/bb2c444e9f555fc58817782782df2eb6232d7ea4/src/v2/Apps/WorksForYou/WorksForYouApp.tsx#L46-L54 — `onChange` was being called on mount causing a redirect to itself, which was logging a pageview since the middleware was getting executed with the referrer change.

fix(filterselect): avoids calling onchange on mount

---

packages/palette/src/elements/BaseTabs/BaseTabs.tsx
packages/palette/src/elements/Join/Join.tsx
packages/palette/src/elements/Tabs/Tabs.story.tsx
packages/palette/src/elements/Tabs/Tabs.tsx

So this is still a problem, sort of.
Currently the auction pages use the `Tabs` component to display the associated auction. We actually very rarely navigate from a given page to another page of the same type, which is why I think this was never noticed. When that happens though the children of the tabs change, the overall `Tabs` component gets reused without the re-render. Since the child re-renders the tab *should* update and re-render but it doesn't. Two reasons for that. One is that we put the active tab in a ref https://github.com/artsy/palette/pull/1070 to prevent re-rendering on mount to prevent it being scrolled to. Looking at this now I feel like I have a few different ideas on how to solve this but I'm having trouble getting a reliable reproduction of the original issue. (Which …

fix(tabs): cached tabs rendering

---

packages/palette/src/elements/Expandable/Expandable.story.tsx
packages/palette/src/elements/Expandable/Expandable.tsx

This PR is needed for the new payment flow for [TX-225](https://artsyproduct.atlassian.net/browse/TX-255) where we need the ability to close an expandable within the expandable content. 
I’ve added an example to the story as well:
https://user-images.githubusercontent.com/50849237/161734257-8006c607-11d2-443a-b00f-80a9b4b8cc03.mov

feat(TX-255): ability to close expandable within expandable content

---

packages/palette/src/elements/FilterSelect/Components/FilterSelectContext.tsx

Related PR: #1154
* use `useUpdateEffect`
* fixed an issue when the length of `selectedItems` is 0

fix: some small improvements for FilterSelectContext

---

packages/palette-docs/content/docs/elements/Message.mdx

Noticed that `Message` was missing from our docs. 
cc @artsy/grow-devs

docs(message): Add missing <Message> component to docs

---

packages/palette/src/elements/Text/Text.tsx

Should have done this a while ago. Updates the default variant from `text` to `sm`.

fix(text): updates default variant to v3

---

packages/palette/src/elements/Spinner/Spinner.story.tsx
packages/palette/src/elements/Spinner/Spinner.tsx

Fixes an annoyance with the `Spinner` component. Can now turn off the default assumption that it should be positioned absolutely. Would like to make that default sensible (static) but, for another day.

fix(spinner): supports box props; respects theme

---

packages/palette-docs/content/docs/index.mdx

Adds a notice to the palette homepage reminding the user about storybooks:

docs(storybook): add notice about our storybooks site

---

packages/palette-docs/content/docs/atoms/Spacing.mdx
packages/palette-docs/content/docs/guides/development.mdx
packages/palette-docs/content/docs/guides/migration.mdx
packages/palette-docs/content/docs/index.mdx
packages/palette-docs/src/layouts/MainLayout.tsx
packages/palette-docs/src/utils/getEditUrl.ts
packages/palette-tokens/README.md

Landed in bizarro world on this one. I swear this was already done? 
In any case, fixes some `master` -> `main` docs links.

chore(docs): Fix broken links

---

packages/palette-docs/src/components/Sidebar/SearchBox.tsx

[WP-52](https://artsyproduct.atlassian.net/browse/WP-52)
I overrode the default DocSearch navigate behavior and replaced it with Gatsby navigate. This should make the search always navigate to the correct pathname, even when running locally.

fix(WP-52): search navigates to correct pathname on local

---

packages/palette/src/elements/ResponsiveBox/ResponsiveBox.story.tsx
packages/palette/src/elements/ResponsiveBox/ResponsiveBox.tsx

We're seeing an issue where: when `ResponsiveBox` components are used, within a single wrapper, within the context of a CSS column, images don't load. This appears to be a Chrome specific bug which has been introduced recently. My theory is that it has to do with the `height: 0`. Either way; it's not a bad reason to use this as a motivator to upgrade to just using native `aspect-ratio`, [which is well supported](https://caniuse.com/mdn-css_properties_aspect-ratio) in all the browsers we're concerned with. A nice benefit here is that we can drop 2 extra DOM nodes per instance.

fix(responsivebox): utilize native aspect-ratio property in place of padding-bottom hack

---

packages/palette/src/elements/Dropdown/Dropdown.story.tsx
packages/palette/src/elements/Dropdown/Dropdown.tsx

For the [FX-4007 task](https://artsyproduct.atlassian.net/browse/FX-4007), it is necessary to add the ability to open the menu by click (not hover effect). This PR adds such an opportunity for `Dropdown` component
https://user-images.githubusercontent.com/3513494/172599110-c740a0f0-21c0-4695-9983-faf39d524f61.mp4

feat: add ability to open Dropdown by click

---

packages/palette/src/utils/usePortal.ts

Wraps the teardown here in a try/catch just in case something else has removed the node.

fix(useportal): guards on removal

---

packages/palette/src/svgs/WeChatIcon.tsx
packages/palette/src/svgs/_icons.story.tsx

Thought this was weird to have here. Making this a simple icon and will replicate functionality using a real tooltip inside of Force.
<details>
<br />
```bash
npm install @artsy/palette-charts@21.0.1-canary.1187.24374.0
npm install @artsy/palette@22.0.1-canary.1187.24374.0
yarn add @artsy/palette-charts@21.0.1-canary.1187.24374.0
yarn add @artsy/palette@22.0.1-canary.1187.24374.0
```
</details>

fix(icons): removes hover functionality from wechat icon

---

packages/palette/src/elements/Banner/Banner.tsx

This will aid in doing full bleed banners in Force in a consistent fashion.

feat(banner): exports variants; ensures text stays centered when dismissible

---

packages/palette/src/elements/Clickable/Clickable.tsx
packages/palette/src/elements/FilterSelect/FilterSelect.tsx
packages/palette/src/elements/ShowMore/ShowMore.story.tsx
packages/palette/src/elements/ShowMore/ShowMore.tsx

Allowing clients to update the styles on the Clickable wrapper and Text component means we can use this component in cases like https://www.figma.com/file/9DMfKOi5RuuBD2f49eB9nV/Artwork-page?node-id=1825%3A96724

feat: make ShowMore more flexible

---

packages/palette/src/elements/Select/Select.tsx

This PR updates Palette's `<Select />` to accept & leverage reference objects.

refactor(Select): add useForwardRef

---

packages/palette/src/elements/Popover/Popover.tsx

Added the ability to pass box props for the `Popover` component (for example, to set the max width of the popover container)

chore: forward box props to `Popover` component

---

packages/palette/src/elements/Shelf/ShelfScrollBar.tsx

A minor fix to address a kind of odd Lighthouse callout. We skip over this button with the tab index so the only time this gets announced is if you use a pointer device to access it.

fix(shelf): adds label to scrollbar thumb

---

packages/palette/src/elements/Popover/Popover.story.tsx
packages/palette/src/elements/Popover/Popover.tsx

The `onClose` prop will be useful for those cases where the `Popover` is a controlled component and visibility is controlled via the `visible` prop
https://user-images.githubusercontent.com/3513494/197190835-e73add19-ff5b-4098-a282-affaf3b65ad4.mp4

feat: add ability to pass `onClose` prop for `Popover` component

---

packages/palette/package.json
packages/palette/src/elements/ModalDialog/ModalDialog.tsx
packages/palette/src/utils/useDidMount.ts
yarn.lock

* `useDidMount` now accepts an options object instead of a single flag
<details>
<br />
```bash
npm install @artsy/palette-charts@25.0.0-canary.1217.25048.0
npm install @artsy/palette@26.0.0-canary.1217.25048.0
yarn add @artsy/palette-charts@25.0.0-canary.1217.25048.0
yarn add @artsy/palette@26.0.0-canary.1217.25048.0
```
</details>

fix: updates react-remove-scroll

---

packages/palette/.eslintrc.js
packages/palette/src/elements/HorizontalOverflow/HorizontalOverflow.tsx

Depending on if an element is centered, the actual detected difference in scroll might be a half pixel. Here we loosen the detection to happen within 1px.

fix(horizontaloverflow): accommodate half pixel differences

---

packages/palette/src/elements/Select/Select.story.tsx
packages/palette/src/elements/Select/Select.tsx

Fixes types so we can support the autocomplete attribute.

fix(select): corrects types

---

README.md
packages/palette/src/elements/Button/Button.story.tsx
packages/palette/src/elements/Dialog/Dialog.tsx
packages/palette/src/elements/HorizontalOverflow/HorizontalOverflow.story.tsx
packages/palette/src/elements/Modal/Modal.tsx
packages/palette/src/elements/Modal/ModalBase.story.tsx
packages/palette/src/elements/ModalDialog/ModalDialogContent.story.tsx
packages/palette/src/elements/ModalDialog/ModalDialogContent.tsx
packages/palette/src/elements/Pill/Pill.story.tsx
packages/palette/src/elements/Popover/Popover.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx
packages/palette/src/elements/Range/Range.story.tsx
packages/palette/src/elements/Skeleton/Skeleton.story.tsx
packages/palette/src/elements/Spacer/Spacer.story.tsx
packages/palette/src/elements/Spacer/Spacer.tsx
packages/palette/src/elements/StaticCountdownTimer/StaticCountdownTimer.tsx
packages/palette/src/elements/TextArea/TextArea.tsx
packages/palette/src/elements/Toasts/Toasts.tsx
packages/palette/src/themes/Themes.story.tsx

no more confusing `ml` and `mt` and `mx` and ..
<details>
<br />
```bash
npm install @artsy/palette-charts@26.0.0-canary.1232.25371.0
npm install @artsy/palette@27.0.0-canary.1232.25371.0
yarn add @artsy/palette-charts@26.0.0-canary.1232.25371.0
yarn add @artsy/palette@27.0.0-canary.1232.25371.0
```
</details>
To migrate to this version, replace the following props on`Spacer`:
- `mb`, `mt` with `y`.
- `ml`, `mr` with `x`.
- `my` with `y`. if in a flex context, double the value (`my={1}` becomes `y={2}`).
- `mx` with `x`. if in a flex context,double the value (`mx={1}` becomes `x={2}`).
- `m` with either `x` or `y`, figure out which one you need based on the case. if …

feat: Spacer uses `x`/`y` now

---

packages/palette/src/elements/Pointer/Pointer.tsx
packages/palette/src/elements/Pointer/index.ts
packages/palette/src/elements/Popover/Popover.story.tsx
packages/palette/src/elements/Popover/Popover.tsx
packages/palette/src/elements/Tooltip/Tooltip.story.tsx
packages/palette/src/elements/Tooltip/Tooltip.tsx
packages/palette/src/helpers/index.ts

* Removes `size` prop from `Tooltip`
* Removes `title` prop from `Popover`
* Adjusts padding in `Popover`
<details>
<br />
```bash
npm install @artsy/palette-charts@27.0.0-canary.1242.25654.0
npm install @artsy/palette@28.0.0-canary.1242.25654.0
yarn add @artsy/palette-charts@27.0.0-canary.1242.25654.0
yarn add @artsy/palette@28.0.0-canary.1242.25654.0
```
</details>

feat(popover/tooltip): variants and pointers

---

packages/palette/src/elements/Tooltip/Tooltip.story.tsx
packages/palette/src/elements/Tooltip/Tooltip.tsx

This component accepts `BoxProps` but we weren't doing anything with them.

fix(tooltip): spreads rest props

---

packages/palette/src/elements/Popover/Popover.tsx

Similar to `Dropdowns` we want to render the `Popover`s into a portal.
<details>
<br />
```bash
npm install @artsy/palette-charts@28.2.0-canary.1251.25893.0
npm install @artsy/palette@29.2.0-canary.1251.25893.0
yarn add @artsy/palette-charts@28.2.0-canary.1251.25893.0
yarn add @artsy/palette@29.2.0-canary.1251.25893.0
```
</details>

feat(popover): renders into a portal

---

packages/palette/src/elements/Popover/Popover.story.tsx
packages/palette/src/elements/Popover/Popover.tsx

Threads through the `z-index` to the positioned element rather than the panel.

fix(popover): threads through z-index to correct element

---

packages/palette/src/elements/Popover/Popover.tsx
packages/palette/src/elements/Tooltip/Tooltip.tsx

Minor fix: the `z-index` here was being duplicated in the `styled` declaration, which was taking precedence.

fix(popover,tooltip): fixes default z-index handling

---

packages/palette/src/elements/Popover/Popover.story.tsx
packages/palette/src/elements/Popover/Popover.tsx

Needed to support progressive onboarding, wherein these must be manually dismissed, or dismissed by taking the appropriate action.
<details>
<br />
```bash
npm install @artsy/palette-charts@28.5.0-canary.1259.26120.0
npm install @artsy/palette@29.5.0-canary.1259.26120.0
yarn add @artsy/palette-charts@28.5.0-canary.1259.26120.0
yarn add @artsy/palette@29.5.0-canary.1259.26120.0
```
</details>

feat(popover): supports optionally ignoring outside clicks

---

packages/palette/src/elements/Popover/Popover.story.tsx
packages/palette/src/elements/Popover/Popover.tsx

With the progressive onboarding we're kind of using these like tooltips with external triggers. This allows us to ignore the typical focus management the `Popover` does.

feat(popover): adds prop to disable focus management

---

packages/palette/package.json
packages/palette/src/elements/Modal/__tests__/ModalBase.test.tsx
packages/palette/src/utils/__tests__/useFocusLock.test.tsx
packages/palette/src/utils/useFocusLock.story.tsx
packages/palette/src/utils/useFocusLock.ts
yarn.lock

As it happens, determining whether or not an element can be focused [is non-trivial](https://github.com/focus-trap/tabbable/blob/master/src/index.js). My selector here was actually allowing for some disabled elements to occupy tab stops, which was causing some elements to retain focus for an extra tab. This pulls in the `tabbable` library which implements a more comprehensive method of determining focusability.

fix(usefocuslock): uses a more accurate method of determining focusable

---

packages/palette/package.json
packages/palette/src/elements/Modal/__tests__/ModalBase.test.tsx
packages/palette/src/utils/__tests__/useFocusLock.test.tsx
packages/palette/src/utils/useFocusLock.story.tsx
packages/palette/src/utils/useFocusLock.ts
yarn.lock

Reverts artsy/palette#1262
A complication: this correctly determines that disabled buttons aren't focusable; but the mutation observer isn't detecting when they change to enabled! Reverting while I investigate.

Revert "fix(usefocuslock): uses a more accurate method of determining focusable"

---

packages/palette/package.json
packages/palette/src/elements/Modal/__tests__/ModalBase.test.tsx
packages/palette/src/utils/__tests__/useFocusLock.test.tsx
packages/palette/src/utils/useFocusLock.story.tsx
packages/palette/src/utils/useFocusLock.ts
packages/palette/src/utils/useMutationObserver.ts
yarn.lock

Reverts artsy/palette#1266
Reverts and patches `useFocusLock` to properly observe `disabled` attribute changes.

Revert "Revert "fix(usefocuslock): uses a more accurate method of determining focusable""

---

packages/palette/package.json
packages/palette/src/elements/Modal/__tests__/ModalBase.test.tsx
packages/palette/src/utils/__tests__/useFocusLock.test.tsx
packages/palette/src/utils/useFocusLock.story.tsx
packages/palette/src/utils/useFocusLock.ts
packages/palette/src/utils/useMutationObserver.ts
yarn.lock

Reverts artsy/palette#1267
Sigh. It looks like this is manifesting some kind of issue where nothing is focusable. This is sporadic and only surfaced by Integrity. I think I'll just replace this with a library dedicated to focus locking instead of our own thing here.

Revert "Revert "Revert "fix(usefocuslock): uses a more accurate method of determining focusable"""

---

packages/palette/src/elements/Popover/Popover.story.tsx
packages/palette/src/elements/Popover/Popover.tsx

Supports adding buttons to dismiss popovers from inside themselves. As needed for progressive onboarding.
<details>
<br />
```bash
npm install @artsy/palette-charts@29.1.0-canary.1272.26566.0
npm install @artsy/palette@30.1.0-canary.1272.26566.0
yarn add @artsy/palette-charts@29.1.0-canary.1272.26566.0
yarn add @artsy/palette@30.1.0-canary.1272.26566.0
```
</details>

feat(popover): optionally passes actions to popover

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx

This PR adds `header` props to the `<AutoCompleteInput />` component.

feat: adding header to AutoCompleteInput component

---

packages/palette/src/elements/ReadMore/ReadMore.story.tsx
packages/palette/src/elements/ReadMore/ReadMore.tsx
packages/palette/src/elements/ReadMore/__tests__/ReadMore.test.tsx

Truncated content frequently features clickable links. The entire surface shouldn't be a button.

fix(readmore): corrects clickable areas in expanded state

---

packages/palette/src/elements/Expandable/Expandable.story.tsx
packages/palette/src/elements/Expandable/Expandable.tsx

Discovered a replication of [the `Expandable` inside of Force](https://github.com/artsy/force/blob/df14d993fdc5859d9dcc6cde5a64c5c8152ca249/src/Components/Artwork/SidebarExpandable.tsx#L22). After chatting with @mdole it seems it was added because this implementation didn't anticipate multi-line labels. That's all — this PR changes from `minHeight` to using top/bottom padding values, which better expresses the intent behind the Figma mock ups.

fix(expandable): better supports multi-line expandable headings

---

packages/palette/src/elements/Box/Box.story.tsx
packages/palette/src/elements/Box/Box.tsx

Due to conditional rendering in the artwork sidebar, proper support for `gap` would go a long way. This lets us implement a `Stack` and avoid problems with conditional rendering on `<Join separator={<Spacer y={1} />}>`

feat(box): supports gap

---

packages/palette/src/elements/Range/Range.tsx

Not a super critical piece of typing, this is a TS 4.0 feature that Volt doesn't have yet and it's causing some issues with the upgrade.

fix(range): removes labelled tuple for time being

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx

Follow-up for: https://github.com/artsy/palette/pull/1287
Previous PR caused an issue:

Fixes Types of property 'maxHeight' are incompatible for AutocompleteInput

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
packages/palette/src/utils/__tests__/usePosition.test.ts
packages/palette/src/utils/usePosition.ts

This addresses an issue that @MrSltun brought up wherein the new phone number input wherein filtering results wouldn't change the dropdown anchor point; so if the dropdown was flipped so that results were above it, filtering them would leave the dropdown anchored to the top.
Edit: I went with a simpler solution for heights: it appears that generally for the combobox pattern, adjusting the drawer size isn't necessarily desirable. Instead I've added support for responsive props and simplified the code somewhat.
<details>
<br />
```bash
npm install @artsy/palette-charts@32.1.1-canary.1298.27720.0
npm install @artsy/palette@33.1.1-canary.1298.27720.0
yarn add …
```

fix(autocompleteinput): adjusts height when filtering results

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx

Closes [GRO-1720](https://artsyproduct.atlassian.net/browse/GRO-1720)
A bit unintuitive but, to summarize:
When we click something in the header that isn't a button or link, the click will propagate down to the body and so focus leaves this element. Previously we were using that as an indication that the drawer should be closed. So what we do now to work around this is that on mouse down: flip a flag, and mouse up: reset it. This prevents the element from closing but we _still_ want to close it on actual clicks outside, so we use `useClickOutside` to handle those. Otherwise if you move focus out of the element by tabbing, we still close.
[GRO-1720]: https://artsyproduct.atlassian.net/browse/GRO-1720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …

fix(autocomplete): improves focus management for pointer devices

---

packages/palette/src/elements/ModalDialog/ModalDialogContent.tsx

BREAKING CHANGE: Removes top padding. Some workarounds apparently existed in the wild which will have to be removed.
This removes the top padding. I think this prop is a bit misguided to begin with and should probably be completely removed. I'm uncertain what the need for it was. I'm going publish a canary, see if I can remove it completely, otherwise remove the hacks and release as a breaking change.
<details>
<br />
```bash
npm install @artsy/palette-charts@33.0.0-canary.1302.28027.0
npm install @artsy/palette@34.0.0-canary.1302.28027.0
yarn add @artsy/palette-charts@33.0.0-canary.1302.28027.0
yarn add @artsy/palette@34.0.0-canary.1302.28027.0
```
</details>

fix(modaldialog): corrects padding with header

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx

Exposes a ref to the input so that we can programmatically focus it (`/` keypress for global search)

feat(autocompleteinput): exposes ref to the underlying input

---

packages/palette/src/elements/Range/Range.tsx

https://artsyproduct.atlassian.net/browse/ONYX-282
In a recent QA session for alerts functionality, Onyx noticed a visual glitch in the `Range` component that seems to affect only mobile Safari (😣)
Web (left) is fine but mWeb (right) shows an extraneous shadow with a hard, clipped edge.
Removing the `first-of-type` modifier and allowing both thumb sliders to get the `FLAT_SHADOW` style makes them consistent
---
After this change, I was concerned that the `Shadow` component placed to coincide with the max slider might need adjusting, but honestly we seem better off without it?
Looks way too heavy, and there is still some clipping apparent.
There is _still_ some clipping happening, but it is essentially unnoticeable unless you are zoomed af. (I.e. try to spot it in the **After** screenshot …

style(range): fix spurious shadows in mobile Safari

---

packages/palette/src/elements/Pill/Pill.story.tsx
packages/palette/src/elements/Pill/Pill.tsx
packages/palette/src/elements/Pill/tokens.ts
packages/palette/src/themes/Themes.story.tsx

We can alter these actual styles later if there turns out to be a Figma spec. For now this is fine. Breaking change because we're dropping the `artist` variant.

feat(pills): adds profile and gray variant; removes artist variant

---

packages/palette/src/elements/Range/Range.tsx

https://artsyproduct.atlassian.net/browse/ONYX-362
Addresses an issue where non-sensical artwork alerts are created, with a min value exactly equal to the max value. Apart from being nearly useless as alerts for collectors, this also confuses the data display for partners.
It seems to make sense to fix this at the library level since min=max is probably not terribly useful in any context?
**Bonus**: this brings the behavior in line with the corresponding component in Eigen.
`min` could exactly equal `max`.
`min` and  `max` are guaranteed to be separated by `step`

fix(range): prevent min from exactly equaling max

---

packages/palette/package.json

The goal of this PR is to make sure that Storybook runs without issues in our dev environments. I added a `NODE_OPTIONS` environment variable set to `--openssl-legacy-provider` in the Storybook start script to make Storybook compatible with Node version 16, addressing a known issue discussed internally. 
Related slack discussion [here](https://artsy.slack.com/archives/CP9P4KR35/p1696351565117019)

chore: add NODE_OPTIONS env var to storybook start script

---

packages/palette/src/elements/Pill/Pill.story.tsx
packages/palette/src/elements/Pill/Pill.tsx

This passes along the `ref` to `Pill` components so that they may be used with `Popover`.

fix(pill): forwards ref to pill

---

packages/palette/src/elements/Pill/Pill.tsx

The `selected` state can be stacked with the other states. As such the `filter` variant of `Pill` had an idle and selected state which were identical. This corrects that. We also add the x icon to the `gray` variant so that it matches it's larger version.

fix(pill): corrects x icon behavior

---

packages/palette/src/elements/Pill/tokens.ts

Selected state should not have a blue outline.

fix(pill): corrects selected state

---

packages/palette/src/elements/Pill/Pill.story.tsx
packages/palette/src/elements/Pill/Pill.tsx

Closes [DIA-215](https://artsyproduct.atlassian.net/browse/DIA-215)
To support quick filter anchors, we allow a right-side positioning of icons.
[DIA-215]: https://artsyproduct.atlassian.net/browse/DIA-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(pill): supports right side icon positioning

---

packages/palette/src/elements/Select/Select.story.tsx
packages/palette/src/elements/Select/Select.tsx
packages/palette/src/elements/Select/tokens.ts

This PR resolves [EMI-1373]
> [!IMPORTANT]
> This PR will be merged to #1250 
This PR solves the issue with `:has` pseudo-class [not being supported by Firefox](https://caniuse.com/css-has) by applying the styles using JS instead of CSS selectors
|---|---|
| <video src="https://github.com/artsy/palette/assets/20655703/221a35af-56c4-4d3a-9974-c78d18e0ddc0" /> | <video src="https://github.com/artsy/palette/assets/20655703/5c8d3399-77fd-463c-9e9b-a2d938ebd66f" /> |
[EMI-1373]: https://artsyproduct.atlassian.net/browse/EMI-1373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-1373): Fix Select issues with Firefox

---

packages/palette/src/elements/MultiSelect/MultiSelect.tsx
packages/palette/src/elements/MultiSelect/tokens.ts
packages/palette/src/elements/Select/Select.tsx

> [!IMPORTANT]
> This PR will be merged to #1250 
This PR fixes a small issue with the text behind the label showing on hover for `Select` and the name in `MultiSelect`
| | Before | After |
|---|---|---|
| Select | <img width="740" alt="image" src="https://github.com/artsy/palette/assets/20655703/a8ab90a8-2974-45c3-bc0d-92b64c769256"> | <img width="742" alt="image" src="https://github.com/artsy/palette/assets/20655703/e80d855c-ca24-4c08-8945-67c20a89128a"> |
| MultiSelect | <img width="740" alt="image" src="https://github.com/artsy/palette/assets/20655703/55939da3-1089-4126-8059-5a516fcf1358"> | <img width="741" alt="image" src="https://github.com/artsy/palette/assets/20655703/a36895fb-8d60-4784-a494-d3d5aa2f71a6"> |

fix: Hide placeholder text for select elements

---

packages/palette/src/elements/Select/Select.tsx

> [!IMPORTANT]
> This PR will be merged to #1250 
This PR adds a handler for `value` and `onChange` props to Select
> [!NOTE]
> Not having a handler for onChange overrides the one we have and blocks the `:has` polyfills for Firefox

fix: Add `value` & `onChange` to Select

---

packages/palette/src/elements/Tooltip/Tooltip.story.tsx
packages/palette/src/utils/useMutationObserver.ts
packages/palette/src/utils/usePosition.ts
packages/palette/src/utils/useResizeObserver.ts

Closes [DIA-240](https://artsyproduct.atlassian.net/browse/DIA-240)
While although I cannot replicate a crash, no matter how many objects appear on page. I was seeing significant frame drops when resizing the window prior to this change, starting at around 3000 instances.
That said: obviously hundreds or thousands of components should never be in the DOM period and we should virtualize that list anyway. But, this should help.
[DIA-240]: https://artsyproduct.atlassian.net/browse/DIA-240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dia-240): optimize tooltip when inactive

---

packages/palette/src/elements/Button/Button.tsx

Surprised this never came up. With the `Pill`s we offset the icons so that the padding doesn't look visually off balance. We should do the same on `Button`
| --- | --- |
| <img src="https://static.damonzucconi.com/_capture/ruI341XBHGzV6XN8f9ZAyR0VZ5AKxxmF1Mvntzo0vlnYSWjPtlc4JDiPfQU6bDCS7jSPLM8RbXH9SfDWXX1LJQMtcL2ok62DwPTe.png"> | <img src="https://static.damonzucconi.com/_capture/jPTiYAWjCQo8l6ErLLRv4mBf8ukQ2uM8Nf6SVfCwJlSfJ90PnZtd5QKya9OZPCoZw7aFZkPy6XKBDlr5R1DeBORoapfKmy5aQ3eu.png"> |

fix(button): offsets icon for padding balance

---

packages/palette/src/elements/Input/Input.tsx
packages/palette/src/elements/MultiSelect/MultiSelect.tsx
packages/palette/src/elements/Select/Select.tsx
packages/palette/src/elements/TextArea/TextArea.tsx

This PR resolves [EMI-1560]
This PR adds a margin-top to the input elements when the `title` is present to prevent the title from overlapping on other elements
| | Before | After |
|---|---|---|
| Input | <video src="https://github.com/artsy/palette/assets/20655703/4232fcf4-b6e6-4682-91fc-2ad601657e3b" /> | <video src="https://github.com/artsy/palette/assets/20655703/50168f9e-6932-46f5-b866-5df04a47138f" /> |
| TextArea | <img width="721" alt="image" src="https://github.com/artsy/palette/assets/20655703/cebe8eaa-0b0b-4e5c-bed1-910112880d12"> | <img width="719" alt="image" src="https://github.com/artsy/palette/assets/20655703/3b87351a-c88a-4c3c-8467-bdbda3e8d379"> |
| Select | <img width="726" alt="image" src="https://github.com/artsy/palette/assets/20655703/0e669393-7673-4c65-bf6a-6d71f875 …

fix(EMI-1560): Add margin-top to elements when the title is present

---

packages/palette/src/elements/Input/Input.tsx
packages/palette/src/elements/MultiSelect/MultiSelect.tsx
packages/palette/src/elements/PhoneInput/PhoneInput.tsx
packages/palette/src/elements/Select/Select.tsx
packages/palette/src/elements/TextArea/TextArea.tsx
packages/palette/src/shared/RequiredField.tsx

This PR resolves [EMI-1561]
This PR updates the color of the "* Required" text under the input elements to be `black30` to match the disabled colors of the borders and the label
| | Before | After |
|---|---|---|
| Input | <img width="712" alt="image" src="https://github.com/artsy/palette/assets/20655703/de7d0d7a-5f01-4609-8322-032a53928d5d"> | <img width="713" alt="image" src="https://github.com/artsy/palette/assets/20655703/020f40bf-56b6-429b-a1e1-4a0f635c3acc"> |
| Select | <img width="712" alt="image" src="https://github.com/artsy/palette/assets/20655703/49ba2a42-d8d1-4d9e-9116-eb714edf7b52"> | <img width="709" alt="image" src="https://github.com/artsy/palette/assets/20655703/38f540df-8ad2-4606-ab4c-58252d7e9dc4"> |
| Phone Input | <img width="710" alt="image" …

fix(EMI-1561): Update "*required" color when the element is disabled

---

packages/palette/src/elements/Drawer/Drawer.tsx

I was expecting this to be more complicated but there's not much to this. I still think we could remove/append the whole thing from the DOM instead of it lying dormant but this _should_ work for our purposes. Will check it out with a canary.
<details>
<br />
```bash
npm install @artsy/palette-charts@36.0.1-canary.1335.29422.0
npm install @artsy/palette@37.0.1-canary.1335.29422.0
yarn add @artsy/palette-charts@36.0.1-canary.1335.29422.0
yarn add @artsy/palette@37.0.1-canary.1335.29422.0
```
</details>

fix(drawer): renders using portal

---

packages/palette/src/elements/Range/Range.story.tsx
packages/palette/src/elements/Range/Range.tsx

It's actually unclear to me how this differed from the ModalDialog which also uses a portal but: when we switched the `Drawer` to use a portal, the range was no longer initializing it's width correctly.

fix(range): correctly sets width when within drawer

---

packages/palette/src/elements/Pill/Pill.story.tsx
packages/palette/src/elements/Pill/Pill.tsx
packages/palette/src/elements/Pill/tokens.ts

Conversation thread: https://artsy.slack.com/archives/C05EQL4R5N0/p1701182070690769?thread_ts=1700759129.374419&cid=C05EQL4R5N0
This PR adds the `dotted` version of the Pill component. This comes as a request from design. 
The component is used here https://www.figma.com/file/lVbIxbnH2IUk1K1FoxyFHV/Filters-and-Alerts-redesign?type=design&node-id=273-47116&mode=dev
**Palette Guidelines** 
**Demo**
https://github.com/artsy/palette/assets/11945712/8c0256cf-3ffe-4b96-a177-4724909c24b8

chore: support dotted pill

---

packages/palette-tokens/src/typography/v3.ts

Adds the `xxs` variant to `Text`

feat(text): adds xxs tokens

---

packages/palette/src/elements/Checkbox/Checkbox.tsx

We were seeing some slightly confusing UX when checkboxes were the first element in dropdowns, as when focus moves to the dropdown, the first checkbox gets focused. This actually does feel much better to use with a pointer device now as the checkbox won't visibly retain focus.

fix(checkbox): moves focus state onto focus-visible

---

packages/palette/src/elements/Tooltip/Tooltip.story.tsx
packages/palette/src/utils/usePosition.ts

We noticed that on some pages with `Tooltip` components in right sidebars, we would see the tooltip dramatically positioned offscreen. @tam-kis noticed that by changing the immediate positioning context to relative we could contain it within the parent. I don't think this change has gone unnoticed for 3 months, so it's unclear what changed to trigger this bug. However we just need to skip positioning when the `Tooltip` is inactive, regardless.

fix(tooltip): correctly handles positioning edge case by skipping when inactive

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
packages/palette/src/elements/AutocompleteInput/__tests__/Autocomplete.test.tsx

PR that originated this issue: https://github.com/artsy/force/pull/13396
The problem is that when user presses on an option, in handleMouseDown function UI gets cleared (dropdown destroyed) after 100ms delay. If user keeps mouse pressed - dropdown UI is cleared before user releases the mouse button. But seems like router links (that are inside options) start handling redirect only after user releases mouse. But at this point of time there are no links in DOM, so redirects are not handled.
onClick will wait until user releases the mouse button, and only after that will clear UI.

fix: fixes long press on AutocompleteInputOption

---

packages/palette/scripts/yalc-sync-after-change

Noticed that when using `yarn local-palette-dev` things weren't properly updating in Force, and doing some investigation found https://github.com/wclr/yalc/issues/195. Seems like force's webpack cache was breaking things.

fix(yalc): Make sure yalc properly syncs changes to Force

---

packages/palette/src/elements/Dropdown/Dropdown.tsx

Closes [DIA-409](https://artsyproduct.atlassian.net/browse/DIA-409)
A bit of a subtle problem: we don't want to manage focus when using a dropdown with a pointer device, only when keyboard navigating.
An illustration of the behavior this PR implements, where `enabled` is referring to focus isolation.
https://github.com/artsy/palette/assets/112297/ea05292e-ad73-45a2-9ec6-a99175d15259
[DIA-409]: https://artsyproduct.atlassian.net/browse/DIA-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dropdown): only manage focus when keyboard navigating

---

packages/palette/src/elements/ReadMore/ReadMore.story.tsx
packages/palette/src/elements/ReadMore/ReadMore.tsx

Updates the `<ReadMore>` link with a new `inlineReadMoreLink` prop defaulting to true. We need this on some of the new private artworks designs:
https://github.com/artsy/palette/assets/236943/db09916a-ec6b-46dc-a52b-ced294aab86f
cc @artsy/amber-devs

feat(read-more): Add `inlineReadMoreLink` prop

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
packages/palette/src/elements/AutocompleteInput/__tests__/Autocomplete.test.tsx

https://artsyproduct.atlassian.net/browse/ONYX-779
This reverts commit 36cfa119503edf04189062d2bc2f29d76fba9752.
The short version:
- #1361 was the last step in a [sequence of fixes](https://artsy.slack.com/archives/C05EQL4R5N0/p1710338279935239?thread_ts=1710255056.226949&cid=C05EQL4R5N0) that attempted to workaround the non-<code>&lt;a&gt;</code>-like behavior of the navigational links in the global search dropdown in Force.
- The reverted PR addressed a real glitch, but at the cost of introducing a more common one that was discovered much later, so we are reverting it.
- We hope to fix this more fundamentally in Palette by allowing Autocomplete to render options as `<a>`'s when appropriate
---
**Demo** of Safari versions 14–17 (via Browserstack, testing against local Force using a …

fix: revert slow-click fix from 1361

---

packages/palette-tokens/src/themes/v3Dark.tsx
packages/palette/src/themes/Themes.story.tsx

I built a little story to display and tweak the theme color values along with contrast ratio and AA/AAA checks.
Then I used it to tweak some of the values and just eyeball some changes. Not super scientific or anything. Just going to get this to a reasonable place and hand off to design. Will publish some canaries to validate in Force. The blue is going to be tricky to get right.
<details>
<br />
```bash
npm install @artsy/palette-charts@37.7.2-canary.1376.30518.0
npm install @artsy/palette-tokens@6.0.1-canary.1376.30518.0
npm install @artsy/palette@38.7.2-canary.1376.30518.0
yarn add @artsy/palette-charts@37.7.2-canary.1376.30518.0
yarn add …
```

Tweaks dark theme

---

packages/palette/src/elements/Avatar/Avatar.story.tsx
packages/palette/src/elements/Avatar/Avatar.tsx

When you upload an avatar, Metaphysics will return an invalid URL — which is crazy — but this is a reasonable thing to do with errored images, regardless.

fix(avatar): hides broken image if avatar load fails

---

packages/palette/src/elements/Dropdown/Dropdown.story.tsx
packages/palette/src/elements/Dropdown/Dropdown.tsx

This just ensures that in cases where a dropdown might be taller than the screen, all content can still be accessed.
https://github.com/artsy/palette/assets/112297/dc25ba8b-f0bc-4ecd-9e2b-769cb5ceda2e

feat(dropdown): handles potentially overflowing content

---

packages/palette/src/elements/Cards/Card.tsx

This is supported/works, w/ a storybook entry - https://github.com/artsy/palette/blob/4f75e5bbea5cb5c9d70b54f044b82e342dede675/packages/palette/src/elements/Cards/Cards.story.tsx#L17 - but the typing wasn't right.

chore: allow null | undefined for image prop in Card

---

packages/palette/src/elements/ModalDialog/ModalDialog.story.tsx
packages/palette/src/elements/ModalDialog/ModalDialog.tsx

First step in removing the massive z-index: supporting one correctly via props.

fix(modaldialog): passes in z-index correctly

---

packages/palette/src/helpers/injectGlobalStyles.tsx

Highlighted text is problematic in dark mode. This PR sets a global selection color using themed values.

feat(theme): sets global selection color

---

packages/palette/src/elements/PhoneInput/PhoneInput.tsx
packages/palette/src/elements/PhoneInput/tokens.tsx

* Fixes for dark mode
* Fixes border color to align with spec

fix(phoneinput): fixes for dark mode

---

packages/palette-tokens/src/themes/v3.tsx
packages/palette-tokens/src/themes/v3Dark.tsx
packages/palette/src/elements/Message/Message.tsx

Improves contrast ratios. Re: dark mode Q/A
<details>
<br />
```bash
npm install @artsy/palette-charts@37.11.2-canary.1388.30720.0
npm install @artsy/palette-tokens@6.0.2-canary.1388.30720.0
npm install @artsy/palette@38.11.2-canary.1388.30720.0
yarn add @artsy/palette-charts@37.11.2-canary.1388.30720.0
yarn add @artsy/palette-tokens@6.0.2-canary.1388.30720.0
yarn add @artsy/palette@38.11.2-canary.1388.30720.0
```
</details>

fix: improves contrast ratio of black60 in dark mode; default message variant

---

packages/palette/src/elements/Modal/ModalBase.story.tsx
packages/palette/src/elements/ModalDialog/ModalDialogContent.tsx

We can safely drop [the focus-visible polyfill](https://caniuse.com/?search=focus-visible) now. Very minor handling here being switched to the pseudo class.

fix: drops minor focus-visible polyfill handling

---

packages/palette/.eslintrc.js
packages/palette/package.json
packages/palette/src/elements/FilterSelect/Components/FilterSelectContext.tsx
packages/palette/src/elements/FilterSelect/FilterSelect.tsx
packages/palette/src/themes/Themes.story.tsx
yarn.lock

Re: [DIA-790](https://artsyproduct.atlassian.net/browse/DIA-790)
lodash is currently 16% of palette's size.
[es-toolkit](https://es-toolkit.slash.page/) is a replacement for lodash that is [much smaller](https://es-toolkit.slash.page/bundle-size.html).
We shouldn't be importing all of lodash for a few utility functions.
We should attempt [to do this in Force](https://es-toolkit.slash.page/compatibility.html) as well. Thoughts?
[DIA-790]: https://artsyproduct.atlassian.net/browse/DIA-790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: replaces lodash with es-toolkit

---

packages/palette/src/helpers/injectGlobalStyles.tsx

We're removing the [focus-visible polyfill from force](https://github.com/artsy/force/blob/main/src/Components/FocusVisible.tsx), where this styling was previously defined.

fix: moves focus-visible styling into global styles

---

packages/palette/src/elements/ModalDialog/ModalDialogContent.story.tsx
packages/palette/src/elements/ModalDialog/ModalDialogContent.tsx

New auth dialog has an unusual title section wherein a back button gets displayed. This PR adds support for passing in a fully custom title area.

feat(modaldialog): supports fully custom title components

---

packages/palette/src/elements/ModalDialog/ModalDialog.story.tsx
packages/palette/src/elements/ModalDialog/ModalDialog.tsx

`ModalBaseProps` was extending a base HTML element's title prop, which was interfering here.

fix(modaldialog): corrects type for title

---

packages/palette-tokens/src/themes/v3.tsx

Resolves [Figma comment](https://www.figma.com/design/UyNOc2vz3bf9k6Cw2itqwd/Home-Feed-(App)?node-id=0-1&node-type=canvas&t=92ePCBF66k3VotOH-0)
This updates the colors `red100` and `red10` to match the color in the [design system](https://www.figma.com/design/gZNkyqLT8AU3T61tluVJyB/Artsy-3.1-Design-System?node-id=6726-1370&node-type=text&m=dev).

fix: Update color red100 and red10

---

packages/palette/src/elements/StackableBorderBox/StackableBorderBox.story.tsx
packages/palette/src/elements/StackableBorderBox/StackableBorderBox.tsx

Noticed some strange issues inside of StackableBorderBox components. Needed to fix the css specifificity:
before / after:

fix(stackable-box): Fix css specificity on borders

---

packages/palette/src/elements/Input/Input.story.tsx
packages/palette/src/elements/Input/Input.tsx

It looks like there were some specificity changes with styled components 6 and certain elements could no longer be targeted without an `&`. This fixes the placeholders in the inputs:
Before:
https://github.com/user-attachments/assets/83020796-cd89-45d5-bc1e-1432a58d0adb
After: 
https://github.com/user-attachments/assets/38216faf-6ca4-4259-adbc-766b0f622612

fix(input): Fix placeholder visibility

---

packages/palette/src/elements/TextArea/TextArea.tsx

Similar to #1405, this fixes the placeholders in the textarea:
Before:
https://github.com/user-attachments/assets/3a3736b1-84d1-40a0-982f-dcaa9e9ccb15
After:
https://github.com/user-attachments/assets/c16032a4-cd37-4945-8b93-15e803c94f0b

fix(textarea): Fix placeholder visibility

---

packages/palette/src/elements/Dropdown/Dropdown.story.tsx
packages/palette/src/elements/Dropdown/Dropdown.tsx

After investigating the issue, I identified that when implemented in Force, the focus states have increased visibility. This was causing a flickering effect when the mouse exited because the pointer status and visibility weren't properly synchronized, which triggered the focus isolation. The fix simply maintains synchronization between these two states to resolve the issue.
<details>
<br />
```bash
npm install @artsy/palette-charts@38.0.5-canary.1411.31331.0
npm install @artsy/palette@39.0.5-canary.1411.31331.0
yarn add @artsy/palette-charts@38.0.5-canary.1411.31331.0
yarn add @artsy/palette@39.0.5-canary.1411.31331.0
```
</details>

fix(dropdown): keeps pointer state in sync with visibility

---

packages/palette-tokens/src/themes/v3.tsx
packages/palette-tokens/src/themes/v3Dark.tsx

https://artsyproduct.atlassian.net/browse/ONYX-1462
Introduces `red50` as a new color intended for urgency/importance indicators, and adjusts `red100` accordingly.
From [Figma](https://www.figma.com/design/zRKGxOWHhq3kcNiNAZCig3/OtH-App%3A-Alerts-and-Activity?node-id=334-23331&m=dev):
<table>
<tr valign="top"><th>Before</th><th>After</th></tr>
<tr valign="top"><td><img width=400 src="https://github.com/user-attachments/assets/4bb9b959-cad4-4cd2-9a39-cfeb5c387e87" /></td><td><img width=400 src="https://github.com/user-attachments/assets/2beaccfb-3a74-4a38-a85c-ff42ea9c3464" /></td></tr>
</table>
**Light mode**: I've kept the colors as spec'd in the Figma.
**Dark mode**: I've improvised with https://webaim.org/resources/contrastchecker (similar to what @dzucconi did in …

feat: adjust and expand red palette

---

packages/palette-charts/package.json

All of these deps will certainly be installed in whatever consuming app so lets move them to peerDeps. Caught this via 
https://app.relative-ci.com/projects/zNeNymVCPwxxOLTcM9qt/jobs/1330-55dq9GnCGbFfs0QVh1uZ/packages?bp=%7B%22filters%22%3A%22changed-1_duplicate-1%22%7D&dt=table&dtg=

chore: Move shared deps to peerDeps

---

packages/palette/package.json

Due to some breakage in our release pipeline I made a semi-manual release of `@artsy/palette@40.3.0`
See [thread](https://artsy.slack.com/archives/C2TQ4PT8R/p1738253121649049)

chore: bump @artsy/palette to v40.3.0

---

packages/palette/src/elements/Dropdown/Dropdown.tsx

When working on something with some z-index complexity I noticed that there was no way to position the dropdown above something that has `position: relative` with a zIndex, because the assigned zIndex is always 1. 
<details>
<br />
```bash
npm install @artsy/palette-charts@39.4.0-canary.1420.31535.0
npm install @artsy/palette@40.5.0-canary.1420.31535.0
yarn add @artsy/palette-charts@39.4.0-canary.1420.31535.0
yarn add @artsy/palette@40.5.0-canary.1420.31535.0
```
</details>

feat(dropdown): ability to assign zIndex to dropdown

---

packages/palette-tokens/src/themes/v3.tsx
packages/palette-tokens/src/themes/v3Dark.tsx

This PR comes as a follow-up to the new design colour (black 90).
Please note, this colour will only be used as a background colour for dark mode and won't be used for light mode.
<details>
<br />
```bash
npm install @artsy/palette-charts@39.5.0-canary.1421.31561.0
npm install @artsy/palette-tokens@6.3.0-canary.1421.31561.0
npm install @artsy/palette@40.6.0-canary.1421.31561.0
yarn add @artsy/palette-charts@39.5.0-canary.1421.31561.0
yarn add @artsy/palette-tokens@6.3.0-canary.1421.31561.0
yarn add @artsy/palette@40.6.0-canary.1421.31561.0
```
</details>

chore: add black90

---

packages/palette/src/elements/Stepper/Stepper.tsx
packages/palette/src/elements/Tabs/Tabs.story.tsx
packages/palette/src/elements/Tabs/Tabs.tsx

The `Tabs` component was using a ref to cache the active tab content in an attempt to prevent re-rendering. This caching mechanism was causing issues with form inputs within tab content, as their state updates weren't being reflected properly.
Removed the `activeTab` ref and now directly render the active tab content using `tabs[activeTabIndex].child`. This maintains all existing functionality (tab switching, scrolling, etc.) while ensuring proper state updates for form inputs and other interactive elements within tab content. All stories still pass.

fix(tabs): prevents stale rendering of tabs

---

packages/palette-charts/package.json
packages/palette/package.json
yarn.lock

Just noticed this in the yarn.lock output in Forque. This is of no consequence since it wasn't imported anywhere, but it just removes this dependency completely.

chore: removes no longer needed dep

---

packages/palette-tokens/src/themes/v3Dark.tsx

Addresses [ONYX-1635]
This updates the v3Dark color `blue10`. It's currently very light, and it's unclear to me why it was updated (https://github.com/artsy/palette/pull/1421/files). Light colors should be very dark within `v3Dark`.
**Mobile-pallete's Message component**
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-04-09 at 15 51 14](https://github.com/user-attachments/assets/40452d7b-91b1-4f65-9e8c-7ff9abfd2b05) | ![Simulator Screenshot - iPhone 16 - 2025-04-09 at 15 50 52](https://github.com/user-attachments/assets/f1584046-e19b-4f48-9f18-6e0daa822819)|
[ONYX-1635]: https://artsyproduct.atlassian.net/browse/ONYX-1635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Update v3Dark blue10

---

packages/palette-tokens/src/themes/v3Dark.tsx

Addresses [ONYX-1635]
* [Figma Design](https://www.figma.com/design/gZNkyqLT8AU3T61tluVJyB/Design-System-Foundations-3.1?node-id=18332-8584&m=dev)
This updates the v3Dark colors `black60` & `black30` to match this  [Figma Design](https://www.figma.com/design/gZNkyqLT8AU3T61tluVJyB/Design-System-Foundations-3.1?node-id=18332-8584&m=dev).
**Before:**
**After:**
**black60:**
**black30:**
[ONYX-1635]: https://artsyproduct.atlassian.net/browse/ONYX-1635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Update v3Dark black60 and black30

---

README.md

This updates the local development docs to use `yarn lerna` instead of `lerna` (which didn't work).

chore: Update local development docs to use `yarn lerna` instead of `lerna`

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
packages/palette/src/utils/usePosition.ts

It seems that Safari's rendering engine has slightly different timings. When rendering an autocomplete with autofocus it the positioning code ran before Safari has finished calculating the element's dimensions and position. This change ensures all layout calculations are complete.

fix(dia-1305): fixes initial autocomplete render in safari

---

packages/palette/src/elements/Avatar/Avatar.story.tsx
packages/palette/src/elements/Avatar/Avatar.tsx

If an avatar is in the same container as some element that doesn't shrink it will shrink/deform. It should always remain a circle and the same size. Text should be adjusted to accommodate/shrink (Will open a corresponding Force PR)

fix(avatar): prevents avatar from deforming

---

packages/palette/src/elements/Image/Image.story.tsx
packages/palette/src/elements/Image/Image.tsx

<del>Let's see if this locates any other collapsing images. Seems like a reasonable change for the type.</del>
If you're lazy loading you've got a block level container anyway so we just fallback to 100% for width and height.
<details>
<br />
```bash
npm install @artsy/palette-charts@40.1.2-canary.1439.31919.0
npm install @artsy/palette@41.1.2-canary.1439.31919.0
yarn add @artsy/palette-charts@40.1.2-canary.1439.31919.0
yarn add @artsy/palette@41.1.2-canary.1439.31919.0
```
</details>

fix(image): prevents image collapse when lazyload without geometry

---

packages/palette/src/elements/MultiSelect/MultiSelect.tsx

Resolves https://artsy.slack.com/archives/C9XJKPY9W/p1746542983418539
Display selected options on MultiSelect.
| --- | --- |
|<img width="425" alt="Bildschirmfoto 2025-05-07 um 16 14 28" src="https://github.com/user-attachments/assets/94dc91eb-115c-4725-bb4a-73c591852e49" /> | <img width="360" alt="Bildschirmfoto 2025-05-07 um 16 13 06" src="https://github.com/user-attachments/assets/54adff77-1ac7-4815-a881-0b798719c066" />|

feat: Display selected options on MultiSelect

---

packages/palette/src/elements/MultiSelect/MultiSelect.tsx
packages/palette/src/elements/MultiSelect/__tests__/MultiSelect.test.tsx

This PR adds `selected`, `onFocus`, and `onBlur` to `MultiSelect`. These updates are needed to use the component in a batch edit artwork table in Volt.

feat: Add selected onFocus and onBlur props to MultiSelect

---

packages/palette/src/elements/MultiSelect/MultiSelect.tsx

This PR fixes the issue of checking whether `MultiSelect` items are selected by comparing their values instead of object references.
When comparing object references to determine if an item is selected, any changes to the items in `options` (which are objects) will cause the check to fail, making all items appear unselected.

fix: MultiSelect selected items check

---

packages/palette/src/elements/MultiSelect/MultiSelect.tsx

This adds an `isVisible` prop to `MultiSelect` to open the options dropdown immediately upon rendering.

feat: Add autoOpen prop to MultiSelect

---

packages/palette/src/elements/Drawer/Drawer.tsx

Set Drawer `transform` to `none` when it's opened to make fixed elements work inside (e.g. AutocompleteInput).
[The uncanny relationship between position fixed and transform property](https://dev.to/salilnaik/the-uncanny-relationship-between-position-fixed-and-transform-property-32f6)

fix: Set Drawer `transform` to `none` when opened for fixed children

---

packages/palette-tokens/src/themes/v3Dark.tsx
packages/palette/.storybook/preview.js
packages/palette/src/Theme.tsx

Currently noticeable on [the shows page](https://www.artsy.net/shows). Updates the effect to match the background color.
Added a theme toggle to the global Storybook so this sort of thing is easier to debug.

fix(dia-1351): update palettes themed effects to match the lighter dark mode foreground color

---

packages/palette/src/elements/Dropdown/Dropdown.story.tsx
packages/palette/src/elements/Dropdown/Dropdown.tsx

* sets the default placement to `bottom` — it is a drop*down* after all
* ensures the transition works in all cases
* prevents the `FocusOn` div from getting styled which was causing a small grey box in the top left corner of all dropdowns
cc @artsy/diamond-devs

fix(dia-1404): dropdown fixes

---

packages/palette-tokens/src/themes/v3.tsx

`themeGet` doesn't work for this key. So, rather than having to do:
```
${({ theme }) => theme.space["0.5"]};
```
Let's just alias the value here.
cc @artsy/diamond-devs

feat(tokens): alias for half value
