artsy/palette

.vscode/settings.json
README.md
package.json
src/Theme.tsx
src/elements/Typography.tsx
src/index.tsx
tslint.json
yarn.lock

Updates package with `conventional-changelog-ember` which mirrors Reaction, as well as Reaction's `tslint.json` config.

Add ember sem-release config; tslint

---

package.json

[FEATURE semanticRelease] Remove --declaration for now

---

src/elements/Typography.tsx
src/palette.d.ts

Move types to d.ts file for consumers

[PATCH types] Move to palette.d.ts file

---

src/Theme.tsx

Removed text color (as per Brian's suggestion)

Remove text color

---

src/Theme.tsx

[Patch moreCSS] Ability to pass global CSS

---

src/Theme.tsx

[PATCH theme] Consolidate BP values

---

.babelrc
package.json
src/elements/Typography.tsx
src/platform/primitives.ios.ts
src/platform/primitives.ts
tsconfig.json
yarn.lock

Add .babelrc so that that consumers know how to consume and toolchains match up

[PATCH modules] Add babel to sync up toolchain

---

src/Theme.tsx

* adds JSDoc mostly everywhere, with the aim being that you're a client dev who doesn't have it all memorized
* **Removes** breakpoints that aren't directly in the notion doc ( I poked @zephraph about this, but @damassi you might wanna weigh in, thus you being the assignee )

Adds JSDocs to the exported palette

---

src/elements/Typography.tsx

Semi colons were in a bad way... I think this resolves the issues.

Fix annoying semicolon error

---

package.json

Removes a styled-systems cleanup artifact that was causing the deploy to fail.

[FIX build] Remove script that was causing release process to fail

---

yarn.lock

Also coordinating an update in reaction.

Update styled-system types

---

package.json

Fixes multiple instances of `styled-components`

[PATCH dev] move styled-components to devDeps

---

package.json
src/Theme.tsx
src/index.tsx
yarn.lock

Moving it over to `<Boot>` in Reaction

[PATCH grid] Remove from lib

---

yarn.lock

The work that was done in #39 can't be used until our TS version is _at least_ 2.9.

Update typescript to 2.9

---

.circleci/config.yml

Update CI so it actually deploys...

[PATCH release] Update CI to use npm deploy context

---

src/elements/Typography.tsx

Adds ability to override typography props via `style`.

[FEATURE typography] Add `style` prop to interface

---

src/Theme.tsx

Removes grid padding in favor of setting in Reaction

[PATCH grid] Remove grid padding

---

src/Theme.tsx

https://artsy.slack.com/archives/C2TQ4PT8R/p1534966253000100
Tested against reaction:

Update theme to supply breakpoints to styled-system

---

package.json
yarn.lock

Downgrade https://github.com/artsy/palette/pull/69 until Emission is fixed.

[PATCH lib] Revert ts to 3.0.1

---

docs/Box.mdx
docs/Flex.mdx
docs/Join.mdx
docs/Message.mdx
docs/Separator.mdx
docs/Spacer.mdx
docs/Typography.mdx
package.json
src/elements/Box.tsx
src/elements/Message.tsx
src/elements/index.tsx
src/helpers.ts
src/index.tsx
src/platform/primitives.ios.ts
src/platform/primitives.ts
yarn.lock

[FEATURE Message] Add Message element; organize exports; stub Docs

---

docs/Message.mdx

[PATCH docs] Fix text size

---

docs/Avatar.mdx
docs/Checkbox.mdx
docs/Spinner.mdx
src/elements/Spinner.tsx

Fixes docs so that subnav items appear correctly

[PATCH updateDocs] Fix subheadings

---

package.json
src/Theme.tsx
src/elements/BorderBox/BorderBox.tsx
src/elements/BorderBox/BorderBoxBase.tsx
src/elements/Message.tsx
src/elements/StackableBorderBox.tsx
src/platform/fonts/fontFamily.ts
src/platform/primitives.ios.ts
src/platform/primitives.ts
tsconfig.json
tslint.json
yarn.lock

Updates our dependencies to latest:
- `@types/react": "^16.4.13`
- `@types/styled-components": "^3.0.0`
- `@types/styled-system": "^3.0.3`
- `react": "^16.5.0`
- `react-dom": "^16.5.0`
- `styled-components": "^3.4.5`
- `styled-system: 3.0.3`
Corresponding PR: https://github.com/artsy/reaction/pull/1227

[PATCH deps] Update deps

---

src/elements/Button.tsx

Noticed text was wrapping at a small dimension

[PATCH button] Fix whitespace wrapping

---

docs/Avatar.mdx
src/elements/Avatar.tsx

To be used in designs like that: https://app.zeplin.io/project/5ac6790d7f57100518f9ab44/screen/5b606192307c780395c2b26e

[PATCH avatar] Add xsmall size

---

docs/Avatar.mdx
src/elements/Avatar.tsx

Follow up on https://github.com/artsy/palette/pull/88. Will need to update Force once this PR is in.
I believe Force is the only place Avatar is used for now, right?

[PATCH Avatar] - update to size names

---

src/elements/StackableBorderBox.tsx

Simple change so merging when green here.

[PATCH StackableBorderBox] Allow to overwrite default padding

---

docs/Avatar.mdx
src/elements/Avatar.tsx
src/elements/__tests__/Avatar.test.tsx

Also added some tests. Note that there's no formal spec for this yet, but wanted to account for various sizes in the text.

[FEATURE avatar] Add ability to display initials if no image provided

---

src/elements/Typography.tsx

Noticed that Text content was not filling parent component's full width, so added inherit prop

[PATCH Typography] added width inherit property to Text component

---

.github/ISSUE_TEMPLATE/component-spec.md

This adds a spec addition/update issue template to palette

Initial issue template

---

src/Theme.tsx

[PATCH typography] Add new Sans "0" font size

---

src/elements/Avatar.tsx
src/platform/primitives.ios.ts
src/platform/primitives.ts

Fix universal Image component. See https://github.com/artsy/palette/issues/104

[FIX Avatar] Fix universal component implementation

---

src/elements/Typography/Typography.tsx

Revert "[PATCH Typography] added width inherit property to Text component"

---

src/elements/Link/Link.tsx

I believe we need a release to actually use it anywhere

[FEATURE link] Trigger release

---

docs/Banner.mdx
src/elements/Banner/Banner.test.tsx
src/elements/Banner/Banner.tsx
yarn.lock

- Adds backgroundColor to banner component for transitions
- Possibly needs some animation added as well, need to check with design team

[PATCH banner] adds backgroundColor prop to Banner

---

docs/Avatar.mdx

Make it reflect actual property.

minor doc change

---

.autorc
package.json
yarn.lock

Fixes an issue with trivial changes deploying anyway.

Update auto-release to v2

---

src/helpers/index.ts

Add missing export from https://github.com/artsy/palette/pull/158

[Helper] Add missing export

---

src/svgs/index.tsx

Add missing Icon export

---

src/svgs/LockIcon.tsx

Relocated icon used a default export

Fix icon default export

---

package.json
src/svgs/LockIcon.tsx
yarn.lock

Upgrades husky and lint staged to latest

[Lib] Upgrade husky

---

src/elements/Tabs/Tabs.tsx

Make Tabs export name more descriptive

Make Tabs export name more descriptive

---

doczrc.js
www/package.json
www/src/components/StatusBadge.tsx
www/src/pages/index.tsx
www/src/pages/layout.tsx
www/yarn.lock

[Docs v2] Continue static layout

---

package.json
www/gatsby-config.js
www/package.json
www/src/components/Playground.tsx
www/static/admin/config.yml
www/yarn.lock
yarn.lock

Followed instructions here: 
https://www.gatsbyjs.org/docs/sourcing-from-netlify-cms/
See: https://www.netlifycms.org/

Add barebones Netlify CMS

---

src/svgs/OpenEyeIcon.tsx

@mzikherman => [OpenEyeIcon] Convert one more SVG prop to camelcase

---

src/svgs/CheckIcon.tsx

minor (allowing to click on the check to deselect)

@mzikherman => [CheckIcon] Add onClick prop

---

.autorc
package.json
yarn.lock

Uses Arty's shared auto config instead of a project specific config.

Use shared autorc config

---

src/svgs/MoreIcon.tsx

Oops-- this started  throwing errors  when I imported this component into reaction.

Fix MoreIcon dom properties

---

src/elements/TextArea/TextArea.tsx

Make TextArea title and descrption ReactNodes so we can add links etc

---

src/elements/TextArea/TextArea.tsx

Tried to use it in reaction and the font was too small. Apparently we're supposed to select theme props like this 😅

fix textarea font rendering

---

www/gatsby-config.js
www/gatsby-ssr.js
www/package.json
www/src/components/Sidebar/NavState.tsx
www/src/components/Sidebar/index.tsx
www/src/layouts/DefaultLayout.tsx
www/yarn.lock

Fixes issue where location couldn't be inferred during first SSR pass, which would break subsequent deep linking once mounted on the client.

Fix SSR navigation

---

src/elements/Colors/Colors.tsx
www/content/docs/home/about.mdx
www/content/docs/home/index.mdx
www/gatsby-node.js
www/src/components/Sidebar/NavTree.tsx
www/src/components/Sidebar/index.tsx

When a nav is autoExpanded, hide toggle

Auto-expand home nav

---

www/package.json
www/yarn.lock

Bump to get the latest colors in

Bump palette

---

www/content/docs/elements/buttons/Button.mdx
www/content/docs/home/getting-started.mdx
www/content/docs/home/process.mdx
www/content/docs/index.mdx
www/content/docs/tokens/Color.mdx
www/content/docs/tokens/Grid.mdx
www/content/docs/tokens/Spacing.mdx
www/content/docs/tokens/Typography.mdx
www/package.json
www/src/Boot.tsx
www/src/components/ArtsyCodeTheme.tsx
www/src/components/Playground.tsx
www/yarn.lock

Cleanup playground behavior, add better language support

More polish / content

---

src/svgs/Icon.tsx
www/content/docs/elements/buttons/Link.mdx
www/content/docs/elements/dialogs/Banner.mdx
www/content/docs/elements/dialogs/DialogWindow.mdx
www/content/docs/elements/dialogs/Message.mdx
www/content/docs/elements/images/Avatar.mdx
www/content/docs/elements/images/Image.mdx
www/content/docs/elements/inputs/Checkbox.mdx
www/content/docs/elements/inputs/Input.mdx
www/content/docs/elements/inputs/RadioGroup.mdx
www/content/docs/elements/inputs/Select.mdx
www/content/docs/elements/inputs/Slider.mdx
www/content/docs/elements/inputs/Tooltip.mdx
www/content/docs/elements/navigation/Pagination.mdx
www/content/docs/elements/navigation/Stepper.mdx
www/content/docs/elements/navigation/Tabs.mdx
www/content/docs/tokens/Grid.mdx
www/src/components/Playground.jsx

Fill in more content

---

www/src/components/Sidebar/NavTree.tsx

Flip chevrons on nav

---

src/svgs/ClosedEyeIcon.tsx

Didn't like the missing defaults

[Icon] fix props

---

www/content/docs/components/EntityHeader.mdx
www/content/docs/elements/animation/index.mdx
www/content/docs/elements/dialogs/Banner.mdx
www/content/docs/elements/dialogs/DialogWindow.mdx
www/content/docs/elements/inputs/Input.mdx
www/content/docs/elements/inputs/QuickInput.mdx
www/content/docs/elements/layout/Collapse.mdx
www/content/docs/home/component-checklist.mdx
www/content/docs/home/getting-started.mdx
www/content/docs/home/process.mdx
www/content/docs/index.mdx
www/content/docs/tokens/Icons.mdx
www/content/docs/utilities/index.mdx
www/src/Boot.tsx
www/src/components/GlobalComponents.jsx
www/src/components/Sidebar/NavTree.tsx
www/src/components/Sidebar/index.tsx
www/src/components/StatusBadge.tsx
www/src/layouts/DefaultLayout.tsx
www/static/admin/config.js
www/static/admin/config.yml

Finishes up this list: https://github.com/artsy/palette/issues/279
@zephraph - i turned off the editorial flow for now. That thing is kinda whatevs for something like this where minor edits are often all that's needed. Let me know if you feel strongly about it.

Address Design QA

---

www/src/components/GlobalComponents.jsx

Back to black

---

www/package.json
www/src/Boot.tsx
www/src/layouts/DefaultLayout.tsx
www/yarn.lock

Paired with @damassi on updating the gatsby site to styled-components 4.0 and palette 3.0

moves www onto styled components 4

---

.babelrc
package.json
yarn.lock

Adds https://www.npmjs.com/package/babel-plugin-add-react-displayname so that we can get better inspectability in our DOM from consumer libs.

Add babel-plugin-add-react-displayname

---

www/content/docs/elements/buttons/Link.mdx

The Link color was not used properly in docs. Correcting that.

---

www/package.json
www/src/components/Sidebar/NavTree.tsx
www/yarn.lock

Noticed this nice little bit come across the Gatsby Newsletter: https://www.gatsbyjs.org/blog/2019-02-20-introducing-use-static-query/
Works as designed! 
(Next step is removing Unstated from the docs.)

Replace `StaticQuery` with Hooks / Upgrade gatsby@2.1.0

---

src/svgs/ClosedEyeIcon.tsx

Missed an optional size for an icon

Add optional size type

---

src/svgs/PageViewsIcon.tsx
src/svgs/index.tsx

[Icons] Add `Icon` to icon name

---

www/package.json
www/yarn.lock

Updates docs with latest icons

[Lib] Bump palette in docs

---

www/content/docs/tokens/Icons.mdx

Make docs icon columns consistent

---

www/package.json
www/yarn.lock

bump version of palette in docs

---

package.json

[ci setup] add repo info to package.json

---

packages/palette-docs/static/admin/config.js
packages/palette-docs/static/admin/config.yml

Corrects the path to our CMS resources

Correct CMS path to admin resources

---

packages/palette/src/elements/Box/Box.tsx

Adds `minHeight` to optional `<Box>` properties. 
#trivial

[Box] Add minHeight prop

---

packages/palette/src/elements/Radio/Radio.tsx

Tests for a fix in Reaction tests.

Fix debounce

---

packages/palette/src/elements/RadioGroup/RadioGroup.test.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.tsx

Adds a test for the new `deselectable` prop.

Add test to RadioGroup

---

packages/palette/src/svgs/NoImageIcon.tsx

Update viewBox of NoImageIcon to fix centering

---

packages/palette-docs/content/docs/elements/data-visualization/BarChart.mdx
packages/palette/src/elements/BarChart/Bar.tsx
packages/palette/src/elements/BarChart/BarChart.tsx

Paired on this with @lilyfromseattle 
https://artsyproduct.atlassian.net/browse/PURCHASE-968

[BarChart] Constrain highlight label position

---

packages/palette-docs/content/docs/elements/data-visualization/BarChart.mdx
packages/palette/src/elements/BarChart/Bar.tsx
packages/palette/src/elements/BarChart/BarChart.test.tsx
packages/palette/src/elements/BarChart/BarChart.tsx

Bar chart updated to accept an onClick that can open a url in a new tab

Update palette to allow clicking into the bars

---

packages/palette/src/elements/BarChart/Bar.tsx

exported BarBox in Bar.tsx for reaction PricingContext tests

exported BarBox for reaction tests

---

packages/palette/src/elements/BarChart/index.tsx

export Bar.tsx from index for reaction PricingContext tests

export Bar.tsx from index

---

packages/palette-docs/content/docs/elements/images/Avatar.mdx
packages/palette-docs/content/docs/elements/images/Image.mdx

Remove mixed content

---

packages/palette/src/elements/BarChart/Bar.tsx
packages/palette/src/elements/BarChart/BarChart.test.tsx
packages/palette/src/elements/BarChart/BarChart.tsx

Added optional onHover to the bars in the BarChart component. This change is necessary to support hover tracking for the pricing context histogram bars.

added onHover to barchart bars

---

packages/palette-docs/content/docs/tokens/Color.mdx
packages/palette-docs/src/components/GlobalComponents.jsx

Follow-up from [377](https://github.com/artsy/palette/pull/377)

fixes ColorComponent admin display and tweaks styling

---

packages/palette/package.json
yarn.lock

Reduce payload size by updating moment-timezone

---

packages/palette/src/elements/BarChart/Bar.tsx
packages/palette/src/elements/BarChart/BarChart.tsx

https://artsyproduct.atlassian.net/browse/PURCHASE-1011

Add triangle to highlighted bar on xs breakpoint

---

packages/palette/.storybook/addons.js
packages/palette/.storybook/config.js
packages/palette/package.json
yarn.lock

See https://github.com/artsy/reaction/pull/2348

[Toolchain] Add @storybook/viewport plugin

---

renovate.json

Stop spamming Luc with renovate assignees

---

renovate.json

I'm removing the new renovate setup being as it seems to not be working as expected.

Revert to old renovate setup

---

renovate.json

Reactive the lib workflow for testing

Use lib workflow

---

packages/palette/src/elements/PriceRange/PriceRange.tsx

- Passes `disabled` prop to Slider to update PriceRange filter color

Passes disabled to Slider

---

packages/palette/src/elements/LabeledRange/LabeledRange.tsx
packages/palette/src/elements/PriceRange/PriceRange.tsx
packages/palette/src/elements/Slider/Slider.tsx

- https://artsyproduct.atlassian.net/browse/DISCO-990

Updates slider disabled styling and allows for disabledText

---

packages/palette-docs/content/docs/elements/data-visualization/BarChart.mdx
packages/palette/src/elements/BarChart/Bar.tsx
packages/palette/src/elements/BarChart/BarChart.test.tsx
packages/palette/src/elements/BarChart/BarChart.tsx

Fixes [GALL-1645](https://artsyproduct.atlassian.net/browse/GALL-1645)

X Axis labels for bar chart

---

packages/palette/src/elements/Menu/Menu.tsx

Fixes a weird clipping issue and tunes up the shadow.
#trivial

[Menu] Fix drop shadow

---

packages/palette/src/elements/Link/Link.tsx

Follow-up to https://github.com/artsy/palette/pull/476; add `position` prop as well.
#trivial

[Link] Add styled-system position mixin

---

packages/palette/src/Theme.tsx

Testing some weirdness in Reaction...

[Debug] Test deploy

---

packages/palette/src/elements/Menu/Menu.tsx

Make the width of `<Menu>` configurable

[Menu] Make width adjustable

---

packages/palette/package.json
yarn.lock

- Removes `luxon` as a peer and dev dependency and moves it to a dependency

Moves luxon to dependency

---

README.md

- Adds list of repos consuming palette to readme

Adds repos consuming palette to readme

---

packages/palette-docs/content/docs/elements/data-visualization/BarChart.mdx
packages/palette/src/elements/Button/Button.ios.tsx

Fixes an import path error from https://github.com/artsy/palette/pull/515

Fix import path

---

README.md

This came up today, thought we should add it to the repo 👍

Adds note about Zeppelin plugin

---

packages/palette/src/elements/Button/Button.tsx

- Adds padding to `Button` small which should be `20px` not `10px`

Adds padding to small button

---

packages/palette/src/platform/fonts/fontFamily.ios.ts

Follow-up from https://github.com/artsy/emission/pull/1687 and https://github.com/artsy/Artsy-UIFonts/pull/12.

Updates iOS font names

---

packages/palette/src/svgs/ArrowRightIcon.ios.tsx

Turns out we also need this one for the iOS artwork view. 😄

Adds ArrowRightIcon.ios

---

packages/palette/src/svgs/CloseIcon.ios.tsx

Need this for the Artwork page carousel.

Add close icon ios version

---

packages/palette-docs/content/docs/elements/dialogs/Modal.mdx

Adds WIP to modal

---

packages/palette/src/elements/Button/Button.tsx

- `longestText` is no longer rendered unless the prop is passed to the `Button` component

Updates button to not always render longestText

---

packages/palette/src/elements/EntityHeader/EntityHeader.ios.tsx

- Fixes Buttons breaking the width of their container based on the hardcoded width. Now computes width from the view width.

PURCHASE-1361 Fixes button breaking viewport

---

packages/palette/src/elements/Modal/Modal.tsx

- Removes the `Modal` from the DOM unless it should be visible.

Doesn't render modal in DOM if it's offscreen

---

README.md

- Cleans up the `README.md` file slightly for more legibility.

Cleans up readme

---

packages/palette/src/elements/EntityHeader/EntityHeader.tsx

Adds an `onClick` prop. 
#trivial

[EntityHeader] Add onClick handler #trivial 

---

packages/palette/src/elements/EntityHeader/EntityHeader.tsx

Moves the interface to the right location

[EntityHeader] Fix interface definition #trivial 

---

packages/palette-docs/content/docs/elements/dialogs/Modal.mdx
packages/palette/src/elements/Modal/Modal.tsx

- Small css update to improve modal scroll

Small CSS adjustments to modal for scroll

---

packages/palette/src/elements/ReadMore/ReadMore.story.tsx
packages/palette/src/elements/ReadMore/ReadMore.tsx
packages/palette/src/elements/ReadMore/__tests__/ReadMore.test.tsx

Adds a `disabled` prop to `<ReadMore>` component. 
#trivial

[ReadMore] Add disabled prop

---

packages/palette/src/elements/PageLoader/PageLoader.tsx

Related: https://github.com/artsy/force/pull/4519, https://github.com/artsy/reaction/pull/2785
Some light cleanup and the ability to pass `style` and `className` props, for greater control from within Force.

[PageLoader] Cleanup

---

packages/palette/src/elements/Modal/Modal.tsx
packages/palette/src/elements/Modal/__tests__/Modal.test.tsx

- Only closes modal if the wrapper is clicked

[Modal] - Checks if wrapper is clicked before closing

---

packages/palette/src/elements/Modal/Modal.tsx

Catching up with the spec: https://app.zeplin.io/project/5acd19ff49a1429169c3128b/screen/5c75ad115c1db5628cc03c2a
Just making the padding 20px on mobile and doing some conditional formatting around the logo/title.

Final modal spacing fixes

---

packages/palette/src/elements/Button/Button.tsx

I think this will fix that issue over in Reaction.

@jonallured => [Button] Export shape of props

---

README.md

Same as force/reaction/readme. I also added a reference to our design friends as palette wouldn't be a thing without them. Thank you friends ❤️.

Add artsy footer

---

packages/palette/src/svgs/BellFillIcon.ios.tsx
packages/palette/src/svgs/BellIcon.ios.tsx

[PURCHASE-1492]
These are needed for the "Watch lot" artwork action in the new ios artwork page
[PURCHASE-1492]: https://artsyproduct.atlassian.net/browse/PURCHASE-1492

PURCHASE-1492: added BellFillIcon and BellIcon for ios

---

packages/palette/src/elements/BarChart/BarChart.story.tsx
packages/palette/src/elements/CSSGrid/CSSGrid.story.tsx
packages/palette/src/elements/DonutChart/DonutChart.story.tsx
packages/palette/src/elements/LineChart/LineChart.story.tsx
packages/palette/src/elements/Modal/Modal.story.tsx
packages/palette/src/elements/ProgressBar/ProgressBar.tsx

Update based on feedback from demo -- change to black, and 2px instead of 3. 
#trivial

[PreloadBar] Change to black and fix size #trivial

---

README.md

Just updating the point people list

Remove luc as pont person 😭

---

packages/palette-docs/content/docs/elements/dialogs/Dialog.mdx
packages/palette/src/elements/Dialog/Dialog.story.tsx
packages/palette/src/elements/Dialog/__tests__/Dialog.test.tsx
packages/palette/src/elements/Modal/Modal.story.tsx

This is just minor clean ups suggested on previous Dialog PR.

Minor clean up.

---

packages/palette/src/elements/Select/Select.tsx

Pretty much title. We want to have the ability to set maxWidth for some work on the /artworks page in Volt.

Add maxWidth to selects

---

packages/palette/src/elements/Tags/Tags.tsx

Though seems unrelated hoping this would fix reaction tests.
discussion here: https://artsy.slack.com/archives/CP9P4KR35/p1572374811199300

Removes extra fragment.

---

packages/palette/src/elements/Box/Box.tsx

I need it for volt layout. In general I think it's good if we try to stay consistent with supporting min/max if we support at least one. Takes some time to figure out why it's not taking max if it's taking min -:)

want the Box to support minWidth

---

packages/palette-docs/package.json
packages/palette/package.json
yarn.lock

Update typescript to 3.7+

---

packages/palette/package.json
yarn.lock

cc @pepopowitz 
After digging in more (and with proper linking) I've verified that the SSR issue is fixed in the beta version. I'm going to update us to this for now.

Fix SSR issue by updating image lazy loading lib

---

packages/palette-docs/content/docs/elements/dialogs/Banner.mdx

Banner was missing code snippets

Add code snippets to <Banner> docs

---

packages/palette/src/elements/Grid/Grid.tsx

Adds a configurable maxWidth prop to the grid.

[Grid] Add maxWidth prop

---

packages/palette/src/elements/BarChart/BarChart.story.tsx
packages/palette/src/elements/Dialog/Dialog.story.tsx
packages/palette/src/elements/DonutChart/DonutChart.story.tsx
packages/palette/src/elements/LineChart/LineChart.story.tsx
packages/palette/src/elements/Modal/Modal.story.tsx

Trying to see if I can get the spurious diff reviews to go away.

Adjusts Chromatic settings

---

packages/palette/src/elements/Modal/Modal.tsx

Update Modal to switch from Serif to Sans fontstyle for title text.
**Before**
**After**

Update Modal to use Sans title

---

packages/palette/src/elements/Avatar/Avatar.shared.tsx

In attempting to upgrade Eigen this surfaced in the specs.

Fixes avatars in React Native

---

packages/palette/package.json
yarn.lock

Just a quick dep bump to see if this fixes the bugs we're seeing, before I try to replace it.

Bumps react-lazy-load-image-component

---

packages/palette/package.json
packages/palette/src/elements/Text/Text.ios.tsx
packages/palette/src/elements/Text/Text.shared.tsx
packages/palette/src/elements/Text/Text.story.tsx
packages/palette/src/elements/Text/__tests__/Text.ios.test.tsx
packages/palette/src/elements/Text/tokens.ios.ts

[FX-2067] Implements Text.ios

---

packages/palette/.storybook/config.js

So this *also* seems to be creating issues.
https://github.com/storybookjs/storybook/issues/7379
Eigen appears to work once this is removed.
This isn't exactly a critical feature and this package wasn't even a specified dependency so I'm just removing.

Removes theme from config

---

packages/palette-docs/content/docs/elements/layout/Cards.mdx
packages/palette/src/elements/Cards/CardTag.shared.tsx
packages/palette/src/elements/Cards/CardTag.tsx
packages/palette/src/elements/Cards/SmallCard.ios.tsx
packages/palette/src/elements/Cards/SmallCard.tsx

To be able to work on GALL-2971 I need a small version of the card. For now only implementing that part so that I can use it in ViewingRoomsApp. (Small version)
I think design for all of those cards is here: https://www.figma.com/file/GrCeNUJbKpfZtgwHga64cC/Artsy-Viewing-Room-Entry-Points-Components?node-id=136%3A2022

[Part of GALL-2970] - adding a small card to web view

---

packages/palette/src/elements/BarChart/BarChart.story.tsx
packages/palette/src/elements/Cards/Cards.story.tsx

[chore] Prevents Chromatic spec diffs

---

packages/palette/src/elements/BarChart/BarChart.story.tsx

Hopefully this will fix these complaints
https://artsy.slack.com/archives/CP9P4KR35/p1594740540000900

Upping the diffThreshold a bit more for BarChart

---

packages/palette-docs/content/docs/elements/layout/Flex.mdx

My most important "code" change in 2020.

addinging some grammer :p

---

packages/palette-docs/content/docs/tokens/Typography.mdx

This is just the minimal fix to try to get the deploy working.

[palette-docs] Fixes mysterious error

---

packages/palette-docs/content/docs/home/getting-started.mdx
packages/palette-docs/content/docs/tokens/Typography.mdx
packages/palette-docs/gatsby-config.js
packages/palette-docs/src/components/GlobalComponents.jsx
packages/palette-docs/src/components/Table.tsx
packages/palette-docs/src/components/TextSpecification.tsx
packages/palette-docs/src/layouts/DefaultLayout.tsx

Improves Typography documentation

---

packages/palette-docs/content/docs/elements/inputs/SelectSmall.mdx

[Docs] Remove WIP from SelectSmall

---

packages/palette/src/elements/Carousel/Carousel.tsx
packages/palette/src/elements/Carousel/CarouselNavigation.tsx

Updates carousel arrow sizing and color

---

packages/palette/src/elements/Skeleton/Skeleton.story.tsx
packages/palette/src/elements/Skeleton/Skeleton.tsx

Prop was missing — small fix to pass it through.

Pass through done prop on SkeletonText

---

packages/palette/src/Theme.tsx

This is to help support the work in [[Web] Type Clean-up](https://www.notion.so/artsy/Web-Type-Clean-up-94cae3cc227243e2a44128b315e65046).
For legacy pages where we're still using Stylus, we'd like to migrate those to the new typographic treatments without having to convert them to React.
So: we need to expose the text variants as JSON that we can then load in Stylus files.
One of three ways:
* exposing these under the theme and therefore tokens.json [this PR]
* gluing them into the exported tokens object in the generate-tokens script
* exporting out a separate text.json file
Ultimately the Stylus helpers in force will look something like:
```styl
THEME = json('node_modules/@artsy/palette/dist/tokens.json', { hash: true })
// Access themed values
fontFamily(name)
value = THEME.fonts[name] …
```

Exposes text variants under theme

---

packages/palette/src/svgs/TriangleDownIcon.tsx

fix: All icon to be filled

---

.vscode/settings.json
packages/palette-docs/content/docs/elements/layout/GridColumn.mdx

This adds docs to the new `GridColumn` component.

docs: Add GridColumn docs

---

packages/palette-docs/content/docs/elements/layout/GridColumns.mdx

Updates GridColumns documentation

---

packages/palette/src/Theme.tsx
packages/palette/src/svgs/TriangleDownIcon.tsx

Adds with a new color, `blue100` (#0A1AB4)

feat: Add blue100 color

---

packages/palette-docs/content/docs/elements/images/Image.mdx
packages/palette/src/elements/Image/Image.tsx

Includes documentation on how to create a responsive image

---

packages/palette/src/elements/Text/Text.tsx
packages/palette/src/elements/Text/tokens.ts

fix: Fix type def

---

packages/palette-docs/content/docs/tokens/Color.mdx
packages/palette-tokens/src/index.ts
packages/palette/src/Theme.tsx

I know we're mid-transition to tokens (#818), but not having these new colors was blocking other work for me so I figured I could update in both places and we'd be good for now.
Will also put up a PR in Eigen for the same reason.
Slack context: https://artsy.slack.com/archives/C9XJKPY9W/p1605904957010300
Notion colors page: https://www.notion.so/artsy/Color-a0c24896daf8433d9409aee2146ac267

feat: update colors

---

packages/palette/src/helpers/injectGlobalStyles.tsx

Removes margins and list-style from list elements. This allows us to remove CSS from Force Novo.
Related to https://artsyproduct.atlassian.net/browse/PLATFORM-3029

Add global styles for lists

---

packages/palette/src/elements/Button/Button.story.tsx
packages/palette/src/elements/Button/Button.tsx

Minor thing here where the loading state wasn't taking precedence over hover; so you'd see the two states conflated.

fix(button): ensure loading styles take precedence over hover

---

packages/palette-tokens/src/helpers.ts
packages/palette-tokens/src/index.ts

Centralize some helpers in tokens

Centralize some of the minor helpers w/ type updates

---

packages/palette-tokens/src/index.ts

lowercase for better readability

---

packages/palette/src/elements/Checkbox/Checkbox.story.tsx

Checking in these stories as I'm about to make some changes to this component and would like to validate against the specs.

chore(checkbox): adds stories for checkbox

---

packages/palette/src/elements/EntityHeader/EntityHeader.story.tsx
packages/palette/src/elements/EntityHeader/EntityHeader.tsx
packages/palette/src/elements/Radio/Radio.story.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx

Closed https://github.com/artsy/palette/pull/867
I do not have the patience to attempt deal with the spec failures right now. I'm going to try to pull over the changes incrementally. Extremely frustrated with the differences between real-world testing and Enzyme.

Pulling over stories from radio button

---

packages/palette/src/Theme.tsx
packages/palette/src/elements/Button/Button.tsx
packages/palette/src/elements/Button/v2/Button.tsx
packages/palette/src/elements/Button/v3/Button.tsx
packages/palette/src/elements/Modal/__tests__/Modal.test.tsx

This should get the Force integration PRs (https://github.com/artsy/force/pull/7115) to pass

Avoids failing specs on unthemed components

---

packages/palette/src/elements/BaseTabs/BaseTab.story.tsx
packages/palette/src/elements/Stepper/Stepper.story.tsx
packages/palette/src/elements/Stepper/Stepper.tsx
packages/palette/src/elements/Swiper/Swiper.story.tsx
packages/palette/src/elements/Tabs/Tabs.story.tsx

Just checking in these stories (in particular Stepper's) so I have the visual diff to work with when I PR later today.

chore(stories): adds tabs/stepper stories

---

packages/palette/src/Theme.tsx
packages/palette/src/elements/BaseTabs/BaseTab.tsx
packages/palette/src/elements/BaseTabs/BaseTabs.story.tsx
packages/palette/src/elements/BaseTabs/BaseTabs.tsx
packages/palette/src/elements/BaseTabs/tokens/v2.tsx
packages/palette/src/elements/BaseTabs/tokens/v3.tsx
packages/palette/src/elements/Stepper/Stepper.story.tsx
packages/palette/src/elements/Stepper/Stepper.tsx
packages/palette/src/elements/Tabs/Tabs.tsx
packages/palette/src/themes/Themes.story.tsx

[v3] Tabs, Stepper

---

packages/palette/src/elements/Input/Input.story.tsx
packages/palette/src/elements/Input/__tests__/Input.test.tsx

chore(stories): checks in input stories

---

packages/palette/src/elements/Input/Input.story.tsx
packages/palette/src/elements/Input/Input.tsx
packages/palette/src/elements/Input/__tests__/Input.test.tsx
packages/palette/src/elements/Input/tokens/types.ts
packages/palette/src/elements/Input/tokens/v2.ts
packages/palette/src/elements/Input/tokens/v3.ts
packages/palette/src/elements/Select/Select.tsx
packages/palette/src/themes/Themes.story.tsx

[v3] Input

---

packages/palette/src/elements/Input/Input.story.tsx
packages/palette/src/elements/Input/Input.tsx

Fix for https://app.circleci.com/pipelines/github/artsy/force/12836/workflows/2342e29d-d042-48ff-a8a6-b8b40ece62a0/jobs/91313

fix(input): corrects input types

---

packages/palette/src/elements/Text/Text.story.tsx
packages/palette/src/elements/Text/Text.tsx
packages/palette/src/elements/Typography/Typography.tsx

The deprecation was long overdue. :)

Deprecates Sans/Serif; mixes in textTransform to Text

---

packages/palette/src/helpers/index.ts

Exports our shadow constants which can be used in https://github.com/artsy/force/pull/7211
cc @kiryl-zubarau

feat(helpers): exports shadow constants

---

packages/palette/src/elements/Input/Input.tsx
packages/palette/src/elements/LabeledInput/LabeledInput.tsx

feat(labeledinput): supports ref

---

packages/palette/src/elements/Checkbox/Check.story.tsx
packages/palette/src/elements/Checkbox/Check.tsx
packages/palette/src/elements/Checkbox/Checkbox.story.tsx
packages/palette/src/elements/Checkbox/Checkbox.tsx
packages/palette/src/elements/Checkbox/__tests__/Checkbox.test.tsx
packages/palette/src/elements/Checkbox/tokens/v2.ts
packages/palette/src/elements/Checkbox/tokens/v3.ts

<details>
<br />
```sh
npm install @artsy/palette@14.12.2-canary.897.16190.0
yarn add @artsy/palette@14.12.2-canary.897.16190.0
```
</details>

feat(checkbox): implements v3 styles

---

packages/palette/src/elements/Expandable/Expandable.story.tsx
packages/palette/src/elements/Expandable/Expandable.tsx

fix(expandable): box props should apply to entire component

---

packages/palette/src/elements/Button/v3/tokens.ts

Pulls in a few refinements that have been made recently.

fix(button): updates v3 button styling

---

packages/palette/src/elements/Pagination/Pagination.story.tsx
packages/palette/src/elements/Pagination/Pagination.tsx

* Designs say to use "Prev" (and this was previously "Prev")
* Some small a11y updates

fix(pagination): updates copy; adjusts aria

---

packages/palette/src/elements/Pagination/Pagination.story.tsx
packages/palette/src/elements/Pagination/Pagination.tsx

Broke the next/prev disabling in the refactor. Fixes.

fix(pagination): fixes last page error

---

packages/palette/src/elements/Pagination/Pagination.tsx

fix(pagination): removes extraneous padding

---

packages/palette/src/elements/Pagination/Pagination.story.tsx
packages/palette/src/elements/Pagination/Pagination.tsx
packages/palette/src/elements/Pagination/SmallPagination.tsx
packages/palette/src/elements/Pagination/__tests__/Pagination.test.tsx
packages/palette/src/elements/Pagination/__tests__/SmallPagination.test.tsx

fix(pagination): correctly disables next/prev

---

packages/palette/src/Theme.tsx

Planning on allowing the `AppShell` theme to be configured with a `theme` key and this makes things easy.

feat(theme): allows theme to be easily swapped

---

packages/palette/src/elements/GridColumns/index.ts

Exports `ColumnSpan` & `ColumnStart`

feat(types): exports ColumnSpan/Start type

---

packages/palette/src/elements/Expandable/Expandable.tsx

Closes [DSWGW-37](https://artsyproduct.atlassian.net/browse/DSWGW-37)

fix(expandable): bumps chevron over 10px in v3

---

packages/palette/src/elements/Shelf/Shelf.story.tsx

Updates stories to use `States` component

feat: Fix Shelf stories

---

packages/palette/src/elements/Image/Image.tsx

feat: [Image] add maxHeight props

---

packages/palette/src/elements/Avatar/Avatar.story.tsx
packages/palette/src/elements/Avatar/Avatar.test.tsx
packages/palette/src/elements/Avatar/Avatar.tsx
packages/palette/src/elements/Avatar/tokens.ts
packages/palette/src/elements/EntityHeader/EntityHeader.story.tsx
packages/palette/src/elements/EntityHeader/EntityHeader.tsx
packages/palette/src/elements/EntityHeader/v2/EntityHeader.tsx
packages/palette/src/elements/EntityHeader/v3/EntityHeader.tsx
packages/palette/src/elements/Spacer/Spacer.tsx

[v3] Supports EntityHeader, Avatar

---

packages/palette/src/elements/Select/Select.tsx

Closes: [DSWGW-40](https://artsyproduct.atlassian.net/browse/DSWGW-40)

fix(select): vertically centers label

---

packages/palette/src/elements/Shelf/Shelf.tsx

Closes: [DSWGW-59](https://artsyproduct.atlassian.net/browse/DSWGW-59)

fix(shelf): improves first page previous button navigation

---

packages/palette/src/elements/Shelf/Shelf.story.tsx
packages/palette/src/elements/Shelf/Shelf.tsx
packages/palette/src/elements/Shelf/ShelfScrollBar.tsx
packages/palette/src/elements/Shelf/__tests__/ShelfScrollBar.test.tsx
packages/palette/src/elements/Shelf/index.ts
packages/palette/src/elements/Shelf/useClickScroll.ts
packages/palette/src/elements/Shelf/useDragScroll.ts

This turned out to be not too bad to implement once I stopped looking at other people's code and just tried to intuitively code it. Let that be a lesson to myself.
<details>
<br />
```sh
npm install @artsy/palette@14.29.1-canary.935.17214.0
yarn add @artsy/palette@14.29.1-canary.935.17214.0
```
</details>

feat(shelf): implements custom scrollbar

---

packages/palette/package.json
packages/palette/src/elements/Shelf/Shelf.tsx
yarn.lock

-----
Snuck in minor update to use-cursor

fix(shelf): vertically centers arrows relative to rail

---

packages/palette/src/elements/Popover/Popover.tsx

fix(popover): skips focus management on initial mount

---

README.md

Remove me as point person

---

renovate.json

Sorry, I should've grouped this with #954, but I'm doing it through the web UI given that I've got a few repos to go through. 
Hi friends, hope you're well! 👋

Remove me from renovate.json

---

packages/palette/src/elements/ProgressDots/ProgressDots.story.tsx
packages/palette/src/elements/ProgressDots/ProgressDots.tsx
packages/palette/src/elements/ProgressDots/__tests__/ProgressDots.test.tsx

Adds click support to progress dots/dashes.

fix(progressdots): supports click

---

packages/palette/src/elements/Shelf/Shelf.story.tsx
packages/palette/src/elements/Shelf/Shelf.tsx
packages/palette/src/elements/Shelf/ShelfNavigation.tsx
packages/palette/src/elements/Shelf/index.ts

feat(shelf): exports shelf nav buttons; improves feedback

---

packages/palette/src/elements/Carousel/Carousel.tsx
packages/palette/src/elements/Swiper/Swiper.tsx

fix(swiper,carousel): loosens children type

---

packages/palette/package.json
yarn.lock

chore(chromatic): updates chromatic

---

packages/palette/.storybook/preview.js

This will reset all the Chromatic stories (which isn't blocking PRs at the moment (need to fix this next since it would have caught a bug I just merged))...

chore(storybook): changes default theme to v3

---

packages/palette/src/utils/useIsomorphicLayoutEffect.ts
packages/palette/src/utils/usePosition.ts

[Shout out](https://medium.com/@alexandereardon/uselayouteffect-and-ssr-192986cdcf7a)

fix(useposition): silences uselayouteffect ssr warning

---

.circleci/config.yml
package.json
packages/palette/src/elements/Carousel/Carousel.story.tsx
packages/palette/src/elements/Grid/Grid.story.tsx
packages/palette/src/elements/GridColumns/GridColumns.story.tsx
packages/palette/src/elements/Image/Image.story.tsx
packages/palette/src/elements/Modal/ModalBase.story.tsx
packages/palette/src/elements/ProgressDots/ProgressDots.tsx
packages/palette/src/elements/Shelf/Shelf.story.tsx
packages/palette/src/elements/Skeleton/Skeleton.story.tsx
packages/palette/src/elements/Swiper/Swiper.story.tsx
packages/palette/src/themes/Themes.story.tsx

Fixes issue where palette-tokens package can't be found

fix: Fix CI deploys

---

packages/palette/src/elements/BaseTabs/BaseTabs.tsx

This PR fixes end shadow for the BaseTabs component.
JIRA - https://artsyproduct.atlassian.net/browse/PX-3894
Now
https://user-images.githubusercontent.com/79979820/126330787-db77d408-c765-4918-bba7-98cd1318dfc0.mov

fix(PX-3894): fix end shadow for BaseTabs component

---

packages/palette/package.json

Need to get rid of this lerna monstrosity. Its all good until one package depends on another

fix: Make sure to compile monorepo packages before publish

---

packages/palette/src/elements/Input/Input.tsx
packages/palette/src/elements/TextArea/TextArea.story.tsx
packages/palette/src/elements/TextArea/TextArea.tsx
packages/palette/src/elements/TextArea/__tests__/TextArea.test.tsx
packages/palette/src/elements/TextArea/tokens/types.ts
packages/palette/src/elements/TextArea/tokens/v2.ts
packages/palette/src/elements/TextArea/tokens/v3.ts

Finally getting around to updating the textarea since it's needed for inquiries.

feat(textarea): supports v3

---

packages/palette/src/elements/TextArea/TextArea.story.tsx
packages/palette/src/elements/TextArea/TextArea.tsx

fix(textarea): passes default value

---

packages/palette/src/elements/LabeledInput/LabeledInput.story.tsx
packages/palette/src/elements/LabeledInput/LabeledInput.tsx
yarn.lock

Re: https://github.com/artsy/palette/pull/994

fix(labeledinput): correctly threads custom heights

---

.circleci/config.yml
packages/palette-docs/package.json

Somewhere on the golden brick road we lost the path. Not sure how this was ever uploading? Maybe back in netlify days? It's all mysterious

ci: Fix docs deploy 

---

packages/palette-docs/content/docs/atoms/Icons.mdx
packages/palette-docs/content/docs/elements/Button.mdx
packages/palette-docs/content/docs/elements/Collapse.mdx
packages/palette-docs/content/docs/elements/DonutChart.mdx
packages/palette-docs/content/docs/elements/Flex.mdx
packages/palette-docs/content/docs/elements/Select.mdx
packages/palette-docs/content/docs/index.mdx

docs: Cleanup - fix headers

---

packages/palette-docs/content/docs/atoms/Icons.mdx
packages/palette-docs/content/docs/atoms/Spacing.mdx
packages/palette-docs/gatsby-config.js
packages/palette-docs/package.json
packages/palette-docs/src/components/GlobalComponents.jsx
packages/palette-docs/src/components/Sidebar/algolia.css
packages/palette-docs/src/layouts/MainLayout.tsx
packages/palette-docs/src/utils/getEditUrl.ts
yarn.lock

Adds an edit button that links to the source and adds some light cleanup before I attempt an upgrade one more time.

Light cleanup

---

packages/palette/src/helpers/injectGlobalStyles.tsx

Going to check out the canary in Force and see if anything is broken 👁️ 
<details>
<br />
```sh
npm install @artsy/palette@14.53.1-canary.1009.19639.0
yarn add @artsy/palette@14.53.1-canary.1009.19639.0
```
</details>

fix: changes default font to unica; cleans up

---

packages/palette-docs/content/docs/guides/how-palette-works.mdx

docs: Add a how palette works section

---

yarn.lock

Not sure how this happened. Only reason I'm opening a PR for this is because I'm not sure if pushing to master will trigger a release.

chore: checks in lockfile

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx

feat(autocompleteinput): adds loading indicator

---

packages/palette/src/elements/Pill/Pill.tsx
packages/palette/src/elements/Pill/tokens.ts

Brings the `Pill` component inline with [the Figma specs](https://www.figma.com/file/m6gDpKHEWDbYJyrwsVZDBr/Artsy-3.0-Design-System?node-id=604%3A1770)

feat(pill): updates pill variants to match current specs

---

packages/palette/src/elements/Pill/tokens.ts

Updated hover state of "filter" pill for [FX-3170](https://artsyproduct.atlassian.net/browse/FX-3170) ticket
[Figma](https://www.figma.com/file/0svJJjlcrCFBkVYzagKP3Z/FX-v3-Surfaces?node-id=4128%3A1534) spec
Jonathan [comment](https://artsyproduct.atlassian.net/browse/FX-3170?focusedCommentId=41304)

feat(pill): search pill variant

---

packages/palette/src/elements/Modal/ModalBase.tsx

Last minor modal related fix. Keeps the height in sync.

fix(modalbase): keeps maxheight in sync

---

packages/palette/src/elements/Button/Button.story.tsx
packages/palette/src/elements/Button/v3/Button.tsx
packages/palette/src/helpers/color.ts
packages/palette/src/svgs/Icon.tsx

feat(button): improves support for icon buttons

---

packages/palette-docs/content/docs/elements/Pill.mdx
packages/palette/src/elements/Pill/Pill.story.tsx
packages/palette/src/elements/Pill/Pill.tsx

Minor changes to better support Pills with icons.

feat(pill): supports pill with icons

---

packages/palette/src/elements/Modal/Modal.tsx

Fixes a background color without transparency from the Modal.

fix: modal background color

---

packages/palette/src/svgs/_icons.story.tsx

#FF https://github.com/artsy/README/issues/427

fix: blacklist -> blocklist

---

packages/palette/src/elements/Button/Button.story.tsx
packages/palette/src/elements/Button/index.ts
packages/palette/src/elements/Button/v3/Button.tsx

Exports out a few V3 tokens so that we can more accurately style some of these 3rd party elements.

feat: exports button variants/mixin

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
packages/palette/src/utils/useFocusLock.ts

feat(autocomplete): supports footer

---

packages/palette/.storybook/main.js

Fixes issue with hot reloading by lazy loading each story on demand.

fix(storybooks): Hot reloading

---

packages/palette-docs/content/docs/atoms/Icons.mdx

Added a note here based on @dzucconi's feedback on #1123

docs: Add link to svg optimization tool

---

packages/palette-docs/content/docs/elements/IconButton.mdx

docs: Use icon in IconButton example [skip ci]

---

packages/palette/src/elements/ModalDialog/ModalDialog.story.tsx
packages/palette/src/elements/ModalDialog/ModalDialog.tsx

Fix for setting percentage based widths.

fix(modal): fixes support for percentage based widths

---

packages/palette/src/elements/Badge/index.ts
packages/palette/src/elements/index.tsx

Includes `Badge` in exported elements.

fix(badge): includes in exports

---

packages/palette/src/elements/Badge/Badge.story.tsx
packages/palette/src/elements/Badge/Badge.tsx

Re: [GRO-846](https://artsyproduct.atlassian.net/browse/GRO-846)
cc @The-Beez-Kneez

fix(badge): prevents wrapping; handles truncation on badges

---

packages/palette/src/elements/Badge/Badge.tsx

GRO-836: Adding design update for gallery attributes, until further approval on designs met

---

packages/palette/src/elements/Marquee/Marquee.story.tsx
packages/palette/src/elements/Marquee/Marquee.tsx

Had previously forgotten to update the Marquee component along with the Badges for this PR:
https://github.com/artsy/palette/pull/1149

GRO-836 Update: Marquee with newly decided default coloring

---

packages/palette-docs/package.json
packages/palette-docs/src/Boot.tsx
packages/palette-docs/src/layouts/MainLayout.tsx
yarn.lock

Addresses https://artsyproduct.atlassian.net/browse/WP-98
This fixes SSR rendering in our docs that fell out when we upgraded Gatsby from 2 to 3. 
cc @artsy/grow-devs

fix(ssr): Fix docs ssr

---

packages/palette/src/elements/Pill/Pill.story.tsx
packages/palette/src/elements/Pill/Pill.tsx

Fixes a minor issue when actually using the `Pill` component through clicking to toggle.

fix(pills): fixes hover on selected pills

---

packages/palette/src/elements/Range/Range.story.tsx
packages/palette/src/elements/Range/Range.tsx

fix(range): adds ability to label each slider

---

packages/palette/src/Theme.tsx
packages/palette/src/elements/GridColumns/GridColumns.tsx

This is such a crazy breaking change in React and we'll have to add this more throughout the codebase. Just fixing a few immediate issues.

fix(types): adds children to types

---

packages/palette/src/elements/ModalDialog/ModalDialog.story.tsx
packages/palette/src/elements/ModalDialog/ModalDialog.tsx
packages/palette/src/elements/ModalDialog/ModalDialogContent.story.tsx
packages/palette/src/elements/ModalDialog/ModalDialogContent.tsx

Adds some features to the modal dialog to support our authentication dialog layout.

feat(modaldialog): adds left/right panel support

---

packages/palette/src/elements/ModalDialog/ModalDialogContent.story.tsx
packages/palette/src/elements/ModalDialog/ModalDialogContent.tsx

Fix for more narrow content. Includes a story to capture issue.

fix(modaldialogcontent): fixes width for shorter content

---

README.md
packages/palette/src/svgs/_icons.story.tsx

Re: https://github.com/artsy/palette/pull/1234

docs: updates readme

---

packages/palette/src/elements/ModalDialog/ModalDialogContent.story.tsx
packages/palette/src/elements/ModalDialog/ModalDialogContent.tsx
packages/palette/src/elements/Text/Text.tsx

Addressing some minor issues that arose when Q/Aing the new auth dialog.

fix(modaldialog): addresses long titles; focus-visible close state

---

package.json
yarn.lock

Re: https://github.com/lerna/lerna/issues/2788#issuecomment-1192788964

chore(deps): upgrades lerna

---

packages/palette/src/elements/Popover/Popover.tsx
packages/palette/src/elements/Tooltip/Tooltip.story.tsx
packages/palette/src/elements/Tooltip/Tooltip.tsx

Threads through `offset` through to our positioning hook so that it's configurable.

feat(tooltip/popover): supports offset

---

packages/palette/src/elements/ModalDialog/ModalDialog.story.tsx
packages/palette/src/elements/ModalDialog/ModalDialog.tsx
packages/palette/src/elements/ModalDialog/ModalDialogContent.tsx

https://user-images.githubusercontent.com/3513494/219044237-1eef4bee-51c4-42b9-851c-5674728e4424.mp4

feat: add `header` prop for `ModalDialogContent`

---

packages/palette/src/elements/Popover/Popover.tsx

Adjusts vertical padding to align with current design system Figma specs.

fix(popover): adjusts vertical padding

---

packages/palette/src/elements/Popover/Popover.story.tsx
packages/palette/src/elements/Popover/Popover.tsx

Allows us to distinguish between implicit and explicit dismissals.

feat(popover): adds ondismiss callback

---

packages/palette/src/elements/Input/Input.story.tsx
packages/palette/src/elements/Input/tokens.ts

fix(input): corrects display of disabled inputs in safari/mobile safari

---

packages/palette/src/elements/Expandable/Expandable.story.tsx
packages/palette/src/elements/Expandable/Expandable.tsx

Going to use these in inverted color schemes.

feat(expandable): supports color configurations

---

packages/palette/src/elements/Expandable/Expandable.story.tsx
packages/palette/src/elements/Expandable/Expandable.tsx

Adds an event callback for tracking.

feat(expandable): adds event callback

---

packages/palette/src/elements/TextArea/TextArea.tsx
packages/palette/src/elements/TextArea/__tests__/TextArea.test.tsx
packages/palette/src/elements/TextArea/tokens.ts
packages/palette/src/elements/TextArea/types.ts

This PR will be merged to `mrsltun/CX-3330/new-input-component`
This PR resolves [CX-3394]
This PR updates the text area component to match the new design
| Status | Screenshot |
| -- | -- |
| default | <img width="712" alt="image" src="https://user-images.githubusercontent.com/20655703/235922388-15798e8e-65d3-437f-abaf-d026ba56a0c2.png"> |
| with title | <img width="712" alt="image" src="https://user-images.githubusercontent.com/20655703/235923069-3204c92d-28e4-4847-9cb2-5079eccee850.png"> |
| with description | <img width="712" alt="image" src="https://user-images.githubusercontent.com/20655703/235923369-2a551d64-b95b-4b16-aa08-9b22391add9f.png"> <img width="712" alt="image" src="https://user-images.githubusercontent.com/20655703/235923402-e7e54691-7172-4b29-9d3d-9ecc027d0b31.png"> |
| …

feat(CX-3394): Update text area component

---

packages/palette/src/elements/Select/Select.story.tsx
packages/palette/src/elements/Select/Select.tsx
packages/palette/src/elements/Select/__tests__/Select.test.tsx
packages/palette/src/elements/Select/tokens.ts
packages/palette/src/elements/Select/types.ts
packages/palette/src/themes/Themes.story.tsx

This PR will be merged to `mrsltun/CX-3330/new-input-component`
This PR resolves [CX-3669]
This PR updates the Select component to match the new design
As well as removing the `variant`s from the Select component
| Status | Screenshot |
| -- | -- |
| default | <img width="490" alt="image" src="https://github.com/artsy/palette/assets/20655703/5429e193-e0cb-4693-8522-e5c7239be612"> |
| default (with value) | <img width="490" alt="image" src="https://github.com/artsy/palette/assets/20655703/34f6219d-a55d-4908-af69-8c69077c9d77"> |
| with title | <img width="490" alt="image" src="https://github.com/artsy/palette/assets/20655703/c06ff4ee-2574-433d-9998-8a4cf3323fe1"> |
| with title (with value) | <img width="490" alt="image" src="https://github.com/artsy/palette/assets/20655703/8c424454-769d-43 …

feat(CX-3669): Update Select component

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx

This PR can resolve this issue https://artsyproduct.atlassian.net/browse/FX-4788

feat: close dropdown when the footer is clicked

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx

This PR is the follow-up of https://github.com/artsy/palette/pull/1296

chore: reuse handleClose method

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx

Allows for configuration of underlying positioning engine.

feat(autocomplete): allows configuration of clamp/flip

---

packages/palette/src/elements/Drawer/Drawer.tsx

This smooths out the drawer animation a bit, but adjusting the easing and the timing very slightly. 
https://github.com/artsy/palette/assets/236943/34536b94-8949-4c8a-b5f8-760f1d543c4f

chore(drawer): Smooth out animation

---

packages/palette/src/elements/Drawer/Drawer.tsx

Update a bit more to match the nav transition. The ease in on leave was a bit meh  
https://github.com/artsy/palette/assets/236943/7675378f-3b9d-415d-88ff-133acf2e2af0

fix(drawer): Update transition a bit more

---

packages/palette/src/elements/ModalDialog/ModalDialogContent.tsx

We'll expose this for use in custom dialogs.

feat(modaldialog): exposes modal close button

---

packages/palette/src/elements/Pill/Pill.story.tsx
packages/palette/src/elements/Pill/Pill.tsx
packages/palette/src/elements/Pill/tokens.ts

Updates tokens to align with the [Figma spec](https://www.figma.com/file/gZNkyqLT8AU3T61tluVJyB/Artsy-3.1-Design-System?node-id=15073%3A3346)

fix(pill): updates profile + gray tokens

---

packages/palette/src/elements/MultiSelect/MultiSelect.tsx
packages/palette/src/elements/MultiSelect/tokens.ts

This PR resolves [EMI-1371]
This PR updates the **MultiSelect** to match the new design system: https://www.figma.com/file/gZNkyqLT8AU3T61tluVJyB/Artsy-3.1-Design-System?type=design&node-id=13406-39254&mode=design&t=diD5gZWh3yQJ8IuU-0
| Status | Screenshot |
| -- | -- |
| default | ![Screenshot 2023-10-24 at 11 47 27 AM](https://github.com/artsy/palette/assets/23108927/b0523c9e-4bf9-4805-993f-9771058a9d93) |
| focus | ![Screenshot 2023-10-24 at 11 45 56 AM](https://github.com/artsy/palette/assets/23108927/7525fe1b-1f20-4696-bc4e-ebd17b3e3cf1) |
| hover | ![Screenshot 2023-10-24 at 11 48 02 AM](https://github.com/artsy/palette/assets/23108927/913ad69b-9c4a-4c51-8691-020a59dbe528) |
| complete | ![Screenshot 2023-10-24 at 11 48 17 AM](https://github.com/artsy/palette/assets/23108927/6a47f66b …

feat(EMI-1371): update MultiSelect components

---

packages/palette/src/elements/Dropdown/Dropdown.story.tsx

I find this simpler than a dedicated component because quite a few things might vary and you'd just wind up replicating the same exact API for dropdown.

chore(dropdown): adds story conforming to filter ui pattern

---

packages/palette/src/elements/Popover/Popover.story.tsx
packages/palette/src/utils/__tests__/usePosition.test.ts
packages/palette/src/utils/usePosition.ts

Takes care of tooltips & popovers that are anchored within scrollable divs.

fix(useposition): handles scrolling within divs

---

packages/palette/src/elements/Popover/Popover.story.tsx
packages/palette/src/utils/__tests__/usePosition.test.ts
packages/palette/src/utils/usePosition.ts

Revert "fix(useposition): handles scrolling within divs"

---

packages/palette/src/utils/usePortal.ts

Reverts artsy/palette#1349
This is lead to at least one actual bug: https://github.com/artsy/force/pull/13333 and a number of strange spec failures. Reverting until I can investigate further.

Revert "fix(useportal): makes safe for ssr"

---

packages/palette/src/elements/Image/LazyImage.tsx

This file is depressing let's replace this thing.

fix(image): prevents ovewriting display style prop

---

packages/palette/src/elements/Tooltip/Tooltip.tsx

Closes [DIA-492](https://artsyproduct.atlassian.net/browse/DIA-492)
[DIA-492]: https://artsyproduct.atlassian.net/browse/DIA-492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(tooltip): prevent parent from altering font-styles

---

packages/palette/src/elements/Input/Input.story.tsx
packages/palette/src/elements/Input/Input.tsx
packages/palette/src/elements/LabeledInput/LabeledInput.story.tsx

This PR updates the input character counter to fix an issue that happens when we update the Input's value using React's state
|---|---|
| <video src="https://github.com/artsy/palette/assets/20655703/fd845028-0352-469e-92d9-f219633b7320" /> | <video src="https://github.com/artsy/palette/assets/20655703/3c142cd2-4dd0-443b-ad91-5981971c6b91" /> |

fix: input counter issue on Input

---

packages/palette-tokens/src/themes/v3.tsx
packages/palette-tokens/src/themes/v3Dark.tsx
packages/palette/src/elements/Cards/Card.tsx
packages/palette/src/elements/Drawer/Drawer.tsx

* Improves the contrast for text using gradient overlays
* Gradient easing via https://larsenwork.com/easing-gradients/
* Uses the themed backdrop for drawers
<details>
<br />
```bash
npm install @artsy/palette-charts@37.12.2-canary.1389.30751.0
npm install @artsy/palette-tokens@6.0.3-canary.1389.30751.0
npm install @artsy/palette@38.12.2-canary.1389.30751.0
yarn add @artsy/palette-charts@37.12.2-canary.1389.30751.0
yarn add @artsy/palette-tokens@6.0.3-canary.1389.30751.0
yarn add @artsy/palette@38.12.2-canary.1389.30751.0
```
</details>

fix(theme): improves legibility for overlays

---

packages/palette/src/elements/BorderedRadio/BorderedRadio.story.tsx
packages/palette/src/elements/BorderedRadio/BorderedRadio.tsx
packages/palette/src/elements/Radio/Radio.story.tsx
packages/palette/src/elements/Radio/Radio.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.tsx

Closes [DIA-729](https://artsyproduct.atlassian.net/browse/DIA-729)
Re: https://artsy.slack.com/archives/C2TQ4PT8R/p1718623491874389
[DIA-729]: https://artsyproduct.atlassian.net/browse/DIA-729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(radio): supports generic type

---

packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx
packages/palette/src/elements/RadioGroup/RadioGroup.tsx

Re: https://github.com/artsy/palette/pull/1390#issuecomment-2173548642

fix(radiogroup): supports default value of false

---

.circleci/config.yml
package.json

Needed to specify yarn as the CI package manager for CircleCI/node

ci(storybook): Fix storybook compiles on merge

---

packages/palette/src/elements/BorderedRadio/BorderedRadio.tsx

More fixes. 
Before:
https://github.com/user-attachments/assets/611d2573-3c5e-4791-ae31-76132152c329
After: 
https://github.com/user-attachments/assets/4bbed2bd-e7a9-4e4a-b808-d775745d2346

fix(bordered-radio): more border specificity fixes

---

packages/palette/src/elements/Dropdown/Dropdown.story.tsx
packages/palette/src/elements/Dropdown/Dropdown.tsx

This is in support of stabilizing the transitions along the top nav.

feat: adds option to disable transitions

---

packages/palette/package.json
packages/palette/src/elements/Banner/Banner.tsx
packages/palette/src/elements/Button/Button.tsx
packages/palette/src/elements/Input/Input.tsx
packages/palette/src/elements/Label/Label.tsx
packages/palette/src/elements/Marquee/Marquee.tsx
packages/palette/src/elements/Message/Message.tsx
packages/palette/src/elements/Pill/Pill.tsx
packages/palette/src/elements/Spinner/Spinner.tsx
packages/palette/src/elements/Stepper/Stepper.tsx
packages/palette/src/elements/Tabs/Tabs.tsx
yarn.lock

... 
<details>
<br />
```bash
npm install @artsy/palette-charts@39.1.0-canary.1412.31379.0
npm install @artsy/palette@40.1.0-canary.1412.31379.0
yarn add @artsy/palette-charts@39.1.0-canary.1412.31379.0
yarn add @artsy/palette@40.1.0-canary.1412.31379.0
```
</details>

chore(react): Fix deprecations 

---

packages/palette-charts/package.json
packages/palette-charts/src/elements/DataVis/useIntersectionObserver.ts

Addresses [DIA-1032]
Fixes issue where bar chart doesn't initialize on mount. 
[DIA-1032]: https://artsyproduct.atlassian.net/browse/DIA-1032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(bar-chart): Fix init

---

packages/palette-charts/package.json

ci: test deploy 1

---

packages/palette/src/elements/Box/Box.tsx

There's some new design language in coming over on CMS side, and i've been having to manually style these things. Also always noticing having to manually control pointer events. So this adds those two things.

feat(box): add boxShadow and pointerEvents

---

packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx

Adds a repo of the autoselect autofocus bug:
https://github.com/user-attachments/assets/141f6520-6a9e-4309-ab88-7fbf40851f3e
cc @artsy/amber-devs

feat(storybooks): Add autofocus table example

---

packages/palette/src/elements/MultiSelect/MultiSelect.tsx

MultiSelect onBlur and onVisible.

fix: MultiSelect onBlur and onVisible

---

packages/palette/src/elements/PhoneInput/PhoneInput.tsx
packages/palette/src/elements/PhoneInput/__tests__/PhoneInput.test.tsx

Relates to [EMI-2542]
This PR updates the label on the phone input from "Phone Number" to "Phone number".
#minor
[EMI-2542]: https://artsyproduct.atlassian.net/browse/EMI-2542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2542): copy update for phone input label

---

packages/palette/src/elements/ResponsiveBox/ResponsiveBox.story.tsx

Related: https://github.com/artsy/palette/pull/1432

fix(stories): prevents layout thrashing

---

packages/palette/src/elements/PhoneInput/PhoneInput.story.tsx

- Adding a PhoneInput loading story to test a bug in production

chore: Adding PhoneInput loading story
